### ISSUE TITLE
digitalocean_record ttl seems not to be idempotent

### ISSUE THREAD

**Issue by niklasweimann** [digitalocean/terraform-provider-digitalocean#1012]
# Bug Report

## Describe the bug
When there are two TXT for a single Domain with different TTLs the TTL for the individual records is not preserved instead it seems to pick the TTL of the record which is handled first. So with each run the TTL is toggled.

### Affected Resource(s)
- digitalocean_record

### Expected Behavior
When the TTL of one record is set to 60 and the TTL of another record to 1800, i want the records to keep the TTL after applying.

### Actual Behavior
One record looses its TTL and both records get the same TTL assigned.

### Steps to Reproduce
1. Create two record ressources like so:
```
resource "digitalocean_record" "test_txt_1" {
  domain   = digitalocean_domain.example_com.name
  type     = "TXT"
  name     = "@"
  value    = "1"
  ttl      = 60
}

resource "digitalocean_record" "test_txt_2" {
  domain   = digitalocean_domain.example_com.name
  type     = "TXT"
  name     = "@"
  value    = "2"
  ttl      = 1800
}
```
2. Apply the Terraform
3. Go to the Web UI and find the following records:
    1. ![Screenshot 2023-07-18 at 14 07 36](https://github.com/digitalocean/terraform-provider-digitalocean/assets/12865466/0d73cd4c-0ee7-40c4-a990-68c4a24ba7d5)

5. Rerun the Plan and Apply the plan looks like this:
    1. ![Screenshot 2023-07-18 at 14 08 13](https://github.com/digitalocean/terraform-provider-digitalocean/assets/12865466/8c407652-5efd-4149-b494-dac55689c647)

6. Go to the Web UI and find the following records:
    1. ![Screenshot 2023-07-18 at 14 08 40](https://github.com/digitalocean/terraform-provider-digitalocean/assets/12865466/9bb067ae-fbc5-4aa2-a50f-747331806b4a)

**Terraform version**
1.5.3

**Comment by danaelhe** [comment]
Hi @niklasweimann ,

Thank you for your detailed write up. This is actually expected behavior of our API as it follows the "Clarifications to the DNS Specification" RFC recommendations. Per the RFC, when you have multiple records for the same fqdn, they are expected to have the same TTL. For reference, see rfc2181, section 5.2: [ https://www.rfc-editor.org/rfc/rfc2181#section-5]( https://www.rfc-editor.org/rfc/rfc2181#section-5).

**Comment by danaelhe** [comment]
I'm going to close this. Please create another issue if you have any other concerns/questions, thank you so much!

**Comment by DanRStevens** [comment]
It seems like mismatched TTLs in Resource Record Sets should produce some kind of warning. It's very confusing behaviour otherwise. If the code is able to set all records to the same TTL, surely it should be easy to add a warning in that case, and perhaps even list the affected records.

**Comment by danaelhe** [comment]
> multiple records for the same fqdn, they are expected to have the same TTL

I like it! Thanks for offering this feedback, I've created a PR implementing your suggestion 🚀

**Comment by DanRStevens** [comment]
Wow, that was fast. Thanks
