### ISSUE TITLE
Adding a SSH key to a droplet forces a replacement

### ISSUE THREAD

**Issue by rvoortman** [digitalocean/terraform-provider-digitalocean#1019]
# Bug Report
I created some droplets for a Docker Swarm cluster. The cluster is made up of 6 nodes: 3 master and 3 nodes. We login on those with SSH keys. When an employee leaves the company or a new one enters, a SSH key is added and/or removed. 

## Describe the bug
This change in SSH_keys forces the droplets to be completely rebuild however, making this authorization change a real chore, since our whole cluster needs to be rebuild in order to achieve this.

The relevant terraform code:
```hcl
data "digitalocean_ssh_key" "key1" {
  name = "robbin"
}

locals {
  ssh_keys = [
    data.digitalocean_ssh_key.key1.fingerprint
  ]
}

# Example of one droplet
resource "digitalocean_droplet" "docker_swarm_manager" {
  name = "docker-swarm-manager-1"
  region = local.region
  size = "s-1vcpu-1gb"
  image = local.image

  ssh_keys = local.ssh_keys
  vpc_uuid = digitalocean_vpc.docker_swarm_network.id
  tags = ["swarm-manager"]
}
```

Adding another one of the SSH keys forces a replace of the manager droplet. 

### Affected Resource(s)
- digitalocean_droplet
- digitalocean_ssh_key

### Expected Behavior
I expected droplets to be able to dynamically upload and remove SSH keys from the Droplet. 

### Actual Behavior
It replaces the droplets completely.

**Comment by andrewsomething** [comment]
DigitalOcean does not currently offer a way to manage SSH keys on an existing Droplet. Currently, keys can only be added at time of creation. So this is the expected behavior for the Terraform provider. 

General feature requests for DigitalOcean can be submitted at https://ideas.digitalocean.com/

Thanks for the feedback.
