### ISSUE TITLE
Support MySQL database advanced configuration

### ISSUE THREAD

**Issue by danaelhe** [digitalocean/terraform-provider-digitalocean#1042]
**Overview**
Similar to the Redis support added in #1037 but for MySQL. The resource should look like this:
`digitalocean_database_mysql_config`

It should include attributes listed in the API documentation [here](https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_patch_config) (Under request body schema -> config -> MySQL)

**Comment by runz0rd** [comment]
@danaelhe mind if i take this?
