### ISSUE TITLE
Add digitalocean_database_pool as data source

### ISSUE THREAD

**Issue by gvangool** [digitalocean/terraform-provider-digitalocean#1059]
### Is your feature request related to a problem? Please describe.
I was looking for a way to get a database pool URL from a terraform resource.

### Describe the solution you'd like
I'd want to be able to define:
```tf
data "digitalocean_database_pool" "example" {
  cluster_name = "example-cluster"
  pool_name = "pool1"
}
```

So I can do:
```tf
locals {
  conn_str = "postgresql://${data.digitalocean_database_pool.example.username}@${data.digitalocean_database_pool.example.host}:${data.digitalocean_database_pool.example.port}/${data.digitalocean_database_pool.example.database}"
}
```

### Describe alternatives you've considered
I've added the information from the connection pool hardcoded, but it's "one more thing" that needs to be manually updated.

**Comment by T-jegou** [comment]
Hello @andrewsomething , I tried to fix this issue, can you take a look? Thanks

**Comment by gvangool** [comment]
Thanks @T-jegou and @danaelhe! 

#1073 fixed my use case 👍
