### ISSUE TITLE
Unable to set port for health_check

### ISSUE THREAD

**Issue by nemcikjan** [digitalocean/terraform-provider-digitalocean#1077]
# Bug Report

---

## Describe the bug

Unable to set port in health_check block.

### Expected Behavior

Ability to set alternative port for health_check

### Actual Behavior

No option for setting port in health_check block

### Steps to Reproduce

**Terraform Configuration Files**

```terraform
resource "digitalocean_app" "auth-hammerhead" {
  spec {
    name   = "some-app"
    ...
    service {
      http_port          = 4000
      internal_ports     = [1231]
      health_check {
        http_path = "/healthcheck"
      }
      ....
    }
  }
}
```

**Terraform version**

1.6.3
**Debug Output**

**Panic Output**

## Additional context

**Important Factoids**

**References**

**Comment by danaelhe** [comment]
Thank you for bringing this to our attention. The [API](https://docs.digitalocean.com/reference/api/api-reference/#operation/apps_create) does offer setting a `port` for `health_check` so we are able to add this support in the terraform digitalocean provider as well. 

I've added a ticket in our backlog to prioritize this as soon as we can. If you'd like to add the implemmentation in a PR yourself, we're more than happy to review and merge the PR ✅
