### ISSUE TITLE
Change Redis timeout settings not working if setting to zero

### ISSUE THREAD

**Issue by MarcoMatarazzo** [digitalocean/terraform-provider-digitalocean#1106]
## Describe the bug

As reported [here](https://github.com/hashicorp/terraform/issues/5694), getOK is not able to correctly check if an option is set when the value of that option is zero, hence the reason why getOkExists has been created.

Trying to run terraform apply DOES recognize the change to be done and shows it in the plan, but does not apply and does not give any error, as it's behaving as it was not set at all.

This is happening AT LEAST when setting `timeout` value in `digitalocean_database_redis_config`.

This is likely affecting other resource arguments that has zero as a valid value.

### Affected Resource(s)
- digitalocean_database_redis_config

### Expected Behavior
Redis timeout should be set to zero.

### Actual Behavior
Redis timeout is not set to zero, and no error is shown.

### Steps to Reproduce

1. Have a resource like:

```
resource "digitalocean_database_cluster" "redis7" {
  name                 = "redis7-test"
  engine               = "redis"
  version              = "7"
  eviction_policy      = "noeviction"
  size                 = "db-s-2vcpu-4gb"
  node_count           = "1"
  region               = "ams3"
}

resource "digitalocean_database_redis_config" "redis7" {
  cluster_id             = digitalocean_database_cluster.redis7.id
  timeout                = 0
}
```

2. Run `terraform apply`

3. Run `terraform apply` again and see that the change is still there to be applied, or check with DO API.

**Terraform version**
```
Terraform v1.5.3
on darwin_amd64
+ provider registry.terraform.io/digitalocean/digitalocean v2.34.1
+ provider registry.terraform.io/hashicorp/aws v5.32.0
```

**Comment by andrewsomething** [comment]
Thanks for flagging this! I've opened https://github.com/digitalocean/terraform-provider-digitalocean/pull/1108 to address it.
