### ISSUE TITLE
When enabling IPv6 there are extra steps required

### ISSUE THREAD

**Issue by danktec** [digitalocean/terraform-provider-digitalocean#1110]
During the IPv6 enablement process, two things need to happen to fully enable the feature

1. The droplet should be powered off before the enablement happens.
```
PUBLIC IPV6 ADDRESS
Enabling IPv6 will require updates to the network settings of the Droplet. [Read more.](https://docs.digitalocean.com/products/networking/ipv6/how-to/enable/#on-existing-droplets)

Your Droplet must be powered off before enabling public IPv6 network.
```

2. there is a bunch of OS level cloud-init config that needs to happen for IPv6 to actually work. (https://docs.digitalocean.com/products/networking/ipv6/how-to/enable/#on-existing-droplets)
So perhaps a warning message to the user which links these instructions after they enable it.

**Comment by andrewsomething** [comment]
Thanks for the great suggestion @danktec! I've opened a PR to address this https://github.com/digitalocean/terraform-provider-digitalocean/pull/1111
