### ISSUE TITLE
Unable to import digitalocean_uptime_alert by id (import id is wrong)

### ISSUE THREAD

**Issue by fabn** [digitalocean/terraform-provider-digitalocean#1118]
# Bug Report

## Describe the bug

According to the [relevant documentation](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/uptime_alert#import) `digitalocean_uptime_alert` should be importable by ID, but that's not the case because the [relevant endpoint](https://docs.digitalocean.com/reference/doctl/reference/monitoring/uptime/alert/get/) needs also the `check_id` to retrieve the alert.

So a simple block like this won't work

```tf
import {
  id = "caaf5861-a9a5-4dc5-94f2-783e39de0a75" # Existing ID
  to = digitalocean_uptime_alert.api_ssl
}

# Create a latency alert for the uptime check
resource "digitalocean_uptime_alert" "api_ssl" {
  name       = "Test alert"
  check_id   = digitalocean_uptime_check.api.id
  type       = "ssl_expiry"
  threshold  = 10
  comparison = "less_than"
  period     = "2m"
  notifications {
    email = ["user@example.com"]
  }
}
```

It fails with `│ Error: Cannot import non-existent remote object` and if I run the plan with
```
$ TF_LOG=debug terraform plan -target digitalocean_uptime_alert.api_ssl
```

I can clearly see the wrong call made to API

```
-----------------------------------------------------: timestamp="2024-03-01T16:55:48.758+0100"
2024-03-01T16:55:48.758+0100 [INFO]  provider.terraform-provider-digitalocean_v2.34.1: 2024/03/01 16:55:48 [DEBUG] GET https://api.digitalocean.com/v2/uptime/checks//alerts/caaf5861-a9a5-4dc5-94f2-783e39de0a75: timestamp="2024-03-01T16:55:48.758+0100"
2024-03-01T16:55:49.045+0100 [INFO]  provider.terraform-provider-digitalocean_v2.34.1: 2024/03/01 16:55:49 [DEBUG] DigitalOcean API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 404 Not Found
Cache-Control: no-cache
Cf-Cache-Status: DYNAMIC
Cf-Ray: 85da555edd38bac7-MXP
```

As you can see it GETs `https://api.digitalocean.com/v2/uptime/checks//alerts/caaf5861-a9a5-4dc5-94f2-783e39de0a75`

### Affected Resource(s)

- digitalocean_uptime_alert

### Expected Behavior

Resource is retrieved successfully

### Actual Behavior

Cannot import existing resources

Having an id of `<check_id>.<alert_id>` (only for imports) should fix the issue and will allow the API to be called with the right params.

Notice that also `terraform import` won't work for the same reason.

**Comment by andrewsomething** [comment]
I've opened a PR to address this issue: https://github.com/digitalocean/terraform-provider-digitalocean/pull/1119 Thanks for flagging this @fabn!

**Comment by fabn** [comment]
Thanks for your quick response
