### ISSUE TITLE
Release v2.35.0

### ISSUE THREAD

**Issue by virtualroot** [digitalocean/terraform-provider-digitalocean#1123]
# Bug Report

## Describe the bug

[v2.35.0](https://github.com/digitalocean/terraform-provider-digitalocean/releases/tag/v2.35.0) was tagged but [never released](https://github.com/digitalocean/terraform-provider-digitalocean/releases).

### Expected Behavior

For the latest version (v2.35.0) to appear in [Terraform](https://registry.terraform.io/providers/digitalocean/digitalocean/latest) and [OpenTofu](https://registry.opentofu.org/v1/providers/digitalocean/digitalocean/versions) registries.

**Comment by andrewsomething** [comment]
Thanks for flagging this for us! I've published the release:

https://github.com/digitalocean/terraform-provider-digitalocean/releases/tag/v2.35.0
