### ISSUE TITLE
Dedicated egress IP addresses support for App platform

### ISSUE THREAD

**Issue by andrewmarklloyd** [digitalocean/terraform-provider-digitalocean#1151]
### Is your feature request related to a problem? Please describe.

Now that the App platform supports [Dedicated egress IP addresses](https://docs.digitalocean.com/products/app-platform/how-to/add-dedicated-ip), I would love the ability to configure this in Terraform.

### Describe the solution you'd like

The [DigitalOcean App spec](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/app) should have a boolean field to enable this feature. It would also be great to have the two IP addresses that digital ocean provides as attributes to the resource.

Example of configuring the Dedicated egress IP addresses in the Digital Ocean console.

<img width="1139" alt="Screenshot 2024-05-01 at 8 50 32 PM" src="https://github.com/digitalocean/terraform-provider-digitalocean/assets/7810418/9af6fe10-8076-495e-9611-c9e6a93e8587">

Example view of the resulting IP address in the Digital Ocean console.

<img width="1148" alt="Screenshot 2024-05-01 at 8 53 03 PM" src="https://github.com/digitalocean/terraform-provider-digitalocean/assets/7810418/d4abf21b-842f-414e-9464-2e9e30faf25c">

 
### Describe alternatives you've considered

Unfortunately if I configure the Dedicated egress IP addresses using the console, a subsequent Terraform apply will remove the configuration. The only alternative I have at this point is to use the `doctl` cli to configure the app platform.

### Additional context
N/A

**Comment by andrewsomething** [comment]
This was fixed by https://github.com/digitalocean/terraform-provider-digitalocean/pull/1164 and was first available in the v2.39.0 release.

**Comment by andrewmarklloyd** [comment]
Awesome thank you!
