### ISSUE TITLE
Consider adding GPG key to OpenTofu registry for the digitalocean provider

### ISSUE THREAD

**Issue by mig5** [digitalocean/terraform-provider-digitalocean#1158]
### Describe the solution you'd like

I recently switched my infrastructure as code from Terraform to Opentofu.

When init'ing my environment that uses DigitalOcean provider, I saw this warning:

> - Installed digitalocean/digitalocean v1.23.0. Signature validation was skipped due to the registry not containing GPG keys for this provider

I wonder if you might consider adding GPG keys to the OpenTofu registry, if not already planned. This is a similar request to https://github.com/microsoft/terraform-provider-azuredevops/issues/1006

For more information on how to do that:
https://github.com/opentofu/registry/issues/new?assignees=&labels=provider-key%2Csubmission&projects=&template=provider_key.yml&title=Provider+Key%3A+

**Comment by andrewsomething** [comment]
Great idea @mig5! I've submitted our public key in https://github.com/opentofu/registry/issues/544

**Comment by andrewsomething** [comment]
Looks like they've merged the change with the key: https://github.com/opentofu/registry/pull/545 Hopefully that will be live soon, but I'm going to go ahead and close this out as there is nothing left to do on our end.

If you run into anything else that we can do to better support using our provider with OpenTofu, please let us know.
