### ISSUE TITLE
Add OpenSearch Documentation

### ISSUE THREAD

**Issue by ngfgrant** [digitalocean/terraform-provider-digitalocean#1175]
### Is your feature request related to a problem? Please describe.

 
I think it would be useful to include some examples for:

1) Setting up cluster (such as:  https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/database_cluster#create-a-new-postgresql-database-cluster) 
2) OpenSearch config (such as https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/database_mysql_config)
2) Adding/Configuring Managed Database log sink for each available. 
3) Adding/Configuring Log Forwarding Destination for App Platform in the App Platform docs.

### Describe alternatives you've considered

I am not sure there are any alternatives, this should be documented. 

### Additional context

I am happy to assist with some PRs for this.

**Comment by danaelhe** [comment]
Addressed in #1198 🫶 

Thank you for opening the issue!

**Comment by GiovanniColonni** [comment]
I only see [this file ](https://github.com/digitalocean/terraform-provider-digitalocean/pull/1198/files) but it's already merged so maybe I don't understand the request
