### ISSUE TITLE
digitalocean_app: support private docker repositories

### ISSUE THREAD

**Issue by bobbyiliev** [digitalocean/terraform-provider-digitalocean#1179]
### Is your feature request related to a problem? Please describe.

App Platform now supports the use of private docker repositories:

> https://docs.digitalocean.com/products/app-platform/how-to/deploy-from-container-images/#deploy-container-using-the-apps-spec 

### Describe the solution you'd like

The `digitalocean_app` resource should support `registry_credentials` to allow users to use private docker repositories.
 
### Additional context

As per the official documentation:

-   `registry_credentials`: The credentials required to access a private Docker Hub or GitHub registry, in the following syntax `"$username:$token"`. We recommend using a token that doesn’t expire and a scope limited to reading the app’s repository. Review [GitHub](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) and [Docker Hub’s](https://docs.docker.com/security/for-developers/access-tokens/) documentation to see how this is done.

**Comment by andrewsomething** [comment]
Hi Bobby!

We added support for this in v2.37.1, but it looks like we neglected to document it. I've addressed this in 
 https://github.com/digitalocean/terraform-provider-digitalocean/pull/1180

**Comment by bobbyiliev** [comment]
Awesome! Thank you for the update!
