### ISSUE TITLE
How can I provision a "Dev Database"?

### ISSUE THREAD

**Issue by bartekpacia** [digitalocean/terraform-provider-digitalocean#1205]
Basically the question.

I ran:

```console
curl -fsSL -X GET \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" \
  "https://api.digitalocean.com/v2/databases/options" \
  | jq '.options.pg'
```

but I don't see the size for Dev Database:

<img width="1173" alt="Screenshot 2024-09-06 at 20 57 02" src="https://github.com/user-attachments/assets/1abc1588-5e70-49e2-a8a9-f01134d02660">

**Comment by andrewsomething** [comment]
A "Dev Database" is a component of an App Platform app. It is not a standalone offering and can only be created via App Platform.

See: https://docs.digitalocean.com/products/app-platform/how-to/manage-databases/#connect-to-a-dev-database

With Terraform, you can add a "Dev Database" to an app by adding a `database` with `production = false`. For example:

```hcl
resource "digitalocean_app" "golang-sample" {
  spec {
    name   = "golang-sample"
    region = "nyc"

    service {
      name               = "go-service"
      environment_slug   = "go"
      instance_count     = 1
      instance_size_slug = "apps-s-1vcpu-1gb"

      git {
        repo_clone_url = "https://github.com/digitalocean/sample-golang.git"
        branch         = "main"
      }
    }

    database {
      name       = "dev-db"
      engine     = "PG"
      production = false
    }
  }
}
```

See: https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/app

**Comment by bartekpacia** [comment]
I see, thanks a ton!
