### ISSUE TITLE
Enable failing linter: errcheck

### ISSUE THREAD

**Issue by loosla** [digitalocean/terraform-provider-digitalocean#1227]
Some linters are disabled. 
Please enable the failing `errcheck` linter and make the necessary changes to ensure that the checks pass.

Steps:
1. Uncomment `errcheck` in https://github.com/digitalocean/terraform-provider-digitalocean/blob/6593bad18758574921e74670c9df08ca8e982566/.golangci.yml#L30
1. Run `make lint` from the root directory of the repo to see the issues to fix
1. Fix the issues to make `make lint` pass

**Comment by TheMarvelFan** [comment]
Hi, 

Iis anyone working on this issue?
I would like to take it up if no one is.

Thanks.

**Comment by TheMarvelFan** [comment]
Hi @loosla ,

I have created the PR to fix this issue. Please review the changes and let me know if any further modifications are reuiqred.

Thanks!

**Comment by TheMarvelFan** [comment]
@loosla 

Also before merging the PR, I request you to change the label on this issue from 'hacktoberfest' (with a small 'h') to 'Hacktoberfest' (with a capital 'H'), as the Hacktoberfest website is only detecting issues labeled with 'Hacktoberfest'.

Hope this is understandable.

Thanks!
