### ISSUE TITLE
Unable to provision spaces bucket in certain regions where it is available

### ISSUE THREAD

**Issue by alephtwo** [digitalocean/terraform-provider-digitalocean#1248]
I'm trying to provision a new Spaces bucket in TOR1 and am currently blocked by the region allow list:

https://github.com/digitalocean/terraform-provider-digitalocean/blob/f650bc286dc0bccf874b07966723a5548384d55f/digitalocean/spaces/spaces_buckets.go#L15

This list should probably be updated to account for which regions support Spaces currently.

**Comment by loosla** [comment]
Good catch, Ben! We need to add `tor1` to this list.
