### ISSUE TITLE
Add support for Droplet backup_policy schema (Daily backups)

### ISSUE THREAD

**Issue by connorhsm** [digitalocean/terraform-provider-digitalocean#1254]
### Is your feature request related to a problem? Please describe.

Earlier this year, DO released daily backup frequency for Droplets. Before this, there existed an ability to configure weekly backups to occur on a specific day and time of the week.

None of this functionality is currently possible via this provider.

![image](https://github.com/user-attachments/assets/764e92e9-eaf7-4f06-b6fd-91f95860248e)

### Describe the solution you'd like

Ability to configure the `backup_policy` parameter as specified by the [DO API](https://docs.digitalocean.com/reference/api/api-reference/#operation/droplets_create).
![image](https://github.com/user-attachments/assets/80e2145a-e6d4-4435-a698-e57bd8ac08ff)

 
### Describe alternatives you've considered

N/A

**Comment by andrewsomething** [comment]
This was added in https://github.com/digitalocean/terraform-provider-digitalocean/pull/1261 and was first released in [v2.44.0](https://github.com/digitalocean/terraform-provider-digitalocean/releases/tag/v2.44.0)
