### ISSUE TITLE
`opensearch_acl` attempting to be set in digitalocean_database_user data, even when no settings block

### ISSUE THREAD

**Issue by iainsproat** [digitalocean/terraform-provider-digitalocean#1289]
# Bug Report

Bumping from `digitalocean/digitalocean` `2.39.2` to `2.46.0`, with an existing DigitalOcean Postgres database cluster and user.

On running terraform plan, an error is reported related to `opensearch_acl`. I do not use opensearch and am not defining any opensearch resources in the terraform plan.

## Describe the bug

An error is thrown when updating digitalocean_database_user

```
Error: Error setting user settings: &errors.errorString{s:"Invalid address to set: []string{\"settings\", \"0\", \"opensearch_acl\"}"}
...
data "digitalocean_database_user" "doadmin" {
```

### Affected Resource(s)

- data digitalocean_database_user

### Expected Behavior

The plan should have run without error.

### Actual Behavior

```
Error: Error setting user settings: &errors.errorString{s:"Invalid address to set: []string{\"settings\", \"0\", \"opensearch_acl\"}"}
...
data "digitalocean_database_user" "doadmin" {
```

### Steps to Reproduce

1. Create a Postgres database cluster & database user (doadmin will suffice) in DigitalOcean UI
2. Create a Terraform data for `digitalocean_database_user`, referencing the ID of the existing resource.

```terraform
data "digitalocean_database_user" "doadmin" {
  cluster_id = "my-postgres-cluster-id"
  name       = "doadmin"
}
```

4. Run terraform plan with terraform version 2.46.0

**Terraform Configuration Files**

**Terraform version**

`v1.9.8`

**Debug Output**

**Panic Output**

## Additional context

**Important Factoids**

**References**

**Comment by andrewsomething** [comment]
Hi @iainsproat, 

Thanks for flagging this issue! The change in https://github.com/digitalocean/terraform-provider-digitalocean/pull/1290 should resolve this. We just cut a new v2.46.1 release with it that should be available on the Terraform registry shortly.
