### ISSUE TITLE
digitalocean_image resource?

### ISSUE THREAD

**Issue by arianvp** [digitalocean/terraform-provider-digitalocean#160]
This provider has a `digitalocean_image` data source, but since recently, it's also
supported to create custom images on digitalocean (https://developers.digitalocean.com/documentation/v2/#create-a-custom-image)

Would it be possible to expose this api as a `resource digitalocean_image`, similar to

https://www.terraform.io/docs/providers/google/r/compute_image.html
https://www.terraform.io/docs/providers/aws/r/ami.html

?

**Comment by andrewsomething** [comment]
This will need to land in godo first in order to enable this: https://github.com/digitalocean/godo/pull/186

**Comment by woods** [comment]
Good news. Looks like that branch got completed and merged in godo ☝️

**Comment by andrewsomething** [comment]
Just wanted to mention that support for importing custom images landed in Packer 1.3.5. Depending on your use cases, that might be a better solution: https://www.packer.io/docs/post-processors/digitalocean-import.html

**Comment by arianvp** [comment]
That is orthogonal to this issue. Once you deploy an image with packer you need to be able to refer to it when creating an instance with Terraform which is currently not possible. Hence this issue

**Comment by andrewsomething** [comment]
> That is orthogonal to this issue.

Right. Just thought it would be worth mentioning for anyone stumbling across this issue.

> Once you deploy an image with packer you need to be able to refer to it when creating an instance with Terraform which is currently not possible. 

Custom images can be referenced just like any other DigitalOcean image. If you've created an image manually or with Packer, you can use the image datasource: https://www.terraform.io/docs/providers/do/d/image.html

**Comment by tyranron** [comment]
Any news on this? Landing custom images or ability to install custom OS via rescue mode like [HCloud does](https://www.terraform.io/docs/providers/hcloud/r/server.html#rescue) is quite vital.
