### ISSUE TITLE
Add digitalocean_firewall datasource

### ISSUE THREAD

**Issue by aslafy-z** [digitalocean/terraform-provider-digitalocean#188]
### Terraform Version
```
Terraform v0.11.11
+ provider.digitalocean v1.1.0
```

### Affected Resource(s)
- digitalocean_firewall
- digitalocean_kubernetes_cluster

### Use case

I'd like to add some rules to the firewall that is automatically created with a `digitalocean_kubernetes_cluster` resource (to fix this bug: https://www.digitalocean.com/community/questions/using-do-managed-kubernetes-cluster-with-helm-chart-stable-prometheus-results-in-some-node_exporters-being-unreachable).

I found a way using `terraform import` mentioned in the docs ( https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/website/docs/r/firewall.html.markdown#import) but it doesn't allow me to create my infrastructure with only one `terraform apply`, and, the `digitalocean_firewall.id` is not exposed in the state, which doesn't allow me to import it without having to rely on `doctl` and tags.

Is there any other way of importing the resource programmatically within my first `apply` step? Would it work if I add another firewall and associate it with my cluster droplets?

I'm unsure if a datasource for `digitalocean_firewall` would help but still, it misses.

Thanks for your insights.

**Comment by aslafy-z** [comment]
I've been able to add rules by adding another firewall bound on the same droplets:


```
resource "digitalocean_firewall" "node-exporter" {
  name = "k8s-${digitalocean_kubernetes_cluster.cluster.id}-worker-node-exporter"

  droplet_ids = ["${data.digitalocean_droplet.workers.*.id}"]

  inbound_rule = [
    {
      protocol         = "tcp"
      port_range       = "9100"
      source_addresses = ["10.0.0.0/8", "172.16.0.0/20", "192.168.0.0/16"]
    },
  ]
}
```

If this is the intended of doing so, it would be great to add a mention in the docs. I think this issue can stay open regarding the implementation of a `digitalocean_firewall` datasource. WDYT?

**Comment by rivernews** [comment]
Exactly the issue I am coming across, currently no direct way to point the firewall to the kubernetes cluster, only to individual droplets, but kubernetes will dynamically scale up/down the droplets.

**Comment by hongkongkiwi** [comment]
Yea, in this case I'd like to attach an existing firewall to my new droplet, but it seems I have no way to get the firewall id from name. This was recently fixed with project, it would be great to see a firewall datasource as well.

**Comment by hongkongkiwi** [comment]
Specifically I need the ability to add our newly created droplet to an existing firewall rule, this is extremely difficult and non-intuitive with the current code as it's designed really for creating a new firewall and adding a list of droplet_ids to it.

If we had a firewall datasource, I could get the existing ids and just push my new id to it and update.

**Comment by rivernews** [comment]
@hongkongkiwi Just want to provide my solution a year after for adding additional firewall rules to kubernetes cluster droplets:

1. Create an additional `digitalocean_firewall` resource and add your rules there.
2. Create a resource `digitalocean_tag`:

```tf
resource "digitalocean_tag" "my-tag" {
  name = "my-tag
}
```

3. **Use the tag to link firewall and your kubernetes cluster default node pool together**.
4. On the firewall resource you created, link the firewall with tag:

```tf
resource "digitalocean_firewall" "my-firewall" {
  tags = [digitalocean_tag.my-tag.id]
}
``` 

5. On the kubernetes cluster node pool, link the tag as below:

```tf
resource "digitalocean_kubernetes_cluster" "my-cluster" {
  node_pool {
    tags = [digitalocean_tag.my-tag.id]
  }
}
```

Now whenever kubernetes cluster scale up / down any droplet, each droplet will have the firewall you created attached, and the ports you opened in your firewall will now be allowed for those droplets. Looks like digitalocean will automatically link resources with the same tag together, so now your node pool is tied with your firewall. In this way you no longer need to modify the default firewall.

Of course, this only applies to the default node pool. What if you have another node pool besides the k8s cluster default node pool? You add the tag just in the same way:

```tf
resource "digitalocean_kubernetes_node_pool" "my-extra-pool" {
    tags = [digitalocean_tag.my-tag.id]
}
```

Now all your droplets scaled by `my-extra-pool` will be automatically attached with your firewall in the same way.
