### ISSUE TITLE
digitalocean_certificate always create duplicates

### ISSUE THREAD

**Issue by marcuslind90** [digitalocean/terraform-provider-digitalocean#318]
Hi there,
I'm having issues with the digitalocean_certificate where it always thinks that there should be a NEW certificate created when an identical one actually already exists. This leads to errors due to duplicate names.

The only way I figured around this is to change my certificate name every time I want to deploy with my CI/CD Pipeline. Very inconvenient. There is an existing issue (see below) that mention similar issues, and the fix suggested does not seem to solve anything.

### Terraform Version
Terraform: 0.12.10
DigitalOcean provider: 1.9.1

> Downloading plugin for provider "digitalocean" (terraform-providers/digitalocean) 1.9.1...

### Affected Resource(s)
- digitalocean_certficiate

### Terraform Configuration Files
```hcl
resource "digitalocean_certificate" "mysitecertificate" {
    name = "mysitecertificate"
    type = "lets_encrypt"
    domains = ["mysite.tld"]

    lifecycle {
        create_before_destroy = true
    }
}
```

### Debug Output
It identifies the certificate as something new, it does not identify that there is an existing certificate and that it is being updated. It just says `+`.
https://gist.github.com/marcuslind90/4e5819125db24034bf3b88ec5d65f138

### Expected Behavior
The certificate has not been updated, so I do not expect it to be changed -- or if it has been changed, it should be able to update it without breaking the pipeline by using the lifecycle block as described by @TFaga  here:
https://github.com/terraform-providers/terraform-provider-digitalocean/issues/98

### Actual Behavior
When I write `terraform plan` it identifies the existing certificate as something new and attempts to create a new one when an existing identical one already exists.

Later when I execute `terraform apply` it leads to the error:

> Error creating Certificate: POST https://api.digitalocean.com/v2/certificates: 422 (request "8fcf7597-a299-435a-bef2-8ea8ba480373") name is not unique

### References
https://github.com/terraform-providers/terraform-provider-digitalocean/issues/98

**Comment by marcuslind90** [comment]
I did find the following quote in the loadbalancer docs where they are saying "you must also change the name of the certificate". So every single commit to master someone has to also update the certificate name?

https://www.terraform.io/docs/providers/do/r/loadbalancer.html

> When managing certificates attached to the load balancer, make sure to add the create_before_destroy lifecycle property in order to ensure the certificate is correctly updated when changed. The order of operations will then be: Create new certificate -> Update loadbalancer with new certificate -> Delete old certificate. When doing so, you must also change the name of the certificate, as there cannot be multiple certificates with the same name in an account.

**Comment by andrewsomething** [comment]
Hi @marcuslind90. I'm not able to reproduce this issue. Could you provide some additional details to help us understand the problem? Are you attempting to re-use a certificate that you created outside of Terraform? In that case, you would be better served by using the certificate datasource rather than the resource. See: https://www.terraform.io/docs/providers/do/d/certificate.html

> So every single commit to master someone has to also update the certificate name?

No. You would only need to use a new name for the certificate if you are looking to replace an existing certificate.

**Comment by marcuslind90** [comment]
Hi @andrewsomething! As I pasted on top in the original post, I am using a lets_encrypt certificate that is created by DigitalOcean. I use this certificate in a load balancer resource at DigitalOcean.

Every time (or at least, very often) when I run terraform in my CI/CD Pipeline it believes that a new certificate should get created. It then errors out due to duplicate names (since the name is hardcoded in the terraform config). 

I was able to temporary solve this by using the random provisioner and generate a random id to append to the resource name. That makes sure that each certificate is unique each time I run terraform. However -- this does not feel like it should be required and it do feel a bit hacky.

**Comment by andrewsomething** [comment]
>  I am using a lets_encrypt certificate that is created by DigitalOcean.

This was created via Terraform?

> when I run terraform in my CI/CD Pipeline it believes that a new certificate should get created.

Is Terraform state saved between CI runs? Are other resources identified as needing to be created?

**Comment by marcuslind90** [comment]
Yes @andrewsomething, the `lets_encrypt` certificate was created using Terraform. It was never manually created from the DigitalOcean dashboard.

This is the only resource that always get marked as having to be created. The other resources work as expected with saved state. The state is stored in Amazon S3.

**Comment by e1nh4nd3r** [comment]
I think I started running into this bug recently myself.  Did your runs emit `500` responses when hitting the `/v2/certificates` endpoint during a `tf apply` run?

```
Error: Error creating Certificate: POST https://api.digitalocean.com/v2/certificates: 500 Server Error
```

**Comment by e1nh4nd3r** [comment]
I think I might have figured out my problem, but it's a different one from this.  I'm validating now.
