### ISSUE TITLE
Add support for node taint

### ISSUE THREAD

**Issue by botzill** [digitalocean/terraform-provider-digitalocean#374]
Hi.

I think will be really useful to have support for taints: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

At the moment I want to start some nodes which accepts only specific pods to be run.

Thx.

**Comment by tombh** [comment]
#379 says that it "implements" this issue. By that I think it merely means that it supports `nodeSelector`s, which although isn't the same as tain/tolerations, does allow you to achieve pretty much the same thing.

Docs on node affinity (`nodeSelector` etc): https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

**Comment by andrewsomething** [comment]
The DO API has now grown support for adding taints to nodes making this something the provider should now be able to support:

https://developers.digitalocean.com/documentation/changelog/api-v2/persistent-node-pool-taints/

**Comment by vkruoso** [comment]
This is not in the DO UI yet, but it would be great to have it in the terraform provider first.

**Comment by baszalmstra** [comment]
Very much looking forward to this feature!

**Comment by Xplouder** [comment]
Looking for this feature!
as @andrewsomething said, looks like the API already support it:
https://www.digitalocean.com/docs/kubernetes/#6-october-2020
https://developers.digitalocean.com/documentation/v2/#create-a-new-kubernetes-cluster
