### ISSUE TITLE
Add ca_cert_pem attribute to digitalocean_database_cluster

### ISSUE THREAD

**Issue by mleonhard** [digitalocean/terraform-provider-digitalocean#388]
Hi DigitalOcean Team,
I'm setting up a managed postgres database and clients.  The database uses a certificate that is signed by the project's certificate authority (CA).  The clients need a copy of the CA certificate to prevent MITM and theft of user data.  I found no way to automatically obtain this certificate.  Would you please add one?

Suggestions:
1. Add `data.digitalocean_project`.
   - Looks up the project associated with the provider's DigitalOcean API token
   - Useful for folks who create their DigitalOcean projects manually, not putting them under control of Terraform.
   - Allows modules to access project-level data without importing from the remote state of the Terraform config that contains the `digitalocean_project` resource.
2.  Add a `data.digitalocean_project.ca_cert_pem` attribute.
3. Optionally, add a `ca_cert_pem` attribute to the `digitalocean_project` resource, for consistency.

Sincerely,
Michael

**Comment by andrewsomething** [comment]
Hi! The CA certificate for a database cluster is not associated with a project. I think it would be more appropriate for it to be part of the database resource itself. Though I definitely agree exposing this via Terraform would be extremely useful. Unfortunately, DigitalOcean API does not currently expose this. I've flagged this issue with the DigitalOcean databases product manager.

**Comment by mleonhard** [comment]
Thanks for your quick reply and clarification!

Minor item: The database cluster returns a certificate that states it is signed by "Project CA".  Renaming it to "Cluster CA" could prevent confusion.

Debugging command: To view the certificate provided by a Postgres service, use OpenSSL 1.1.1 or newer and pass the `-starttls postgres` argument.  MacOS has an old version that doesn't support 'postgres'.  We can use a newer one from Alpine:
```
$ docker run --rm -i -t alpine:3.11 sh -c '
  apk add openssl &&
  (echo |openssl s_client -starttls postgres -host private-NNN-db-cluster-do-user-NNN-0.db.ondigitalocean.com -port 25061)'
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/1) Installing openssl (1.1.1d-r3)
Executing busybox-1.31.1-r9.trigger
OK: 6 MiB in 15 packages
CONNECTED(00000003)
depth=1 CN = a4e1475f-c078-49f3-bae8-71a8de7a05c6 Project CA
verify error:num=19:self signed certificate in certificate chain
verify return:1
depth=1 CN = a4e1475f-c078-49f3-bae8-71a8de7a05c6 Project CA
verify return:1
depth=0 ST = service, O = a4e1475f-c078-49f3-bae8-71a8de7a05c6, CN = db-cluster-1
verify return:1
---
Certificate chain
 0 s:ST = service, O = a4e1475f-c078-49f3-bae8-71a8de7a05c6, CN = db-cluster-1
   i:CN = a4e1475f-c078-49f3-bae8-71a8de7a05c6 Project CA
 1 s:CN = a4e1475f-c078-49f3-bae8-71a8de7a05c6 Project CA
   i:CN = a4e1475f-c078-49f3-bae8-71a8de7a05c6 Project CA
---
Server certificate
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
subject=ST = service, O = a4e1475f-c078-49f3-bae8-71a8de7a05c6, CN = db-cluster-1

issuer=CN = a4e1475f-c078-49f3-bae8-71a8de7a05c6 Project CA

---
No client certificate CA names sent
Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:ECDSA+SHA1:RSA+SHA224:RSA+SHA1
Shared Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3431 bytes and written 487 bytes
Verification error: self signed certificate in certificate chain
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 3072 bit
Secure Renegotiation IS NOT supported
No ALPN negotiated
Early data was not sent
Verify return code: 19 (self signed certificate in certificate chain)
---
DONE
```

**Comment by rgbrizzlehizzle** [comment]
Hey looks like I'm dragging up an old thread but I think this is necessary for users to truly automate the provisioning of Mongo instances.  From the DO managed mongo db docs 

> SSL connections are required, you will need to use a TLS compatible MongoDB client in combination with the CA certificate to connect.

I see on a provisioned database there is a button to download the cert, but that doesn't scale for automatically provisioned instances. 

Is it still the case that there is no programatic access to these certs? If so, is that something that is on the roadmap? Or perhaps allowing users to opt in to less restrictive connection requirements?

**Comment by andrewsomething** [comment]
Hi @rgbrizzlehizzle 

This has recently been added to the API for programatic access:

https://docs.digitalocean.com/reference/api/api-reference/#operation/get_ca

`GET https://api.digitalocean.com/v2/databases/{database_cluster_uuid}/ca`

Adding a data source for this is on the roadmap.

**Comment by rgbrizzlehizzle** [comment]
Fantastic 🎉

**Comment by rgbrizzlehizzle** [comment]
@andrewsomething is there an ETA on when this is planned to be tackled?  i believe with the latest `2.12.1` release all other bugs have been squashed as far as a fully automated mongo deployment goes :)

**Comment by andrewsomething** [comment]
@rgbrizzlehizzle  I've just opened a PR for this https://github.com/digitalocean/terraform-provider-digitalocean/pull/717
