### ISSUE TITLE
Kubernetes node pool should not accept min size = 0

### ISSUE THREAD

**Issue by nrmitchi** [digitalocean/terraform-provider-digitalocean#436]
This is likely an issue with the API side of the DigitalOcean provider, however the provider could do some basic validation as well.

I've been having some issues with the cluster autoscaler behaviour not functioning (I am [not the only one](https://www.digitalocean.com/community/questions/cluster-autoscaling-does-not-seem-to-work)), and it has since been confirmed by digital ocean support that digital ocean does not support autoscaling with node pools with a min size of 0.

The behaviour of the autoscaler appears to be that if any node pools in the cluster have a min size of 0, the cluster autoscaler does not function. This matches with the behaviour I have seen in my own testing.

The node pool min size for anything in the autoscaling attribute should validate that min size must be >= 1.

This is more concerning due to the fact that the [autoscaling node pool example](https://www.terraform.io/docs/providers/do/r/kubernetes_node_pool.html) uses a min size of 0.

### Terraform Version
```
Terraform v0.12.24
+ provider.digitalocean v1.18.0
```
 
### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_kubernetes_cluster
- digitalocean_kubernetes_node_pool

### Terraform Configuration Files
```
resource "digitalocean_kubernetes_cluster" "foo" {
  name    = "foo"
  region  = "nyc1"
  version = "1.15.5-do.1"

  node_pool {
    name       = "front-end-pool"
    size       = "s-2vcpu-2gb"
    node_count = 1
  }
}

resource "digitalocean_kubernetes_node_pool" "autoscale-pool-01" {
  cluster_id = digitalocean_kubernetes_cluster.foo.id
  name       = "autoscale-pool-01"
  size       = "s-1vcpu-2gb"
  auto_scale = true
  min_nodes = 0
  max_nodes = 5
}
```

### Expected Behavior
Node pools which are accepted by the API are valid and function as described.

### Actual Behavior
An accepted-as-valid node pool with a min_size of 0 causes the cluster autoscaler to not function.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a kubernetes cluster, and a second node pool with `autoscale = true` and `min_size = 0`
2. `terraform apply`
3. Deploy _something_ to the cluster, and then increase the replicas (`kubectl scale --replaces=X`)
4. Notice that the cluster does not autoscale, and there are no autoscaling-related events published against the scaled resource

**Comment by pbecotte** [comment]
I have been going back and forth with support for literally weeks with them trying to figure out why my node pools don't auto-scale. Thanks!
