### ISSUE TITLE
digitalocean_project gets destroyed when i try to destroy only the digitalocean_droplet attached with it

### ISSUE THREAD

**Issue by paulocorreaslz** [digitalocean/terraform-provider-digitalocean#459]
Hi guys,

I'm having a problem trying to destroy a droplet using the command "destroy" with the "-target" parameter. Instead of destroying only the droplet, the terraform also destroys the project that the droplet is linked to.

### Terraform Version
terraform version 0.12.28
provider.digitalocean v1.9.1

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_droplet
- digitalocean_project

### Terraform Configuration Files
 ```
resource "digitalocean_project" "homologacao" {
  name        = "Homologacao"
  description = "Projeto de maquinas com web services de ambiente em homologacao"
  purpose     = "Web Application"
  environment = "Staging" 
  resources   = [
        "digitalocean_droplet.wsteste01.urn",
        "digitalocean_droplet.teste02.urn"
    ]
}

resource "digitalocean_droplet" "wsteste01" {
  name               = "ubuntu-nyc1-wsteste-01"
  image              = var.ubuntu18 # ubuntu-18-04-x64
  region             = "nyc1"
  size               = var.sta1vcpu1gb25hd #
  private_networking = true
  backups            = true
  resize_disk        = false
  ipv6               = true
  tags               = ["default"]
}

resource "digitalocean_droplet" "test02" {
  name               = "ubuntu-nyc1-test-02"
  image              = var.ubuntu18 # ubuntu-18-04-x64
  region             = "nyc1"
  size               = var.sta1vcpu1gb25hd 
  private_networking = true
  backups            = true
  resize_disk        = false
  ipv6               = true
}

variable "sta1vcpu1gb25hd" {
  description = "Standard Basic"
  default     = "s-1vcpu-1gb"
}

variable "ubuntu18" {
  description = "Default ubuntu 18 LTS"
  default     = "ubuntu-18-04-x64"
}

provider "digitalocean" {
    token   = var.do_token
    version = "1.9.1"
}

variable "do_token" {
  default = "my_token"
}

variable "pub_key" {
  default = "/home/paulo/.ssh/id_rsa.pub"
}

variable "pvt_key" {
  default = "/home/paulo/.ssh/id_rsa"
}

variable "ssh_fingerprint" {
  default = "private"
}
```

### Debug Output
https://gist.github.com/paulocorreaslz/5f2926821cf473516596b24b4ed8935f

### Panic Output
no panic output

### Expected Behavior
when i run the command "terraform destroy -target digitalocean_droplet.test02" the terraform should only destroy the droplet and maintain the project that it is attached it
### Actual Behavior
when i run the command "terraform destroy -target digitalocean_droplet.test02", the terraform destroy both assets, the droplet and the project, even with another droplet "wtest01" attached to it, leaving it with no project.
 
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform destroy -target digitalocean_droplet.test02`

### Important Factoids
It's a normal account at digitalocean.

### References
I didn't found another reference oppened or closed.

**Comment by andrewsomething** [comment]
Hi @paulocorreaslz,

According to the upstream Terraform documentation, this is actually the intended behavior when using the `-target` flag. From https://www.terraform.io/docs/commands/destroy.html

> The `-target` flag, instead of affecting "dependencies" will instead also destroy any resources that _depend on_ the target(s) specified. For more information, see [the targeting docs from terraform plan](https://www.terraform.io/docs/commands/plan.html#resource-targeting).

I agree that isn't very intuitive, but as the debug output notes:

> The -target option is not for routine use, and is provided only for
> exceptional situations such as recovering from errors or mistakes, or when
> Terraform specifically suggests to use it as part of an error message.

In most cases, you will want to just remove the individual resource from your config and re-run `terraform apply` in order to destroy it.

Let me know if there's anything else we can do to help. Please feel free to reopen the issue if I have misunderstood the problem.

**Comment by paulocorreaslz** [comment]
Thank you for the answer @andrewsomething , you are right in everything that you said.

It's not routine, and i do agree with you, its not a very intuitive behaviour in that situation. By the way, your suggestion is very precise for my case. 

I only think really strange that i can destroy my droplets with the doctl without interfere with the project.

Thank you again and be safe.
