### ISSUE TITLE
digitalocean_container_registry_docker_credentials defaults inconsistent with api limits leads to silent failure

### ISSUE THREAD

**Issue by caligin** [digitalocean/terraform-provider-digitalocean#466]
### Terraform Version
v0.12.28, provider v1.21.0

### Affected Resource(s)

- digitalocean_container_registry_docker_credentials

### Terraform Configuration Files

actual resource names replaced with example ones, my setup follows almost literally the one provided in the provider documentation [here](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/container_registry_docker_credentials) 

```hcl
provider "digitalocean" {
}

resource "digitalocean_kubernetes_cluster" "cluster" {
  name    = "cluster"
  region  = "lon1"
  version = "1.16.6-do.0"
  tags    = ["tag"]

  node_pool {
    name       = "worker-pool"
    size       = "s-1vcpu-2gb"
    node_count = 1
  }
}

resource "digitalocean_container_registry" "registry" {
  name = "registry"
}

resource "digitalocean_container_registry_docker_credentials" "registry-cluster" {
  registry_name  = digitalocean_container_registry.registry.name
}

provider "kubernetes" {
  load_config_file = false
  host             = digitalocean_kubernetes_cluster.cluster.endpoint
  token            = digitalocean_kubernetes_cluster.cluster.kube_config[0].token
  cluster_ca_certificate = base64decode(
    digitalocean_kubernetes_cluster.cluster.kube_config[0].cluster_ca_certificate
  )
}

resource "kubernetes_secret" "cluster-registry-registry-access" {
  metadata {
    name = "docker-cfg"
  }

  data = {
    ".dockerconfigjson" = digitalocean_container_registry_docker_credentials.registry-cluster.docker_credentials
  }

  type = "kubernetes.io/dockerconfigjson"
}
```

### Debug Output

[relevant section of trace output with ids redacted](https://gist.github.com/caligin/f908c06e21a8f1c42d11ad8a3e0083d0) (happy to actually provide the full output privately if needed):

### Expected Behavior

apply completes creating a `digitalocean_container_registry_docker_credentials` and a `kubernetes_secret` resource succesfully

OR

apply fails creating a `digitalocean_container_registry_docker_credentials` resource with a clear message about maximum `expiry_seconds`

### Actual Behavior

apply creates a `digitalocean_container_registry_docker_credentials` with apparently `null` `docker_credentials` value, terraform fails apply with:
```
Error: Secret "docker-cfg" is invalid: data[.dockerconfigjson]: Required value

  on main.tf line 43, in resource "kubernetes_secret" "cluster-registry-registry-access":
  43: resource "kubernetes_secret" "cluster-registry-registry-access" {

```

### Steps to Reproduce

`terraform apply` the above configuration

### Important Factoids

I created my tf configuration following the official documentation for provider version 1.21.0 [here](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/container_registry_docker_credentials), it states that `expiry_seconds` defaults to roughly 68 years but in the tf trace output the API is clearly rejecting this value specifying that the max is 50 years.

changing the configuration setting an explicit `expiry_seconds = 1576800000` (roughly 50 years w/o, taking in account leap years) fixes the issue and the configuration applies successfully

**Comment by andrewsomething** [comment]
Thanks for flagging this issue for us! We should have a fix in place shortly.
