### ISSUE TITLE
Destroy certificates before destroying the domain of that certificate

### ISSUE THREAD

**Issue by jonathanvansina** [digitalocean/terraform-provider-digitalocean#470]
### Terraform Version
```bash
Terraform v0.12.29
+ provider.digitalocean v1.22.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_domain
- digitalocan_certificate
- (digitalocean_loadbalancer)

### Terraform Configuration Files
Main module (`terraform/main.tf`)
```hcl
resource "digitalocean_domain" "cloud" {
  name = var.domain_name
}
```
Submodule (`terraform/modules/application/main.tf`)
```hcl
resource "digitalocean_certificate" "openapi" {
  name    = "le-openapi-cert"
  type    = "lets_encrypt"
  domains = [var.lb-certificate-fqdn]

  lifecycle {
    create_before_destroy = true
  }
}

resource "digitalocean_loadbalancer" "openapi" {
  name                   = "openapi-${var.region}"
  region                 = var.region
  droplet_tag            = "openapi"
  redirect_http_to_https = true

  forwarding_rule {
    entry_port     = 443
    entry_protocol = "https"

    target_port     = 80
    target_protocol = "http"

    certificate_id = digitalocean_certificate.openapi.id
  }

  forwarding_rule {
    entry_port     = 80
    entry_protocol = "http"

    target_port     = 80
    target_protocol = "http"

    certificate_id = digitalocean_certificate.openapi.id
  }

  healthcheck {
    port     = 22
    protocol = "tcp"
  }
}
```

### Debug Output
```bash
Error: Error deleting Domain: DELETE https://api.digitalocean.com/v2/domains/example.com: 422 DNS domain is currently in use by a Let's Encrypt certificate, deleting this domain would prevent the Let's Encrypt certificate renewal
```

### Expected Behavior
The resource digitalocean_certificate should be destroyed before the digitalocean_domain.

### Actual Behavior
The resource digitalocean_domain is not destroyed because it has a hidden dependency by a digitalocean_certificate for that domain.

### Steps to Reproduce
1. Create a DigitalOcean **sub**module with a load balancer and certificate for that load balancer.
2. Create in the **main** module a domain name for the load balancer.
3. Run `terraform apply`
4. Run `terraform destroy`

### Important Factoids
My domain name is created in my main module (`terraform/main.tf`) and my certificate is created in a submodule (`terraform/modules/application/main.tf`). So I don't have the option to use the `depends_on` meta-argument.

**Comment by jonathanvansina** [comment]
Saw just that the same problem is happening when applying (`terraform apply`) the infrastructure (with the root- and submodules).
A temporary fix is to use the domain as a data source. Or just running `terraform destroy` or `terraform apply` twice.

**Comment by tdyas** [comment]
Terraform will infer a dependency when one resource has an attribute that references another resource. Thus, in your example, Terraform infers that `digitalocean_loadbalancer.openapi` depends on `digitalocean_certificate.openapi` because of the reference to `digitalocean_certificate.openapi.id` in the `forwarding_rule` clauses. However, note that `digitalocean_certificate.openapi' contains a reference to `var.lb-certificate-fqdn` and not to `digitalocean_domain.cloud`. 

So the question becomes, how is `lb-certificate-fqdn` being specified? Can you post the `module` clause that is bringing in the submodule into the main module?

**Comment by jonathanvansina** [comment]
Thanks for your answer @tdyas! Your response let me think further, and I found a solution for this issue. 

#### Before
First of all this is my `main.tf` in the **root module** where you asked for:

```tcl
[...]
# Data
resource "digitalocean_domain" "cloud" {
  name = var.domain_name
}
[...]
# Modules
module "application" {
  source = "./modules/application"

  lb-certificate-fqdn = "lb.${var.domain_name}"
}
```

#### After
By using the name attribute from my `digitalocean_domain.cloud` resource as a variable. Terraform discover the necessary dependency and will create the resources in the right order:

```hcl
[...]
# Data
resource "digitalocean_domain" "cloud" {
  name = var.domain_name
}
[...]
# Modules
module "application" {
  source = "./modules/application"

  lb-certificate-fqdn = "lb.${digitalocean_domain.cloud.name}"
}
}
```
...

We have two resources in the root module (`digitalocean_domain` and `digitalocean_ssh_key`), do you advice to never put resources in your root module and put all resources in submodules (even if the submodule only create one resource)? Thanks in advance.

**Comment by tdyas** [comment]
> We have two resources in the root module (digitalocean_domain and digitalocean_ssh_key), do you advice to never put resources in your root module and put all resources in submodules (even if the submodule only create one resource)? Thanks in advance.

Resources in the root module is fine. No need to make your config more complex than it needs to be.
