### ISSUE TITLE
In-place upgrade of to new PostgreSQL major version

### ISSUE THREAD

**Issue by ehamberg** [digitalocean/terraform-provider-digitalocean#471]
Currently, when changing the `version` of a `digitalocean_database_cluster` resource, terraform will try to replace the resource. It should instead do an in-place upgrade of the major version, as one can do through the control panel: https://www.digitalocean.com/docs/databases/postgresql/how-to/upgrade-version/

**Comment by drssdinblck** [comment]
Are there any plans for implementing this?
