### ISSUE TITLE
digitalocean_images data source missing created sort key

### ISSUE THREAD

**Issue by thecjharries** [digitalocean/terraform-provider-digitalocean#477]
I mistakenly reported this here first: https://github.com/hashicorp/terraform/issues/25859

### Terraform Version
```
Terraform v0.13.0
+ provider registry.terraform.io/terraform-providers/digitalocean v1.22.1
```

### Affected Resource(s)
`digitalocean_images` data source

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
[full file in gist](https://gist.github.com/thecjharries/a1e3dbef2e4957bb5f75799371d2ec46#file-test-tf)

### Debug Output
[full file in gist](https://gist.github.com/thecjharries/a1e3dbef2e4957bb5f75799371d2ec46#file-output-log)

### Expected Behavior
Per [the docs](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/data-sources/images), this should have returned a list of images sorted by `created`.

### Actual Behavior
* Without the sort, `created` is returned in the output
* With the sort, TF fails with this message
```
Error: expected sort.0.key to be one of [id name type distribution slug image private min_disk_size size_gigabytes status error_message], got created

  on test.tf line 20, in data "digitalocean_images" "available":
  20: data "digitalocean_images" "available" {
```

### Steps to Reproduce
```
export TF_VAR_do_pat=<some API token>
terraform init
terraform apply
```

### References
[`digitalocean_images` data source docs](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/data-sources/images)

**Comment by thecjharries** [comment]
I'll have a PR up for this in a few minutes

**Comment by bentranter** [comment]
Thanks for the detailed report and PR @thecjharries!
