### ISSUE TITLE
Add droplet monitoring resource

### ISSUE THREAD

**Issue by epicserve** [digitalocean/terraform-provider-digitalocean#479]
If possible, please add a resource for adding monitoring alerts.

**Comment by atombrella** [comment]
It doesn't seem like there are any API endpoints for this, which seems like a prerequisite. That was at least the impression I got from https://github.com/digitalocean/godo which is used in different parts of the code.

**Comment by atombrella** [comment]
I have an ongoing effort to implement this :tada: I hope to open a PR in September that's ready for review :100:

**Comment by atombrella** [comment]
@andrewsomething Can be closed :)

@epicserve It's available in 2.12 (https://github.com/digitalocean/terraform-provider-digitalocean/commit/cf4091dc31668ce817ab3a9870ee2d43f1cca627)
