### ISSUE TITLE
Add digitalocean_database_replica datasource

### ISSUE THREAD

**Issue by nathancolgate** [digitalocean/terraform-provider-digitalocean#489]
### Terraform Version

```
Terraform v0.12.29
+ provider.digitalocean v1.22.2
```

### Affected Resource(s)

- digitalocean_database_replica

### (Desired) Terraform Configuration Files

```hcl
data "digitalocean_database_replica" "read_only_db" {
  name = "project-read-only"
}
```

### Use Case

Our databases and replicas are created at a shared level, outside our project-specific terraform.

We are able to look up the database and get the attributes to use in our project-specific terraform.

But we can not grab the read-only replica host within the project.

I believe [the DigitalOcean API](https://developers.digitalocean.com/documentation/v2/#retrieve-an-existing-read-only-replica) already supports this.

**Comment by andrewsomething** [comment]
Closed via https://github.com/digitalocean/terraform-provider-digitalocean/pull/608
