### ISSUE TITLE
Nodes stuck in "Deleting" state

### ISSUE THREAD

**Issue by roddajohn** [digitalocean/terraform-provider-digitalocean#495]
Terraform Version: 0.12.29
Provider Version: 1.22.0

Affected Resources:
- `digitalocean_kubernetes_cluster`
- `digitalocean_kubernetes_node_pool`

### Terraform Configuration Files
```hcl
resource "digitalocean_kubernetes_cluster" "cluster" {                                                    
  name = var.cluster_name                                                                                 
  region = var.region                                                                                     
  version = data.digitalocean_kubernetes_versions.latest.latest_version                                   
  tags = ["talos-k8s-cluster"]                                                                            
                                                                                                          
  node_pool {                                                                                             
    name = "default"                                                                                      
    size = var.control_size                                                                               
    node_count = 1                                                                                        
    auto_scale = false                                                                                    
    tags = ["talos-k8s-cluster"]                                                                          
  }                                                                                                       
}  
```

### Debug Output
https://gist.github.com/roddajohn/b396656bc85feef060714c97eef47205

### Expected Behavior / Actual Behavior
I am expecting the number indicated by `actual_node_count` equal the number of active nodes, or `node_count`.  This has been in a state like this for > 1 month.  There are four nodes listed as "deleting" (the one active node also isn't listed?) and don't seem to every disappear.

### Steps to Reproduce
The above output is the result of an apply command where I was simply adding a tag to the node pool, but it pulls the state of the nodepool.

### Important Factoids
I previously edited the node pools manually before switching to terraform (been on it for over a year now and haven't experienced problems).

**Comment by scotchneat** [comment]
@roddajohn apologies for the delay in response. 
There were some odd settings in the configuration you shared (e.g. `auto_scale = false`, `node_count = 0`) that caught our eye. However, since the cluster has been deleted, we won't be able to troubleshoot this further.
If you continue to experience this issue, please let us know and we can escalate it accordingly.

**Comment by ChiefMateStarbuck** [comment]
running `terraform refresh` might help
