### ISSUE TITLE
Error creating Certificate 422

### ISSUE THREAD

**Issue by metanovii** [digitalocean/terraform-provider-digitalocean#496]
### Terraform Version
Terraform v0.12.26

### Affected Resource(s)
digitalocean_certificate

### Terraform Configuration Files
```hcl
provider "digitalocean" {
  version = "1.19.0"
  token   = var.do_token
}

provider "acme" {
  version    = "1.5.0"
  server_url = var.letsencrypt_api_endpoint
}

locals {
  acme_domain = join(".", ["${var.k8s_domain}", "${var.main_domain}"])
}

module "acme_certificate" {
  source  = "nephosolutions/certificate/acme"
  version = "2.0.0"

  dns_names = [
    "${local.acme_domain}",
    "*.${local.acme_domain}"
  ]

  email_address = var.cloudflare_email

  dns_challenge = {
    provider = "cloudflare"

    config = {
      CF_ZONE_API_TOKEN = var.cloudflare_api_token_read
      CF_DNS_API_TOKEN  = var.cloudflare_api_token
      CF_API_EMAIL      = var.cloudflare_email
    }
  }

}

resource "digitalocean_certificate" "cert-lb" {
  name              = "certificate-qa-${random_id.uniq_id.hex}"
  type              = "custom"
  private_key       = module.acme_certificate.private_key
  leaf_certificate  = module.acme_certificate.certificate
  certificate_chain = module.acme_certificate.fullchain

  lifecycle {
    create_before_destroy = true
  }

}

```

### Debug Output
i have not debug

### stdout message
Error: Error creating Certificate: POST https://api.digitalocean.com/v2/certificates: 422 (request "4369c6be-ea66-45f0-bb9f-52e6df4c70c3") name is not unique

The error occurs only after the certificate is updated. If the certificate is new, there is no error.

**Comment by kopylash** [comment]
@metanovii have you solved the problem?

I have similar issue. Terraform state contains old certificate id, while in digital ocean it shows another cert.
<img width="703" alt="Screenshot 2020-10-17 at 16 24 10" src="https://user-images.githubusercontent.com/9396184/96338287-915e9b00-1095-11eb-821f-cf9f3117490c.png">
<img width="557" alt="Screenshot 2020-10-17 at 16 25 29" src="https://user-images.githubusercontent.com/9396184/96338289-94598b80-1095-11eb-83ad-781f1843f2e6.png">

**Comment by kopylash** [comment]
So, I found the issue by checking docs. Terraform will do refresh to detect configuration drift. DO manages letsencrypt certificates on it's own, so at some point Terraform will detect that `certificate_id` does not match the one stored in state.

I declared certificate resource as following: (noticed `create_before_destroy`?)
```terraform
resource "digitalocean_certificate" "cert" {
  name    = "${local.name_prefix}-lets-encrypt}"
  type    = "lets_encrypt"
  domains = [data.digitalocean_domain.default.name]

  lifecycle {
    create_before_destroy = true
  }
}
```

In docs it is said that there cannot be 2 certificates with the same name.
<img width="707" alt="Screenshot 2020-10-17 at 16 48 07" src="https://user-images.githubusercontent.com/9396184/96338833-4fcfef00-1099-11eb-96b8-261af8395a21.png">


So you need the name to be computed with some random part, e.g.
```
  name    = "${local.name_prefix}-lets-encrypt-${uuid()}"
```
