### ISSUE TITLE
Providing ENV var based credentials does not work

### ISSUE THREAD

**Issue by martinisoft** [digitalocean/terraform-provider-digitalocean#498]
### Terraform Version
Terraform v0.13.4
+ provider registry.terraform.io/digitalocean/digitalocean v1.22.2
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.2

### Affected Resource(s)
- provider "digitalocean"

### Terraform Configuration Files
```hcl
# DigitalOcean API Token. This can also be set via 
# DIGITALOCEAN_ACCESS_TOKEN and DIGITALOCEAN_TOKEN environment vars
variable "do_token" {}

provider "digitalocean" {
    token = var.do_token
}
```

### Debug Output
https://gist.github.com/martinisoft/0c35bdf8af763ac8e62a7ec0ad79d111

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
I should not be prompted for a token, but I am still prompted for one anyway.

### Actual Behavior
I am prompted for a token and it still tries to perform a plan, but it ultimately fails because of a lack of authentication credentials. This is the error output:
```
$ terraform plan
var.do_token
  Enter a value:

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.digitalocean_kubernetes_versions.stable: Refreshing state... [id=terraform-20201006204952647200000001]

Error: Error retrieving Kubernetes options: GET https://api.digitalocean.com/v2/kubernetes/options: 401 Unable to authenticate you

  on main.tf line 13, in data "digitalocean_kubernetes_versions" "stable":
  13: data "digitalocean_kubernetes_versions" "stable" {
```

### Steps to Reproduce
1. `export DIGITALOCEAN_ACCESS_TOKEN=<token>`
1. `terraform plan`

### Important Factoids
Simply following the latest digitalocean provider docs to run into this issue. However, if I export `TF_VAR_do_token` with my API key, terraform plan works as expected since `TF_VAR` is a special environment variable prefix.

### References
None

**Comment by andrewsomething** [comment]
Hi @martinisoft,

By specifying the token in the config as a variable, you are overriding the environment variable:

```
provider "digitalocean" {
    token = var.do_token
}
```

If you are setting it in the environment, you can just use:

```
provider "digitalocean" {
}
```

**Comment by martinisoft** [comment]
Oh interesting, that is not clear in the documentation. Would there be a way to allow for both? Think I saw some tricks with coalesce in there, but I guess it's tricky to do.

**Comment by Zelgius** [comment]
This is supported by Terraform. Name your environment variable TF_VAR_name_of_your_terraform_variable and it will be picked up automatically.

**Comment by martinisoft** [comment]
> This is supported by Terraform. Name your environment variable TF_VAR_name_of_your_terraform_variable and it will be picked up automatically.

This is what I ultimately ended up doing, but the provider docs confused me. The "Alternatively" bit wasn't clear enough to me that if I leave out the token option entirely it would just use those env vars, but then I'd lose out on variables in TF. Go figure.

**Comment by martinisoft** [comment]
Thanks again for the help folks. I guess I'll close this now in case people end up searching this in the future.
