### ISSUE TITLE
Documentation link is broken for digitalOcean provider (404)

### ISSUE THREAD

**Issue by abh23** [digitalocean/terraform-provider-digitalocean#499]
Hello there, 

I am unable to see documentation for digitalocean provider on terraform's website. 

URL: `https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs`

Please check and update the link.

**Comment by andrewsomething** [comment]
Thanks for reporting this. This seems to be an issue with the Terraform registry website.

If you go to: https://registry.terraform.io/providers/digitalocean/digitalocean
It redirects to: https://registry.terraform.io/providers/digitalocean/digitalocean/latest

But if you go directly to that page, you get the 404 error. If you go through the first page, it works. From there, if you click on the "documentation" link, it goes to: https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs

Again that works, but if you try to go directly to the page it 404s.

**Comment by andrewsomething** [comment]
Looks like this is affecting other providers as well:

https://discuss.hashicorp.com/t/link-to-kubernetes-provider-docs-broken/15513
https://discuss.hashicorp.com/t/aws-provider-docs-are-showing-page-not-found/15516

**Comment by abh23** [comment]
You are right @andrewsomething. 
Is there a way it can be conveyed to terraform registry maintainers?

**Comment by andrewsomething** [comment]
I've reached out to the team at HashiCorp to flag this for them.

**Comment by andrewsomething** [comment]
It seems to be working now if you do a hard reload or open in an incognito window. I'm going to go ahead and close this, but follow up with HashiCorp as well.

**Comment by abh23** [comment]
Hi. Issue persists. I just tried. Seems like the changes weren't propagated to CDNs?

**Comment by aicarmic** [comment]
Tony here from HashiCorp. Thanks for the reports, confirming we had a short outage on 10/13/2020 from 7-8am PT, however this should be resolved and you should no longer be seeing 404s.
