### ISSUE TITLE
Terraform cloud crashes on plan (same configuration worked few weeks ago)

### ISSUE THREAD

**Issue by liarco** [digitalocean/terraform-provider-digitalocean#505]
### Versions
Terraform: `v0.13.5`
DigitalOcean provider: `v2.0.0`

### Affected Resource(s)
The issue doesn't seem to be related to any specific resource.

### Terraform Configuration Files & Debug Output
Complete gist: https://gist.github.com/liarco/99f3c59ebc0c3996986b2c654b2b5f09

I'm using Terraform Cloud with remote execution and I can't find a way to get `crash.log`.

I'm sorry that I can't provide more information, but please let me know if there's anything I can do to help you understanding the issue.

**Comment by andrewsomething** [comment]
Thank you for flagging this issue @liarco. We've just releases v2.0.1 that should resolve it.

    terraform init -upgrade

Apologizes for the disruption.

**Comment by tdyas** [comment]
I missed that change in semantic of `diag.FromErr` in doing the upgrade. :( I've sent a PR to change the SDK to handle nil errors passed to that method. https://github.com/hashicorp/terraform-plugin-sdk/pull/623
