### ISSUE TITLE
Document database support for Apps

### ISSUE THREAD

**Issue by poiati** [digitalocean/terraform-provider-digitalocean#507]
It looks like currently, we can't add a development database to an App. My assumption is based here: https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/app. I can't find any reference to how to do that.

### Terraform Version
Terraform v0.12.20

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_app

**Comment by andrewsomething** [comment]
Looks like we forgot to include the database bits in the documentation! You can see the schema here:

https://github.com/digitalocean/terraform-provider-digitalocean/blob/master/digitalocean/app_spec.go#L334

A basic example would be:

```hcl
resource "digitalocean_app" "foobar" {
  spec {
    name = "foobar"
    region = "nyc"
    service {
      name               = "go-service"
      environment_slug   = "go"
      instance_size_slug = "basic-xxs"
      git {
        repo_clone_url = "https://github.com/digitalocean/sample-golang.git"
        branch         = "main"
      }
    }
    database {
      name         = "test-db"
      engine       = "PG"
      production = false
    }
  }
}
```
