### ISSUE TITLE
remote-exec provisioner fails with: "Failed to upload script: lease wait while we get your droplet ready..."

### ISSUE THREAD

**Issue by alor** [digitalocean/terraform-provider-digitalocean#508]
### Terraform Version
Terraform v0.13.4
+ provider registry.terraform.io/digitalocean/digitalocean v2.0.1

### Affected Resource(s)
remote-exec provisioner for droplets 

### Expected Behavior
the remote-exec script is uploaded and executed after droplet creation

### Actual Behavior
it fails with this error: 
"Failed to upload script: lease wait while we get your droplet ready..."

the same error is displayed if I try with a "file provisioner"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. configure a new droplet with a remote-exec provisioner action or a file provisioner
2. terraform apply
3. wait the droplet creation
4. as soon as the droplet is created the error is displayed

### Important Factoids
I think it's a timing problem of something changed by digital ocean. it never happened before and if I insert a local-exec provisioner that does nothing by wait for 30 seconds (a shell script with sleep 30), then the remote-exec is successful.

maybe the droplet is not yet ready for ssh when terraform consider it good to go.

**Comment by andrewsomething** [comment]
Thanks for the report. Can you share an example configuration that is running into this problem?

This basic example is working as expected for me. 

```
resource "digitalocean_droplet" "foo" {
  image = "ubuntu-20-04-x64"
  name = "foo"
  region = "nyc2"
  size = "s-1vcpu-1gb"
  ssh_keys = [12345]

  connection {
    host = self.ipv4_address
    user = "root"
    type = "ssh"
  }

  provisioner "remote-exec" {
    inline = ["touch /root/test"]
  }
}
```

**Comment by alor** [comment]
Here it is:

```
resource "digitalocean_droplet" "bar" {
  count = var.bar_count
  image = "docker-18-04"
  name = "bar-${count.index + 1}"
  size = "s-4vcpu-8gb"
  monitoring = true
  tags = ["BAR"]
  private_networking = true
  ipv6 = true
  # cloud config
  user_data = templatefile("${path.root}/cloud-config.yaml", { public_key = file(var.pub_key_file) })
  ssh_keys = [var.ssh_fingerprint]

  connection {
    host = self.ipv4_address
    user = "root"
    type = "ssh"
    private_key = file(var.pvt_key_file)
    timeout = "2m"
  }

  // this fixes the issue
//  provisioner "local-exec" {
//    command = "sleep 30'"
//  }

  provisioner "remote-exec" {
    inline = [
      # remove rules for docker daemon
      "sudo ufw delete allow 2375/tcp",
      "sudo ufw delete allow 2376/tcp",
    ]
  }

  provisioner "file" {
    source      = "${path.root}/ssh_key.pub"
    destination = "/home/bar/.ssh/authorized_keys"
  }
}
```

**Comment by andrewsomething** [comment]
This seems to be due to a change in the Docker 1-Click image. I've raised the problem with our Marketplace team for further investigation.

**Comment by andrewsomething** [comment]
@alor An updated Docker 1-Click image should now be available fixing this issue. Let us know if you're still running into any problems.

**Comment by alor** [comment]
thanks!
