### ISSUE TITLE
Ability to list all SSH Keys

### ISSUE THREAD

**Issue by stack72** [digitalocean/terraform-provider-digitalocean#518]
Hey @andrewsomething 

WE've had a request in the Pulumi provider to add the ability to list all SSH Keys. When I started looking at this, I thought we can go 1 of 2 ways:

1. Create a new datasource for this
2. Change the current ssh key datasource to not require a name and return a list of ssh keys

My tendency is towards #1 but I wanted to check with you before I carry out the work and send a PR

Thoughts?

Paul

**Comment by andrewsomething** [comment]
:+1:  #1 is definitely the way to go here. We have a number of data source where we provide both a single and list version (e.g. `digitalocean_droplet` and `digitalocean_droplets`). Actually a bit surprised we haven't gotten around to SSH keys yet.

Take a look at one of the existing list-type data sources. We have an internal library to handle them in a standard way: 

https://github.com/digitalocean/terraform-provider-digitalocean/tree/master/internal/datalist

Thanks for taking this on!

**Comment by stack72** [comment]
Thanks - wanted to make it consistent and thus needed to check! PR will come in today
