### ISSUE TITLE
Creating k8s cluster ends with SLUG error

### ISSUE THREAD

**Issue by tomaszmichalak** [digitalocean/terraform-provider-digitalocean#521]
Hi,
I try to create my k8s cluster with resource:
```
resource "digitalocean_kubernetes_cluster" "kubernetes_cluster" {
  name    = "xxx"
  region  = "fra1"
  version = "1.19.3-do.0"

  tags = ["staging"]

  node_pool {
    name       = "tr-staging-pool"
    size       = "s-1vcpu-2gb"
    auto_scale = false
    node_count = 1
  }
}
```
When running `terraform apply` we get an error:
```
digitalocean_container_registry.container_registry: Creating...
digitalocean_kubernetes_cluster.kubernetes_cluster: Creating...
digitalocean_container_registry.container_registry: Still creating... [10s elapsed]
digitalocean_container_registry.container_registry: Creation complete after 13s [id=technology-radar-registry]
digitalocean_container_registry_docker_credentials.registry_docker_credentials: Creating...
digitalocean_container_registry_docker_credentials.registry_docker_credentials: Creation complete after 1s [id=technology-radar-registry]

Error: Error creating Kubernetes cluster: POST https://api.digitalocean.com/v2/kubernetes/clusters: 422 validation error: invalid version slug
```

### Terraform Version
```
Terraform v0.13.5
+ provider registry.terraform.io/digitalocean/digitalocean v2.1.0
+ provider registry.terraform.io/gavinbunney/kubectl v1.9.1
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
```

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_kubernetes_cluster

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```
resource "digitalocean_kubernetes_cluster" "kubernetes_cluster" {
  name    = "xxx"
  region  = "fra1"
  version = "1.19.3-do.0"

  tags = ["staging"]

  node_pool {
    name       = "tr-staging-pool"
    size       = "s-1vcpu-2gb"
    auto_scale = false
    node_count = 1
  }
}
```

### Expected Behavior
No error.

### Actual Behavior
Error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/digitalocean/terraform-provider-digitalocean/pull/516

**Comment by andrewsomething** [comment]
The error is because `1.19.3-do.0` is not an available version. The current version that are available for creating new clusters are:

```
$ doctl kubernetes options versions 
Slug            Kubernetes Version
1.19.3-do.2     1.19.3
1.18.10-do.2    1.18.10
1.17.13-do.2    1.17.13
```

You can also find these via Terraform:

```
data "digitalocean_kubernetes_versions" "example" {}

output "k8s-versions" {
  value = data.digitalocean_kubernetes_versions.example.valid_versions
}
```

https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/data-sources/kubernetes_versions

You can also specify a version prefix allowing you to pin to a specific minor version, e.g.:

```
data "digitalocean_kubernetes_versions" "example" {
  version_prefix = "1.19"
}

resource "digitalocean_kubernetes_cluster" "example-cluster" {
  name    = "example-cluster"
  region  = "lon1"
  version = data.digitalocean_kubernetes_versions.example.latest_version

  # other cluster details
}
```

**Comment by tomaszmichalak** [comment]
Thanks for the help. It works as expected.
