### ISSUE TITLE
resource "digitalocean_container_registry" doesn't work v0.13.5

### ISSUE THREAD

**Issue by j-737casa** [digitalocean/terraform-provider-digitalocean#522]
Hi there,

### Terraform Version
Terraform v0.13.5

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_container_registry

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    digitalocean = {
      source = "digitalocean/digitalocean"
      version = "~> 2.1.0"
    }
  }
}

provider "digitalocean" {
  token = var.token
}

resource "digitalocean_container_registry" "registry" {
  name = "fe"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: 
https://gist.github.com/j-737casa/d2755abaafb4f52c8a1406674c75bbb1

### Expected Behavior
Terraform plan success

### Actual Behavior
Fails Terraform plan

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init && terraform plan`

**Comment by j-737casa** [comment]
when i add the missing field it works. you need to update the docs
![image](https://user-images.githubusercontent.com/74134982/98746379-4b070e00-23ad-11eb-9816-0e83869b452c.png)

**Comment by andrewsomething** [comment]
Thanks for flagging this for us. We'll get the docs updated.
