### ISSUE TITLE
custom_image documentation unclear

### ISSUE THREAD

**Issue by pacocc** [digitalocean/terraform-provider-digitalocean#526]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- opc_storage_volume

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by pacocc** [comment]
The documentation at ($URL) does not specify the conditions necessary for "resource "digitalocean_custom_image""s.
It appears to be referring to a Docker image where a Linux ISO should work.  For example, if an http/s iso URL is specified the error is:

  The provider provider.digitalocean does not support resource type
  "digitalocean_custom_image".

Objective is to instantiate a Duvean droplet as there are no Duvean images available at api.digitalocean.com/v2/images.

URL: https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/custom_image
Terraform Version: v0.13.5

**Comment by andrewsomething** [comment]
Thanks for opening this issue. I think there are definitely some improvements to be made there. 

ISOs are not currently supported by this feture. Images must be in one of the following file formats:

- Raw (.img) with an MBR or GPT partition table
- qcow2
- VHDX
- VDI
- VMDK

This main docs for DigitalOcean custom images can be found here: https://www.digitalocean.com/docs/images/custom-images/

**Comment by andrewsomething** [comment]
We should also include an example of creating a Droplet with the image:

```
resource "digitalocean_custom_image" "focal" {
  name         = "ubuntu-20.04-minimal-cloudimg-amd64"
  distribution = "Ubuntu"
  description  = "testing..."
  url          = "https://cloud-images.ubuntu.com/minimal/releases/focal/release/ubuntu-20.04-minimal-cloudimg-amd64.img"
  regions      = ["nyc3"]
}

resource "digitalocean_droplet" "example" {
  image     = digitalocean_custom_image.focal.id
  name      = "example-1"
  region    = "nyc3"
  size      = "s-1vcpu-1gb"
  user_data = "my script here..."
  ssh_keys  = [107149]
}
```
