### ISSUE TITLE
Achieving one VPC per droplet should be simpler

### ISSUE THREAD

**Issue by obilodeau** [digitalocean/terraform-provider-digitalocean#531]
# Update

Due to a [default behavior change](https://developers.digitalocean.com/documentation/changelog/api-v2/vpc-new-droplets/) starting October 1st 2020, all created droplets now belong to your region's default VPC. Using `private_networking = false` has been deprecated.

It is possible to create a VPC per droplet but it is complicated. See this workaround: https://github.com/digitalocean/terraform-provider-digitalocean/issues/531#issuecomment-734408200

I'm keeping this issue open to document a request that it should be simpler to do so. My use case is security. Many people create many droplets for different purposes in our organization (including shared shell access) and the ability to nmap/SSH scan the LAN to discover other droplets is undesired.

# Initial Bug Report

### Terraform Version

```
$ terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/digitalocean/digitalocean v2.1.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/nbering/ansible v1.0.4
```

### Affected Resource(s)

- droplet
- vpc (I guess)

### Terraform Configuration Files
```hcl
resource "digitalocean_droplet" "some-server" {
  image    = "ubuntu-18-04-x64"
  name     = "some-server"
  region   = "tor1"
  ipv6     = true
  private_networking = false
  size     = "s-1vcpu-1gb"
  resize_disk = false
  ssh_keys = [data.digitalocean_ssh_key.server.fingerprint]

  connection {
    host = self.ipv4_address
    user = "root"
    type = "ssh"
    agent = true
    timeout = "2m"
  }

  # Wait until instance responds to SSH before triggering next actions
  provisioner "remote-exec" {
    inline = [
      "until [ -f /var/lib/cloud/instance/boot-finished ]; do sleep 1; done",
    ]
  }
}
```

### Debug Output

I don't think it is required at this time.

### Panic Output

N/A

### Expected Behavior
What should have happened?

Droplet should be created with private_networking turned off.

### Actual Behavior
What actually happened?

The droplet was created with private networking turned on, in the default VPC of the region:

```
$ terraform show
[...]

# digitalocean_droplet.some-server:
resource "digitalocean_droplet" "some-server" {
    backups              = false
    created_at           = "2020-11-25T06:10:53Z"
    disk                 = 25
    id                   = "21[..]78"
    image                = "ubuntu-18-04-x64"
    ipv4_address         = "138.X.Y.2"
    ipv4_address_private = "10.X.Z.75"
    ipv6                 = true
    ipv6_address         = "2604:X:Y:Z:3001"
    locked               = false
    memory               = 1024
    monitoring           = false
    name                 = "some-server"
    price_hourly         = 0.00744
    price_monthly        = 5
    private_networking   = true
    region               = "tor1"
    resize_disk          = false
    size                 = "s-1vcpu-1gb"
    ssh_keys             = [
        "...",
    ]
    status               = "active"
    urn                  = "do:droplet:<someid>"
    vcpus                = 1
    volume_ids           = []
    vpc_uuid             = "<some uuid>"
}

[...]
```

### Steps to Reproduce

1. define a droplet with `private_networking` set to false
2. `terraform apply`
3. `terraform show`

You will see right away that the droplet will have private_networking turned on. The fact that it can't be removed makes the issue even more annoying.

For security purposes, I don't want some of the machines I create to accidentally have VPC access to others (created even by other departments). As a workaround, I will probably create VPCs dynamically and allocate them to my droplets. Relying on `private_networking = false` would be better.

**Comment by lfarnell** [comment]
@obilodeau Based on the [docs](https://developers.digitalocean.com/documentation/v2/#create-a-new-droplet) the parameter you are using is deprecated.
```
private_networking | Boolean | This parameter has been deprecated. Use 'vpc_uuid' instead to specify a VPC network for the Droplet. If no `vpc_uuid` is provided, the Droplet will be placed in the default VPC.
```
Not 100% certain but this would seem as though you **can not** disable private networking with VPC's

**Comment by obilodeau** [comment]
Great find. Thanks @lfarnell.

[Looking here](https://developers.digitalocean.com/documentation/v2/#vpcs) I think I'll create a non-default VPC with an undefined `ip_range` and associate it with my droplet. A bit unfortunate that it has to be this complex to avoid putting every server in the same virtual DMZ.

**Comment by obilodeau** [comment]
Ok, below is what is required to get a VPC per droplet since the [October 1st change](https://developers.digitalocean.com/documentation/changelog/api-v2/vpc-new-droplets/). It relies on the [random provider](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/pet) so you might need to do a `terraform init`.

Note that the VPC is managed by terraform here and will be removed on a destroy action. Also, it is not tied to a specific characteristic of the droplet like you can do with a [random provider resource keeper](https://registry.terraform.io/providers/hashicorp/random/latest/docs#resource-keepers). Lastly, the VPC and the droplet must be in the same region. This could be extracted out in a variable.

```terraform
resource "digitalocean_droplet" "some-server" {
  image    = "ubuntu-18-04-x64"
  name     = "some-server"
  region   = "tor1"
  ipv6     = true
  # private_networking is deprecated, we need to generate a unique VPC per server
  #private_networking = false
  vpc_uuid = digitalocean_vpc.server.id
  size     = "s-1vcpu-1gb"
  resize_disk = false
  ssh_keys = [data.digitalocean_ssh_key.server.fingerprint]

  connection {
    host = self.ipv4_address
    user = "root"
    type = "ssh"
    agent = true
    timeout = "2m"
  }

  # Wait until instance responds to SSH before triggering next actions
  provisioner "remote-exec" {
    inline = [
      "until [ -f /var/lib/cloud/instance/boot-finished ]; do sleep 1; done",
    ]
  }
}

# This section handles creating a random vpc per droplet instance
resource "random_pet" "vpc_name" {}

resource "digitalocean_vpc" "server" {
  name   = "isolated-vpc-${random_pet.vpc_name.id}"
  region = "tor1"
}
```

**Comment by tdyas** [comment]
Suggestion: Create [a Terraform module](https://www.terraform.io/docs/modules/index.html) with both a `digitalocean_vpc` resource and a `digitalocean_droplet` resource. Then instantiate the module any time you need a droplet with its own VPC.

**Comment by scotchneat** [comment]
Looking back on this issue, I see @obilodeau, you found a possible solution, and @tdyas made a good suggestion as well. 
I'm closing this issue now but if you feel this needs more discussion, please don't hesitate to reopen it.
