### ISSUE TITLE
Apply acl public-read on spaces bucket does not have effect, the bucket is still private

### ISSUE THREAD

**Issue by nlitterat** [digitalocean/terraform-provider-digitalocean#536]
### Terraform Version 
0.14.0

### Affected Resource(s) 
- digitalocean_spaces_bucket

### Terraform Configuration Files
```hcl
resource "digitalocean_spaces_bucket" "xxxx" {
  name   = "xxx"
  region = "nyc3"
  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["GET"]
    allowed_origins = ["*"]
    max_age_seconds = 3000
  }
  acl = "public-read"

}
```

### Debug Output
Terraform is applied successfully 

### Panic Output
Terraform is applied successfully 

### Expected Behavior
The bucket is created with public read access

### Actual Behavior
The bucket is restricted only to users with access key and token

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
None

### References
None that I found

**Comment by andrewsomething** [comment]
Setting `public-read` for a bucket only effects the bucket-level permission, i.e. listing objects in the bucket. It does not grant access to any individual object. Those permission must be set on the object itself.

If I create a bucket like:

```
resource "digitalocean_spaces_bucket" "a982e9c8-3a31-11eb-bc68-a741f2231c05" {
  name   = "a982e9c8-3a31-11eb-bc68-a741f2231c05"
  region = "nyc3"
  acl = "public-read"
}
```

I can successfully access the bucket unauthenticated:

```
$ curl -I https://a982e9c8-3a31-11eb-bc68-a741f2231c05.nyc3.digitaloceanspaces.com/
HTTP/1.1 200 OK
X-RGW-Object-Count: 0
X-RGW-Bytes-Used: 0
x-amz-request-id: tx000000000000000206868-005fd0f07e-2a11b61-nyc3c
Content-Length: 0
Date: Wed, 09 Dec 2020 15:42:54 GMT
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
```

Removing the `public-read` and applying the changes:

```
resource "digitalocean_spaces_bucket" "a982e9c8-3a31-11eb-bc68-a741f2231c05" {
  name   = "a982e9c8-3a31-11eb-bc68-a741f2231c05"
  region = "nyc3"
}
```

I can no longer access it:

```
$ curl -I https://a982e9c8-3a31-11eb-bc68-a741f2231c05.nyc3.digitaloceanspaces.com/
HTTP/1.1 403 Forbidden
Content-Length: 250
x-amz-request-id: tx000000000000000212e35-005fd0f0d0-2a11d50-nyc3c
Accept-Ranges: bytes
Content-Type: application/xml
Date: Wed, 09 Dec 2020 15:44:16 GMT
Strict-Transport-Security: max-age=15552000; includeSubDomains; preloa
```

**Comment by nlitterat** [comment]
Hi Sorry for late response 
I will look into it and try to understand why your code is working and why is not 
Thanks for your time

**Comment by andrewsomething** [comment]
Thanks for the follow up. Please feel free to reopen if you have additional information.
