### ISSUE TITLE
Add support for full domain object as per the App Specification

### ISSUE THREAD

**Issue by acraven** [digitalocean/terraform-provider-digitalocean#542]
### Affected Resource
`digitalocean_app`

### Expected Behavior
The `domains` attribute of `digitalocean_app` should support a list of `domain`, `type`, `wildcard` and `zone` attributes as per the [App Specification](https://www.digitalocean.com/docs/app-platform/references/app-specification-reference/).

### Actual Behavior
The `domains` attribute of `digitalocean_app` is currently a list of strings.

### Other
I'm currently unable to use this provider as I need to set the `zone` of my domain.

**Comment by andrewsomething** [comment]
Closed via https://github.com/digitalocean/terraform-provider-digitalocean/issues/572
