### ISSUE TITLE
Add support for images attribute as per the App Specification

### ISSUE THREAD

**Issue by acraven** [digitalocean/terraform-provider-digitalocean#543]
### Affected Resource
`digitalocean_app`

### Expected Behavior
The `image` attribute of `service`, `static_site` and `worker` objects of `digitalocean_app` should support an object with `registry_type`, `registry`, `repository` and `tag` attributes as per the [App Specification](https://www.digitalocean.com/docs/app-platform/references/app-specification-reference/).

### Actual Behavior
The `image` attribute of `service`, `static_site` and `worker` objects of `digitalocean_app` is currently missing.

### Important Factoids
For some reason `static_site` doesn't have an `image` attribute in the App Specification. I'm not sure where the lack of support is as `job` does, but doesn't work for me. I can work around it by specifying the image I want to deploy as the base image in an otherwise empty Dockerfile and deploying that. It's not ideal as I have to them have a repo with just that in it.

### Other
I'm currently unable to use this provider as I use the `image` attribute as opposed to the `git` or `github` attributes.

**Comment by andrewsomething** [comment]
Closed via https://github.com/digitalocean/terraform-provider-digitalocean/pull/565
