### ISSUE TITLE
Add support for job components

### ISSUE THREAD

**Issue by acraven** [digitalocean/terraform-provider-digitalocean#545]
### Affected Resource
`digitalocean_app`

### Expected Behavior
The `digitalocean_app` resource should support Job components as per the [App Specification](https://www.digitalocean.com/docs/app-platform/references/app-specification-reference/).

### Actual Behavior
The ability to specify `job` attributes in `digitalocean_app` is currently missing.

### Other
I'm currently unable to use this provider as I use Job components.

**Comment by andrewsomething** [comment]
Closed via https://github.com/digitalocean/terraform-provider-digitalocean/pull/566
