### ISSUE TITLE
Apps: 400 Account does not have access to the repo

### ISSUE THREAD

**Issue by pjhampton** [digitalocean/terraform-provider-digitalocean#547]
### Terraform Version
Terraform v0.12.21

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_app

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl

resource "digitalocean_app" "www-app" {
  spec {
    name        = "www-app"
    region      = "nyc"

    service {
      name               = "www-app"
      dockerfile_path    = "Dockerfile"
      http_port          = 80
      instance_count     = 1
      instance_size_slug = "professional-xs"

      git {
        repo_clone_url = "https://github.com/pjhampton/app.git"
        branch         = "master"
      }
    }

  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Digital Ocean has been granted access to the private repo via the UI

### Actual Behavior
```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

digitalocean_app.www-app: Creating...

Error: Error creating App: POST https://api.digitalocean.com/v2/apps: 400 Account does not have access to the repo
```

### Steps to Reproduce
Try to deploy an app from a private repo that has been granted access via the UI

### Important Factoids
n/a

### References
n/a

**Comment by andrewsomething** [comment]
Hi @pjhampton,

Is `https://github.com/pjhampton/app.git` a private repository? If so, you'll need to use the [`github` attribute](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/app#github) instead of `git`. You will also need to allow DigitalOcean App Platform access to the repository by following: https://cloud.digitalocean.com/apps/github/install

**Comment by pjhampton** [comment]
That's perfect, thanks as always @andrewsomething.

2 pieces of well-intentioned feedback: 
  - From the docs that was not clear - an example might be useful.
  - The username/repo format is case sensitive, but typically that is not the case in git world. I've also got away with not caring too much about casing before in TF world too.
