### ISSUE TITLE
API error when creating multiple VPCs at the same time without an ip_range

### ISSUE THREAD

**Issue by obilodeau** [digitalocean/terraform-provider-digitalocean#551]
### Terraform Version

```
$ terraform -v
Terraform v0.14.4
+ provider registry.terraform.io/digitalocean/digitalocean v2.1.0
+ provider registry.terraform.io/hashicorp/aws v3.22.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/time v0.6.0
+ provider registry.terraform.io/nbering/ansible v1.0.4
```

### Affected Resource(s)
- digitalocean_vpc

### Terraform Configuration Files
```hcl
# Creates a unique VPC for this service for increased isolation
resource "random_pet" "service1_vpc_name" {}
resource "digitalocean_vpc" "service1" {
  name   = "product-vpc-${random_pet.service1_vpc_name.id}"
  region = "tor1"
}

# Creates a unique VPC for this service for increased isolation
resource "random_pet" "service2_vpc_name" {}
resource "digitalocean_vpc" "service2" {
  name   = "product-vpc-${random_pet.service2_vpc_name.id}"
  region = "tor1"
}
```

### Debug Output
https://gist.github.com/obilodeau/bff8e06317c87362c1eb8bc4b6e7f6a4

### Expected Behavior

* Two VPCs with different IP ranges are created at the same time

### Actual Behavior

* Two requests to create VPCs without an `ip_range` are issued at the same time
* One request completes successfully with allocated range `10.118.80.0/20`
* The other request fails with:
```
{
    "id": "unprocessable_entity",
    "message": "This range/size overlaps with another VPC network in your account: product-vpc-wise-emu 10.118.80.0/20.",
    "request_id": "10b4eb0b-21a9-4a9c-a316-c1c0d4b5c7aa"
}
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* A workaround is to introduce a `time_sleep` between the creation of the two VPCs. The `time_sleep` has a `depend_on` the creation of the first VPC and the second VPC has a `depend_on` the `time_sleep`.
* We opened a support ticket to digital ocean about this (#4323973). Ticket was closed saying to report here instead.
* We feel that the problem is not in this provider but in the way the DO API handles the requests concurrently with regards randomly picking the `ip_range`. That said, introducing a small delay in this provider could be a satisfactory fix.

**Comment by andrewsomething** [comment]
Thanks for flagging this issue. We've raised it internally with our VPC team for further investigation. If needed, we can work around it here in the provider but it does seem as if this would effect users creating VPCs in parallel using other tools as well.

Another temporary work around for anyone hitting this would be to disable parallelism. Eg.

    terraform apply -parallelism=1

**Comment by obilodeau** [comment]
Amazing support guys! Fix works in production. Thanks!

**Comment by andrewsomething** [comment]
Glad to hear it's working!
