### ISSUE TITLE
digitalocean_kubernetes_cluster change node_pool size fails with mysterious error

### ISSUE THREAD

**Issue by danryu** [digitalocean/terraform-provider-digitalocean#558]
### Terraform Version
Terraform v0.14.4

### Terraform Configuration Files
```hcl
resource "digitalocean_kubernetes_cluster" "service_live" {
  name    = "service-live"
  region  = "fra1"
  # Grab the latest version slug from `doctl kubernetes options versions`
  version = "1.19.3-do.0"
  tags    = ["production", "live"]

  node_pool {
    name       = "worker-pool-live"
    size       = "s-1vcpu-2gb"   # change to eg "s-2vcpu-4gb" and attempt 'terraform plan'
    node_count = 2
    auto_scale = true
    min_nodes  = 2
    max_nodes  = 5
  }
}
```

### Debug Output
https://gist.github.com/danryu/4618225877559c66d3ec13f07604b3da

### Expected Behavior
When I change 
`    size       = "s-1vcpu-2gb"`
to
`    size       = "s-2vcpu-4gb"`

in the above resource description, I expect 'terraform plan' to complete successfully or to fail with some meaningful error.

### Actual Behavior
terraform crashes with some strange error about secrets
`Error: an error on the server ("This URL is only used when you have built the production\n                version of the app. Visit http://localhost:3000/ instead, or\n                run `yarn run build` to test the production version.") has prevented the request from succeeding (get secrets docker-cfg)
`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create cluster with above code
2. Update cluster node_pool size to any other size
3. `terraform plan`

### Important Factoids
I did have live deployments on the cluster when attempting this. It may not be sensible to attempt node size change with live deployments anyway. But in any case I would like to get some more meaningful output back from the DO provider.

**Comment by andrewsomething** [comment]
Hi @danryu, DigitalOcean does not support changing the instance size used for an existing node pool. You can add or remove node to the pool or add a new pool with a different size. Though this error seems to be something else all together.

Looking at you log, it seems to be happening when the Kubernetes provider is attempting to access the secret from the cluster:

    kubernetes_secret.example: Refreshing state... [id=default/docker-cfg]

Can you share how you've configured the Kubernetes provider? My first guess would be that you have a local kubeconfig file that is pointing at at localhost, and there is something else running there now. Specifying `load_config_file = false` will prevent the kubeconfig file being used over what is configured in Terraform.

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#load_config_file

**Comment by danryu** [comment]
Thanks @andrewsomething for the clarification on DO node resizing.

However on the localhost error side - it's not so clear.
> My first guess would be that you have a local kubeconfig file that is pointing at at localhost, and there is something else running there now.

That's the thing - I don't have any kubeconfig that is pointing at any k8s cluster apart from the one on DO - the only cluster I'm running anywhere.

I set up the k8s provider as per the docs:
```
provider "kubernetes" {
  load_config_file = false
  host  = digitalocean_kubernetes_cluster.service_live.endpoint
  token = digitalocean_kubernetes_cluster.service_live.kube_config[0].token
  cluster_ca_certificate = base64decode(
    digitalocean_kubernetes_cluster.service_live.kube_config[0].cluster_ca_certificate
  )
}

resource "kubernetes_secret" "tremf" {
  metadata {
    name = "docker-cfg"
  }

  data = {
    ".dockerconfigjson" = digitalocean_container_registry_docker_credentials.tremfregcred.docker_credentials
  }

  type = "kubernetes.io/dockerconfigjson"
}
```

**Comment by andrewsomething** [comment]
Looking into this newly reported issue (https://github.com/digitalocean/terraform-provider-digitalocean/issues/562), I'm wondering if this problem is related to using interpolation to pass credentials to the Kubernetes provider. Do you have better results if you first apply changes to the cluster alone before applying changes for other resources?

    terraform apply -target digitalocean_kubernetes_cluster.service_live

**Comment by danryu** [comment]
Hi @andrewsomething - sorry, I meant to try this, but project work pulled me away and I never got back to it.

We can close this if you want - or we can keep it open until I can test the same scenario in TF, possibly not for several weeks though.

**Comment by andrewsomething** [comment]
Thanks for the follow up @danryu. I'm going to go ahead and close this out, but don't hesitate to reopen or create a new issue if you're still having problems.
