### ISSUE TITLE
How to correctly and safely provision volumes?

### ISSUE THREAD

**Issue by hholst80** [digitalocean/terraform-provider-digitalocean#560]
I found an issue that the initial filesystem only provision a 380 MB filesystem.

Is there a way to at least make the initial filesystem (not a resize) happen seemless with Terraform? Either via the TF provider or as a best-practice workflow on-top of TF?

Background:

https://github.com/hashicorp/terraform/issues/27537#issuecomment-762905289

**Comment by andrewsomething** [comment]
Can you share the configuration that you are using? 

```
resource "digitalocean_volume" "test" {
  name                    = "test"
  region                  = "ams3"
  size                    = 50
  initial_filesystem_type = "ext4"
}

resource "digitalocean_droplet" "test" {
  name   = "test"
  size   = "s-1vcpu-1gb"
  image  = "ubuntu-20-04-x64"
  region = "ams3"
}

resource "digitalocean_volume_attachment" "test" {
  droplet_id = digitalocean_droplet.test.id
  volume_id  = digitalocean_volume.test.id
}
```

SSHing into the Droplet created using the above config shows the volume to be sized as expected:

```
# lsblk --fs /dev/disk/by-id/scsi-0DO_Volume_test
NAME FSTYPE LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINT
sda  ext4         fc830fb1-2ec9-47aa-bd1a-cfe51da71fb5   46.9G     0% /mnt/test
```

**Comment by hholst80** [comment]
Let me run back and double check these things.  The only obvious difference is that I use rancheros instead of the default os for a droplet? (Also, I am explicit about which ssh keys should be added - are all keys added by default?)

```
resource "digitalocean_droplet" "XXX" {
  image     = "rancheros"
  name      = "XXX.omcr.io"
  region    = "ams3"
  size      = "s-1vcpu-1gb"
  ssh_keys  = data.digitalocean_ssh_keys.keys.ssh_keys.*.id
}

data "digitalocean_ssh_keys" "keys" {
}
```

**Comment by hholst80** [comment]
I can confirm that it works with debian.

Changing the droplet os to rancheros.  The disk is not mounted, but more problematically, it is not resized to 50GiB.  The filesystem is ext4 (correctly set) but not grown to 50GiB the full extent of the underlying blockstore device.

![image](https://user-images.githubusercontent.com/6200749/105625758-9917a380-5e2b-11eb-969d-68e58ea7d7f8.png)

**Comment by andrewsomething** [comment]
> Changing the droplet os to rancheros.

I checked in with our block storage team and unfortunately auto-mounting/formating is not supported RancherOS.  

https://www.digitalocean.com/docs/volumes/#limits

The recommendation for distros like RancherOS is to format it on the guest OS directly. Eg:

    sudo mkfs.ext4 /dev/disk/by-id/scsi-0DO_Volume_name
    sudo mkdir -p /mnt/name
    sudo mount -o discard,defaults /dev/disk/by-id/scsi-0DO_Volume_name /mnt/name

If you attach a newly formatted volume that shows the incorrect size, you should be able to expand the file system on it. Eg:

    sudo resize2fs /dev/disk/by-id/scsi-0DO_Volume_name

**Comment by hholst80** [comment]
So the format is done on the droplet that mounts the persistent storage, after the volume is created?

**Comment by andrewsomething** [comment]
Right. The recommendation for RancherOS is to create an un-formatted volume and format it once attached to the Droplet.

**Comment by hholst80** [comment]
RancherOS is EOL'd for mid 2021 so no matter. I did not know that. No need for either of the parties here to continue spending time on this. Thank you guys for looking into it though!
