### ISSUE TITLE
digitalocean_kubernetes_cluster has empty attributes when digitalocean_kubernetes_versions does not match actual cluster version

### ISSUE THREAD

**Issue by devurandom** [digitalocean/terraform-provider-digitalocean#562]
### Terraform Version

```
❯ terraform -v
Terraform v0.14.5
```

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_kubernetes_versions
- digitalocean_kubernetes_cluster
- kubernetes (provider)

### Terraform Configuration Files

Config excerpt:

```hcl
data "digitalocean_kubernetes_versions" "default" {
  version_prefix = "1.18."
}

resource "digitalocean_kubernetes_cluster" "default" {
  [...]
  auto_upgrade = true
  version      = data.digitalocean_kubernetes_versions.default.latest_version
  [...]
}

provider "kubernetes" {
  host             = digitalocean_kubernetes_cluster.default.endpoint
  token            = digitalocean_kubernetes_cluster.default.kube_config[0].token
  cluster_ca_certificate = base64decode(
    digitalocean_kubernetes_cluster.default.kube_config[0].cluster_ca_certificate
  )
}
```

### Expected Behavior

`terraform plan` or `terraform refresh` should not output an error.

### Actual Behavior

```
Error: Get "http://localhost/api/v1/namespaces/[...]": dial tcp [::1]:80: connect: connection refused
Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

### Steps to Reproduce

1. I recently upgraded my DigitalOcean Kubernetes cluster from 1.18 to 1.19 using the web UI
2. Today I tried to `terraform refresh` and received abovementioned error messages
3. I tried `terraform plan` and saw the same messages
4. Providing a literal string (instead of referring to the `digitalocean_kubernetes_cluster` resource) for the `host` of the `kubernetes` provider turns the error message into: `Error: Get "[...]/api/v1/namespaces/[...]": x509: certificate signed by unknown authority` (now using the correct endpoint instead of `http://localhost`)
5. Changing `version_prefix` from `"1.18."` to `"1.19."` resolves the problem (the error messages do not appear any longer)

**Comment by andrewsomething** [comment]
Hi @devurandom, 

What version of the Kubernetes provider are you using? It looks like they've recently released a new version with some behavior changes:

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/v2-upgrade-guide

It seems like we may need to update some of our docs around connecting the Kubernetes provider to a DigitalOcean Kubernetes resource.

**Comment by devurandom** [comment]
I first noticed the problem with kubernetes provider version 1.13.3, then upgraded to 2.0.1 and the problem persisted. The digitalocean provider was initially at version 2.3.0, then updated to 2.4.0, which also did not resolve the problem.

**Comment by andrewsomething** [comment]
> What fixed the problem in the end was to change the version_prefix in the digitalocean_kubernetes_versions data resource.

The expected behavior here would be for the DigitalOcean provider to propose creating a new cluster as downgrading versions in-place is not a supported action. Running a plan targeted at the the cluster alone does show this:

    terraform plan -target digitalocean_kubernetes_cluster.default


The Kubernetes provider docs have added a warning to discourage using interpolation to pass credentials:

> When using interpolation to pass credentials to the Kubernetes provider from other resources, these resources SHOULD NOT be created in the same Terraform module where Kubernetes provider resources are also used. This will lead to intermittent and unpredictable errors which are hard to debug and diagnose. The root issue lies with the order in which Terraform itself evaluates the provider blocks vs. actual resources. Please refer to this section of Terraform docs for further explanation.

> The most reliable way to configure the Kubernetes provider is to ensure that the cluster itself and the Kubernetes provider resources can be managed with separate apply operations.

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#stacking-with-managed-kubernetes-cluster-resources

So I think the "fix" here is to improve our docs for inter-operation with the Kubernetes provider.

**Comment by devurandom** [comment]
Can you please give a practical recommendation on how I should do it correctly? Is the correct way to lay out my Terraform code to have two directories, one for the cluster / machines (i.e. "DigitalOcean stuff") and one for the general infrastructure running on top (i.e. Kubernetes and Helm things)? And they must not be modules and not be referenced from the same Terraform code, to enforce that two separate `terraform apply` invocations are used? How do I transport credentials between the two directories in this case? Could you please provide an example that shows how to do the whole setup?

**Comment by lfarnell** [comment]
@devurandom So one thing you can investigate is separating your configuration into the base infrastructure bits (DigitalOcean stuff) and your "things" inside of Kubernetes. You can accomplish this using [Terraform modules](https://www.terraform.io/docs/language/modules/index.html). This will help with the separation of concerns between the infrastructure and the applications that run on top of it. The composition of how these modules are built is pretty flexible but I would encourage you to have a look around the [Terraform Registry](https://registry.terraform.io/browse/modules) and learn how others have structured their modules and how you can piece together modules. The decomposition of your large monolithic (just assuming here) is that you can eliminate the need to plan changes for large amounts of infrastructure if you opnly need to change some small property of a Kubernetes deployment.

**Comment by devurandom** [comment]
Thanks a lot, @lfarnell ! So far I split infrastructure (Kubernetes and database clusters in DigitalOcean, cert-manager, ingress-nginx, metrics-server, kube-state-metrics, newrelic agents) from the application (database database and user, deployment, service, secrets, ingress). I will see to split up the infrastructure some more.

Since you recommend using modules for this: Would combining several modules into one root module still satisfy the "managed with separate apply operations" @andrewsomething quoted from https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#stacking-with-managed-kubernetes-cluster-resources ? As I understood, Terraform reads all modules and then determines what to do to apply them all at once?

**Comment by lfarnell** [comment]
So I personally like to keep them in different modules that aren't nested like my example but you can do it
```hcl
module "infra" {
    source = "<some location>"
    foo = true
    bar = "1gb" 
}

module "apps" {
    source = "<some other location>"
    host = module.infra.host
    token = module.infra.token
    cluster_ca_cert = module.infra.cluster_ca_cert
}
```
This then you can do `terraform apply -module=infra` and once this is applied and completed you can do `terraform apply -module=apps`

**Comment by andrewsomething** [comment]
@lfarnell Thanks for sharing all that great advice. :blue_heart: 

@devurandom Sounds like you've made some good progress already, but hopefully the example in this PR will be helpful: https://github.com/digitalocean/terraform-provider-digitalocean/pull/564
