### ISSUE TITLE
failure to plan request due to random errors from loadbalancer

### ISSUE THREAD

**Issue by killyosaur** [digitalocean/terraform-provider-digitalocean#569]
starting with a build that already has a loadbalancer for kubernetes

Add redirect along with TLS certs

when the terraform times out due to the another resource taking too long (say digitalocean_apps) the following error occurs when I try and re-run the terraform request:
[DEBUG] Error setting Load Balancer forwarding_rule - error: &errors.errorString{s:"Invalid address to set: []string{\"forwarding_rule\", \"1\", \"certificate_name\"}"}

I also get a similar error when trying to remove the forwarding:
[DEBUG] Error setting Load Balancer forwarding_rule - error: &errors.errorString{s:"Invalid address to set: []string{\"forwarding_rule\", \"0\", \"certificate_name\"}"}

**Comment by SPTKL** [comment]
using version 2.4.0
I got the same error while declaring 
```terraform
data "digitalocean_loadbalancer" "<name>" {
  name = "<name>"
}
```

**Comment by adrian-dinu** [comment]
Got the same issue on 2.8.0 with a LB generated by Kubernetes:

```yaml
data "digitalocean_loadbalancer" "<name>" {
  name = "<name>"
}
```

Getting the error:

`Error: [DEBUG] Error setting Load Balancer forwarding_rule - error: &errors.errorString{s:"Invalid address to set: []string{\"forwarding_rule\", \"1\", \"certificate_name\"}"}`

This blocks the full terraform from planning or even refreshing.
