### ISSUE TITLE
Database without private networking causes crash on state refresh

### ISSUE THREAD

**Issue by flyte** [digitalocean/terraform-provider-digitalocean#576]
I'm in the process of upgrading from Terraform 0.11 to 0.14, currently upgrading to 0.12.

I created a DO postgres database using 1.2.0 (at the time it was unreleased, and I had to compile it myself) of this provider. However, now that I'm using Terraform 0.12, and have upgraded to 2.5.0 of the DO provider, I get a crash when I try to run `terraform apply`.

I've narrowed it down to the database, and created a brand new terraform 0.12 stack that just has the db in. It now crashes in the same way when I import the existing database using its ID.

### Terraform Version
```
Terraform v0.12.30
+ provider.digitalocean v2.5.0
```
### Affected Resource(s)

- digitalocean_database_cluster

### Terraform Configuration Files
```hcl
provider "digitalocean" {
  token   = local.digitalocean_token
  version = "~> 2.5.0"
}
```
```hcl
locals {
  digitalocean_token   = "<REDACTED>"
}
```
```hcl
resource "digitalocean_database_cluster" "db" {
  name       = "micro-staging"
  engine     = "pg"
  version    = "11"
  size       = "db-s-1vcpu-1gb"
  region     = "lon1"
  node_count = 1

  maintenance_window {
    day  = "saturday"
    hour = "07:00:00"
  }

  lifecycle {
    ignore_changes = [
      maintenance_window,
    ]
  }
}
```

### Debug Output
https://gist.github.com/flyte/b7be0b1a92b0d6c12c5737289b0f0bdf#file-command-output

### Panic Output
https://gist.github.com/flyte/b7be0b1a92b0d6c12c5737289b0f0bdf#file-crash-log

### Expected Behavior
State should have been updated from the data received from the DO API

### Actual Behavior
Terraform crashed

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` when you've got the DB in your state file already, or:
2. `terraform import digitalocean_database_cluster.db <REDACTED DB ID>`

### Important Factoids
When comparing the response from the DO API to a freshly made database (with the latest DO provider), the database I'm trying to get the status of (or import), doesn't contain the `private_connection` section or the `private_network_uuid` value.

**Comment by flyte** [comment]
Judging by https://github.com/digitalocean/terraform-provider-digitalocean/blob/main/digitalocean/resource_digitalocean_database_cluster.go#L421 it would suggest that the missing `private_network_uuid` and `private_connection` sections is causing the issue.

**Comment by flyte** [comment]
A bit of extra context here as well: https://developers.digitalocean.com/documentation/changelog/api-v2/private-networking-support-for-managed-databases/

**Comment by flyte** [comment]
I've just manually added the database to the default VPC, which now makes it return a `private_network_uuid` value, but still doesn't return a `private_connection` section. It also doesn't list a host or port on the DO control panel under Connection Details -> Private Network. This seems like a bug within DO itself, unless it's going to appear after some time.

**Comment by andrewsomething** [comment]
Thank you for flagging this issue @flyte. It does sound like there is an underlying issue outside of the Terraform provider. DigitalOcean databases should automatically be assigned to your default VPC for the region. Though we should also be handling this more gracefully on the Terraform side. This should not cause a panic.
