### ISSUE TITLE
digitalocean_database_replica missing urn attribute.

### ISSUE THREAD

**Issue by shinebayar-g** [digitalocean/terraform-provider-digitalocean#590]
### Terraform Version
Terraform v0.14.7

### Affected Resource(s)
digitalocean_database_replica
digitalocean_project

### Terraform Configuration Files
```hcl
terraform {
  backend "remote" {
    organization = "dddd"

    workspaces {
      name = "prod"
    }
  }

  required_version = ">= 0.14.7"

  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "2.5.1"
    }
  }
}

resource "digitalocean_database_cluster" "db_master" {
  name       = "mysql-cluster"
  engine     = "mysql"
  version    = "8"
  size       = "db-s-2vcpu-4gb"
  region     = "sgp1"
  node_count = 1
  tags       = "mysql-cluster"
}

resource "digitalocean_database_replica" "db_replica" {
  count = 1

  name       = "mysql-replica-${count.index + 1}"
  cluster_id = digitalocean_database_cluster.db_master.id
  region     = "sgp1"
  size       = "db-s-2vcpu-4gb"
  tags       = "mysql-cluster"
}

resource "digitalocean_project" "test" {
  name        = "Test Project"
  description = "Test Project"
  purpose     = "Web Application"
  environment = "Production"
  resources = [
    digitalocean_database_cluster.db_master.urn,
  ]
}
```

### Expected Behavior
Database cluster's read only replicas show up correctly in project menu.
![image](https://user-images.githubusercontent.com/3091558/108798558-0bc78c00-755c-11eb-8e78-220a379cca64.png)

### Actual Behavior
DB Replicas aren't not showing in DigitalOcean project menu.

![image](https://user-images.githubusercontent.com/3091558/108798492-e8044600-755b-11eb-8f18-dbdf1e609a44.png)

### Steps to Reproduce
1. `terraform apply`
2. Go to DigitalOcean console
3. Check project menu

### Additional info

Moving cluster to another project then moving back fixes this issue. But next terraform run deletes the replica again.

![image](https://user-images.githubusercontent.com/3091558/108799571-a0cb8480-755e-11eb-9f86-27d3e1e2f3e0.png)

[digitalocean_database_replica](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/database_replica#attributes-reference) resource should expose `urn` attribute.

**Comment by nicolasdalbroi** [comment]
Hello,

I'm experiencing the same issue. Is there any additional information? Or any planned updates on this?

**Comment by danaelhe** [comment]
Hi @shinebayar-g 
Thank you so much for bringing this up to us and the thorough explanation! We've also monitored the other similar Github issue to this (#639 ) and are currently investigating it. Will give an update as soon as we can.
