### ISSUE TITLE
Apple Silicon (darwin/arm64) support

### ISSUE THREAD

**Issue by Owpac** [digitalocean/terraform-provider-digitalocean#593]
### Terraform Version

Terraform v0.14.7

### Affected Resource(s)

All Digital Ocean objects

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

```terraform init``` successfully install digitalocean provider on darwin_arm64 platform

### Actual Behavior
What actually happened?

```
Error: Incompatible provider version

Provider registry.terraform.io/digitalocean/digitalocean v2.5.1 does not have
a package available for your current platform, darwin_arm64.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`

### Important Factoids

Running terraform on Macbook Pro M1 (darwin_arm64)

### References
 N/A

**Comment by andrewsomething** [comment]
Thanks for opening this issue. This is something we'll definitely want to support. With the release of Go 1.16 `darwin/arm64` is now officially supported: https://golang.org/doc/go1.16#darwin

Goreleaser will automatically build binaries once we've updated to using Go 1.16 for builds: https://goreleaser.com/deprecations/#builds-for-darwinarm64

**Comment by Owpac** [comment]
Thank you for your answer, do you have any idea of the release date of DO provider using Go 1.16 ?

**Comment by scotchneat** [comment]
We have a couple of features we intend to release soon. One is [done](https://github.com/digitalocean/terraform-provider-digitalocean/pull/594) and the other is [in progress](https://github.com/digitalocean/terraform-provider-digitalocean/issues/374). We should be able to address this issue with the same release. 

We intend to have those ready within the next week. If there's any delay, I'll look at cutting a release sooner to address this.

**Comment by scotchneat** [comment]
@Owpac the [latest release](https://github.com/digitalocean/terraform-provider-digitalocean/releases/tag/v2.6.0) is now available. Please let us know if you have any issues!
