### ISSUE TITLE
kubernetes example does not work

### ISSUE THREAD

**Issue by pyrho** [digitalocean/terraform-provider-digitalocean#600]
Hi there,

### Terraform Version
0.14.8

### Terraform Configuration Files
https://github.com/digitalocean/terraform-provider-digitalocean/blob/main/examples/kubernetes/kubernetes-config/main.tf#L18

### Debug Output
```
Terraform v0.14.8
Configuring remote state backend...
Initializing Terraform configuration...

Error: Unable to find cluster with name: MY_CLUSTER_NAME

  on kubernetes-config/main.tf line 18, in data "digitalocean_kubernetes_cluster" "primary":
  18: data "digitalocean_kubernetes_cluster" "primary" {
```

### Expected Behavior
The example works.

### Actual Behavior
The example does not work.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by scotchneat** [comment]
@pyrho the config file you referenced is actually a module of the parent folder. See here:
https://github.com/digitalocean/terraform-provider-digitalocean/blob/main/examples/kubernetes/main.tf#L36

While it's possible to run that config on its own, it would require an existing cluster, and to pass the required variables to terraform as `terraform apply -var cluster_id=$CLUSTER_ID -var cluster_name=$CLUSTER_NAME`.

The intention with these examples is that the full environment is managed at the `examples/kubernetes` folder level.

**Comment by pyrho** [comment]
Hi @scotchneat !

I know that the [kubernetes/main.tf](https://github.com/digitalocean/terraform-provider-digitalocean/blob/main/examples/kubernetes/kubernetes-config/main.tf) file is a module that's used in this [main.tf](https://github.com/digitalocean/terraform-provider-digitalocean/blob/main/examples/kubernetes/main.tf).That's how I'm using it currently.

In the current state (without my change that is), the first `terraform apply` call will succeed, but subsequent calls will fail with the error I mentioned (I realize now that was not clear in my first comment).

Could you try and reproduce the issue on your end ?

Then again, the issue is solved on my end so if you think this is just noise, feel free to keep this closed.

**Comment by scotchneat** [comment]
Thanks for the update @pyrho. Definitely. We'll be testing this out.

**Comment by danaelhe** [comment]
Hi @pyrho, could you provide us with the change that you did that caused the issue?

**Comment by pyrho** [comment]
I just tried to use [the example](https://github.com/digitalocean/terraform-provider-digitalocean/tree/main/examples/kubernetes) on a brand new cluster and it failed.
[My pr](https://github.com/pyrho/terraform-provider-digitalocean/commit/3dda906cd8285a39df938d0a427b1552c065d748) fixes the issue.

That being said, if you can't reproduce this issue then it surely must be an error on my part.

ftr: I'm not seeking assistance, just letting you know the issue I think I found and sharing what I think fixed it.

**Comment by danaelhe** [comment]
Sounds good, please don't hesitate to reach back out for anything.
