### ISSUE TITLE
Add support for maintenance_policy to digitalocean_kubernetes_cluster

### ISSUE THREAD

**Issue by nightvisi0n** [digitalocean/terraform-provider-digitalocean#607]
It seems the [latest provider](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/kubernetes_cluster) is missing the option to set a [maintenance_policy](https://developers.digitalocean.com/documentation/v2/#create-a-new-kubernetes-cluster) on the ressource.

### Affected Resource(s)
- digitalocean_kubernetes_cluster

### References
#237

**Comment by kakarukeys** [comment]
I second it.
