### ISSUE TITLE
Feat: Modify managed kubernetes cluster firewall, cluster-wide and for node-pools

### ISSUE THREAD

**Issue by atmosx** [digitalocean/terraform-provider-digitalocean#609]
### Terraform Version
```bash
$ terraform -v
Terraform v0.14.5
```

### Affected Resource(s)

- digitalocean_kubernetes_cluster
- digitalocean_kubernetes_node_pool

### Use case

I'm running pods as in `host mode` network. The application that runs on a specific node pool, will have to use a predefined UDP and TCP port range. There is no way to modify the firewall through terraform, same way we can do with `digitalocean_database_firewall`.

### Feature
Currently there is no way to modify the default kubernetes firewall through terraform.

Would be nice if the we had a `digitalocean_kubernetes_node_pool_firewall` for node pools or `digitalocean_kubernetes_firewall` for cluster-wide firewalls.

The DO API supports firewall modification, so this shouldn't be too hard to implement.

### Workarounds

I have not tested any workaround, but in theory we should be able to import and use the firewall through terraform.

**Comment by andrewsomething** [comment]
The `digitalocean_database_firewall` resource is needed as a database cluster's firewall rules (called "[trusted sources](https://www.digitalocean.com/docs/databases/postgresql/how-to/secure/#firewalls)" in the control panel) are not integrated with DigitalOcean cloud firewalls. It is a separate system managed at the database cluster level: https://developers.digitalocean.com/documentation/v2/#update-firewall-rules--trusted-sources--for-a-database-cluster

DigitalOcean Kubernetes clusters should support opening and closing of their NodePorts automatically, but the default firewalls can not be modified:

> When you create a cluster on version 1.19 or later, we automatically provision two cloud firewalls for the cluster and manage the opening and closing of their NodePorts (ports 30000-32767) as services are added and removed from the cluster. One firewall manages the connections between resources in your VPC network, including master nodes, and worker nodes, while the other manages connections between worker nodes and the public internet. Cluster firewalls are named k8s- concatenated with the cluster name.

> Defining a NodePort service in your service spec automatically opens the specified ports on the firewall. When you remove services from the cluster, the ports on the firewall close automatically.

> You cannot delete the cluster’s default firewalls or manually change their configuration in the control panel. Any changes made to the default firewalls through the control panel will not persist and be reverted. If you need to open ports outside of the NodePort range, such as port 80, manually create a new DigitalOcean Cloud Firewall and associate it with the cluster.

https://www.digitalocean.com/docs/kubernetes/resources/managed/#worker-node-firewalls

Multiple DigitalOcean cloud firewalls can be applied to the same group of resources as they are composable. To open an additional port for a cluster, you can use the standard `digitalocean_firewall` resource. Using tags, you can apply a firewall to all of the nodes in a specific node pool. You could use something like:

```
locals {
  k8-fw-tag = "node-pool-firewall-80"
}

resource "digitalocean_kubernetes_cluster" "foo" {
  name    = "foo"
  region  = "fra1"
  version = "1.20.2-do.0"

  node_pool {
    name       = "worker-pool"
    size       = "s-1vcpu-2gb"
    node_count = 1
    tags       = [local.k8-fw-tag]
  }
}

resource "digitalocean_firewall" "open-80" {
  name = "k8s-open-80"
  tags = [local.k8-fw-tag]

  inbound_rule {
    protocol         = "tcp"
    port_range       = "80"
    source_addresses = ["0.0.0.0/0", "::/0"]
  }
}
```

Let us know if that works for your use case.

**Comment by atmosx** [comment]
Hey!

Yes that worked for me. The solution I came up with is:

```hcl
resource "digitalocean_firewall" "app" {
  tags = [ "k8s:${digitalocean_kubernetes_cluster.comp.id}"]
  name = "k8s-${var.cluster_environment}"

  inbound_rule {
    protocol         = "tcp"
    port_range       = "4000"
    source_addresses = ["0.0.0.0/0", "::/0"]
  }

  inbound_rule {
    protocol         = "tcp"
    port_range       = "56000-58000"
    source_addresses = ["0.0.0.0/0", "::/0"]
  }

  inbound_rule {
    protocol         = "udp"
    port_range       = "56000-58000"
    source_addresses = ["0.0.0.0/0", "::/0"]
  }
}
```

Thanks!!!
