### ISSUE TITLE
Existing Droplet is not recreated when new SSH authorized keys are added to Terraform

### ISSUE THREAD

**Issue by pavgup** [digitalocean/terraform-provider-digitalocean#612]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
```
Terraform v0.14.9
+ provider registry.terraform.io/cloudflare/cloudflare v2.19.2
+ provider registry.terraform.io/digitalocean/digitalocean v2.7.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- digitalocean_droplet: when adding an ssh key to a droplet, the resource is not affected

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "digitalocean_droplet" "test" {
  image    = "ubuntu-20-04-x64"
  name     = "test.pg.gl" # This FQDN will generate a PTR record
  region   = "sfo3"
  size     = "s-2vcpu-4gb"
  ipv6     = true
  ssh_keys = [digitalocean_ssh_key.user.fingerprint, digitalocean_ssh_key.user2.fingerprint, digitalocean_ssh_key.user7.fingerprint, digitalocean_ssh_key.user4.fingerprint]
}
```

### Expected Behavior
What should have happened?
The droplet should have been recreated to allow for a set of authorized keys that include new users

### Actual Behavior
What actually happened?
The droplet remains up with new users not authorized

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by pavgup** [comment]
Thank you! <3

**Comment by andrewsomething** [comment]
This will be in the next release. Sorry it took so long!

**Comment by pavgup** [comment]
Oh man, no apologies required, you're making the world a better place. I'm just sorry I couldn't make the change myself! :)
