### ISSUE TITLE
Spaces creation fails: "no such host"

### ISSUE THREAD

**Issue by matthewhembree** [digitalocean/terraform-provider-digitalocean#617]
Hello!

### Terraform Version
```
Terraform v0.15.0
on darwin_amd64
+ provider registry.terraform.io/digitalocean/digitalocean v2.7.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- resource: digitalocean_spaces_bucket
- data: digitalocean_spaces_bucket

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
No issues with:
- resource: digitalocean_droplet

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    digitalocean = {
      source = "digitalocean/digitalocean"
      version = "2.7.0"
    }
  }
  required_version = "0.15.0"
}

provider "digitalocean" {
  token = var.digitalocean_token
  spaces_access_id = var.spaces_access_id
  spaces_secret_key = var.spaces_secret_key
}

resource "digitalocean_spaces_bucket" "i-dont-exist" {
  name = "i-dont-exist"
  region = "ny3"
}

data "digitalocean_spaces_bucket" "i-already-exist" {
  name = "i-already-exist"
  region = "ny3"
}

variable "digitalocean_token" {
  type = string
  description = "Digital Ocean API token"
  sensitive = true
}

variable "spaces_access_id" {
  type = string
  description = "Digital Ocean Spaces access ID"
  sensitive = true
}

variable "spaces_secret_key" {
  type = string
  description = "Digital Ocean Spaces secret key"
  sensitive = true
}

output "i-already-exist_attrs" {
  value = data.digitalocean_spaces_bucket.i-already-exist
}
```

### Debug Output
[trace.log](https://gist.github.com/matthewhembree/3235038c0f11aa761ac82610db7c8634#file-trace-log)
[refresh-trace.log](https://gist.github.com/matthewhembree/3235038c0f11aa761ac82610db7c8634#file-refresh-trace-log)

### Panic Output
n/a

### Expected Behavior
- Space created.
- Existing bucket attributes output.

### Actual Behavior
- Space not created.
- On `tf refresh`: error `no such host`

DNS lookup error on `tf apply`:
```
╷
│ Error: Error creating Spaces bucket: RequestError: send request failed
│ caused by: Put "https://i-dont-exist.ny3.digitaloceanspaces.com/": dial tcp: lookup i-dont-exist.ny3.digitaloceanspaces.com on 192.168.1.1:53: no such host
│
│   on main.tf line 1, in resource "digitalocean_spaces_bucket" "i-dont-exist":
│    1: resource "digitalocean_spaces_bucket" "i-dont-exist" {
│
╵
```

DNS lookup error on `tf apply`:
```
╷
│ Warning: Empty or non-existent state
│
│ There are currently no resources tracked in the state, so there is nothing to refresh.
╵
╷
│ Error: error reading Spaces bucket "": RequestError: send request failed
│ caused by: Head "https://i-already-exist.ny3.digitaloceanspaces.com/": dial tcp: lookup i-already-exist.ny3.digitaloceanspaces.com on 192.168.1.1:53: no such host
│
│   on main.tf line 6, in data "digitalocean_spaces_bucket" "i-already-exist":
│    6: data "digitalocean_spaces_bucket" "i-already-exist" {
│
╵
```

Same issue when resolver is configured to something else (e.g. 1.1.1.1).

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform refresh`

### Important Factoids
No special networking shims, firewalls. Macos firewall disabled.
Terraform installed with tfenv via Homebrew.

### References
n/a

Thanks!

**Comment by matthewhembree** [comment]
The same result with Terraform in Docker: [docker-trace.log](https://gist.github.com/matthewhembree/3235038c0f11aa761ac82610db7c8634#file-docker-trace-log)

```
❯ docker run -it -v $PWD:/data -w /data hashicorp/terraform:0.15.0 -v
Terraform v0.15.0
on linux_amd64
+ provider registry.terraform.io/digitalocean/digitalocean v2.7.0
```

Thanks!

**Comment by matthewhembree** [comment]
Oh @andrewsomething ... that's embarrassing for me. I thought I had at least tried letting the [default](https://github.com/digitalocean/terraform-provider-digitalocean/blob/9f791e084b07bbf5aac27b84061b1492132c9d05/digitalocean/resource_digitalocean_spaces_bucket.go#L47) flow through.

Thanks for the correction!

**Comment by andrewsomething** [comment]
No worries! That error message really isn't very clear at all. We should be doing something better.
