### ISSUE TITLE
Error finding provider registry.terraform.io/hashicorp/digitalocean

### ISSUE THREAD

**Issue by alapidas** [digitalocean/terraform-provider-digitalocean#621]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
terraform -v
Terraform v0.15.0
on darwin_amd64
```

### Terraform Configuration Files
```
[alapidas@giraffe ~/Downloads/do_test] ~> cat provider.tf
# Configure the DigitalOcean Provider
provider "digitalocean" {
  # export DIGITALOCEAN_TOKEN="Your API TOKEN"
}
[alapidas@giraffe ~/Downloads/do_test] ~> terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/digitalocean...
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/digitalocean: provider registry registry.terraform.io does not have a
│ provider named registry.terraform.io/hashicorp/digitalocean
│
│ Did you intend to use digitalocean/digitalocean? If so, you must specify that source address in each module which requires that provider. To see which
│ modules are currently depending on hashicorp/digitalocean, run the following command:
│     terraform providers
╵

[alapidas@giraffe ~/Downloads/do_test] ~> ls -al
total 8
drwxr-xr-x    3 alapidas  staff     96 Apr 21 21:40 .
drwx------@ 888 alapidas  staff  28416 Apr 21 21:39 ..
-rw-r--r--    1 alapidas  staff    113 Apr 21 21:40 provider.tf
```

### Debug Output
https://gist.github.com/alapidas/195b5a1d22d3abc3b6be3a39a4b8c4ee

### Expected Behavior
`terraform init` should complete

### Actual Behavior
Initialization doesn't complete.

### Steps to Reproduce
Create the file in the output above and run `terraform init`

**Comment by alapidas** [comment]
Related: https://github.com/rancher/terraform-provider-rke/issues/270

But this isn't in the examples here

**Comment by scotchneat** [comment]
Thank you for reporting this issue @alapidas. 

It looks like the droplet examples need to be updated (issue #622 has been created to track this change).

To resolve your issue, you need to map the provider name in a `terraform` configuration block. The [kubernetes](https://github.com/digitalocean/terraform-provider-digitalocean/blob/main/examples/kubernetes/main.tf#L1) example does include the required configuration. You would need to add something like this:

```
terraform {
  required_providers {
    digitalocean = {
      source = "digitalocean/digitalocean"
      version = ">= 2.8.0"
    }
  }
}
```

Please don't hesitate to reopen this issue if you continue to see the problem after making these changes.
