### ISSUE TITLE
Update the end to end Droplet example

### ISSUE THREAD

**Issue by andrewsomething** [digitalocean/terraform-provider-digitalocean#622]
This project includes an example of creating a Droplet, installing nginx on it, and assigning a domain to it:

https://github.com/digitalocean/terraform-provider-digitalocean/tree/main/examples/droplet

It was written years ago and it no longer represents Terraform best practices. In fact, it does not even run as written!

Since it was originally written, Terraform's configuration language has undergone a number of changes. When updating the example, Terraform's upgrade guides may be a good resource:

https://www.terraform.io/upgrade-guides/index.html

Beyond syntax changes, the example defaults to using `ubuntu-16-04-x64`. A more recent version of Ubuntu would be preferable.

Feel free to look for additional areas for improvement.

**Comment by scotchneat** [comment]
The docs published to the Terraform registry need to be updated as well - https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs#example-usage
