### ISSUE TITLE
terraform import of digitalocean_spaces_bucket always fails

### ISSUE THREAD

**Issue by danlester** [digitalocean/terraform-provider-digitalocean#627]
Hello! Even for a very basic spaces config, terraform import doesn't seem to work.

### Terraform Version
Terraform v0.15.0
on darwin_amd64

### Affected Resource(s)
- digitalocean_spaces_bucket

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    digitalocean = {
      source = "digitalocean/digitalocean"
      version = "2.8.0"
    }
  }
}

resource "digitalocean_spaces_bucket" "main" {
  name   = "dsl-import-test"
  region = "nyc3"

  acl = "private"
}
```

### Debug Output
`terraform apply` works as expected - the bucket is created at https://dsl-import-test.nyc3.digitaloceanspaces.com/

However if I run the following (after deleting the terraform.tfstate file):
```
terraform import digitalocean_spaces_bucket.main dsl-import-test
```

I see:

```
digitalocean_spaces_bucket.main: Importing from ID "dsl-import-test"...
digitalocean_spaces_bucket.main: Import prepared!
  Prepared digitalocean_spaces_bucket for import
digitalocean_spaces_bucket.main: Refreshing state... [id=dsl-import-test]
╷
│ Error: error reading Spaces bucket "dsl-import-test": RequestError: send request failed
│ caused by: Head "https://dsl-import-test..digitaloceanspaces.com/": dial tcp: lookup dsl-import-test..digitaloceanspaces.com: no such host
│
```

### Expected Behavior
I would have expected the terraform.tfstate file to be created to include the spaces bucket.

### Actual Behavior
I saw the error above... It looks as though the region has been dropped from the URL.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
1. `terraform apply`
1. `rm terraform.tfstate`
1. `terraform import digitalocean_spaces_bucket.main dsl-import-test`

Thank you very much for reading. Any insight or workarounds gratefully received!

**Comment by andrewsomething** [comment]
Hi @danlester,

When importing a Space, you must provide both its region and name separated by a comma: 

https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/spaces_bucket#import

So: `terraform import digitalocean_spaces_bucket.main nyc3,dsl-import-test`

Looks like we should be providing a much more helpful error here.

**Comment by danlester** [comment]
Thank you so much for helping with this! I tried all sorts of combinations of dots but not commas...

Sorry I didn't spot the note in the documentation. Definitely would be useful for a relevant error message if region not provided.

Thanks again.
