### ISSUE TITLE
Urn missing in database_replica

### ISSUE THREAD

**Issue by nicolasdalbroi** [digitalocean/terraform-provider-digitalocean#639]
Hello,

I'm experiencing some issues when I try to obtain the database replica urn while importing the resource. If I import the resource as a database_cluster it shows the urn, but it is not a database cluster. The urn is needed for the plan to not delete the resource. 

Terraform v0.15.1 provider registry.terraform.io/digitalocean/digitalocean v2.8.0

Can I get some help with this?

Regards.

**Comment by danaelhe** [comment]
Hi @nicolasdalbroi 
Thank you so much for bringing this up to us! We've also monitored the other similar Github issue to this (#590 ) and are currently investigating it. Will give an update as soon as we can.

**Comment by danaelhe** [comment]
Hi there,

Thank you for bringing this to our attention. This has been addressed in #921  and will be available in the next release (which we plan to do in the next few days).

Thank you so much for your feedback! Please don't hesitate to reach out again.

Dana
