### ISSUE TITLE
Idea: Provider Region Code

### ISSUE THREAD

**Issue by designermonkey** [digitalocean/terraform-provider-digitalocean#645]
I am wondering if it would be possible to add a feature of being able to specify the region code in the provider config. In a similar vein to how AWS have it configured, if the region were specified in the provider, each resource would check for that value, or demand it in it's own config.

I feel this would make it easy to use the provider in modules for example, where currently I am having to specify the region code into the module, where instead I could simply pass the relevant provider by region.

What do you think?

**Comment by andrewsomething** [comment]
Thanks for the suggestion. There is a related issue that has some more context around this: https://github.com/digitalocean/terraform-provider-digitalocean/issues/226 I do think a provider level default would be useful. Though there are some complications around how to implement that with Terraform. That issue and the Terraform SDK one linked there go into that. 

One difference between the AWS and DO APIs is that with AWS, you configure a client on a per region basis. If you want to work with multiple AWS regions, you need to configure multiple clients (or for Terraform, alias multiple provider blocks). With DO, you can specify the region at the resource level. So the AWS provider does not run into the same complications with using a default region.

I'm going to close this one out and continue tracking this request in the other issue.
