### ISSUE TITLE
Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by carlpett** [digitalocean/terraform-provider-digitalocean#655]
# Bug Report
---

## Describe the bug
When destroying droplets and updating the loadbalancer with the new, reduced, list of droplets, several "inconsistent plan" errors are produced (one per droplet removed, and one for the load balancer):

```
Error: Provider produced inconsistent final plan

When expanding the plan for
module.web-service.module.loadbalancer.digitalocean_loadbalancer.loadbalancer[0]
to include new values learned so far during apply, provider
"registry.terraform.io/-/digitalocean" produced an invalid new value for
.droplet_ids: actual set element cty.NumberIntVal(2.47554157e+08) does not
correlate with any element in plan.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

... repeated once per destroyed droplet

Error: Provider produced inconsistent final plan

When expanding the plan for
module.web-service.module.loadbalancer.digitalocean_loadbalancer.loadbalancer[0]
to include new values learned so far during apply, provider
"registry.terraform.io/-/digitalocean" produced an invalid new value for
.droplet_ids: length changed from 18 to 24.
```
### Affected Resource(s)
- digitalocean_loadbalancer

### Expected Behavior
No errors

### Actual Behavior
Errors described above

### Steps to Reproduce
1. Reduce droplet count 
1. `terraform apply`

**Terraform Configuration Files**
```tf
resource "digitalocean_droplet" "droplet" {
  count = var.droplet_count
  ...
}

resource "digitalocean_loadbalancer" "loadbalancer" {
  droplet_ids = digitalocean_droplet.droplet.*.id
  ...
}
```

## Additional context
This appears to have been a recent change in the DigitalOcean APIs? We've been doing the same operation for a long time without errors.

We are unfortunately stuck on 1.23, so this might be something which has been long deprecated and was finally removed? If so, this would just be a "FYI"-type of issue.

**Comment by andrewsomething** [comment]
Hi @carlpett. I haven't been able to reproduce this issue using Terraform v1.0 with either v2.10.1 or v1.23.0 of the provider. What version of Terraform itself are you using?

Is this something you've hit on multiple occasions? Wondering if there was a temporary issue with the load balancer API that has cleared up.

**Comment by carlpett** [comment]
Hi @andrewsomething,
We're on 0.12.28 (yes, old versions of everything in this part of our environment). I've run into it twice, earlier today when I created this issue, and last week. I will be running the same operation again tomorrow, can report back if it reproduces again.
Not sure if it might be related to having large lists of droplet id:s directly on the LB? The web console only allows ten droplets, but we've gone from 36->24, and now 24->18, so still quite a bit larger.

**Comment by carlpett** [comment]
Hi,
No, we've reduced our usage rather drastically, so it is no longer an active issue.
