### ISSUE TITLE
digitalocean_droplet is not clear about SSH usage and password creation

### ISSUE THREAD

**Issue by root0day** [digitalocean/terraform-provider-digitalocean#685]
I can’t know what type of ssh_keys  should be filled in
In addition, the document does not seem to say how to create an instance with a password 

Operating system and software information
windows 10 lstc 1809
Terraform v1.0.5

terraform {
  required_providers {
    digitalocean = {
      source = "digitalocean/digitalocean"
      version = "~> 2.0"
    }
  }
}

provider "digitalocean" {
  token = "36049f*****"
}

resource "digitalocean_custom_image" "example" {
  name   = "image-01"
  url = "https://cloud.debian.org/images/cloud/OpenStack/9.13.26-20210722/debian-9.13.26-20210722-openstack-amd64.qcow2"
  regions = ["sfo3"]
}

resource "digitalocean_ssh_key" "example" {
  name       = "TerraformExample"
  public_key = "ssh-rsa xxxxx"
}

resource "digitalocean_droplet" "example" {
  image     = digitalocean_custom_image.flatcar.id
  name      = "example-01"
  region    = "sfo3"
  size      = "s-1vcpu-1gb"
  ipv6      = "false"
  ssh_keys  = digitalocean_ssh_key.example.id
}

Error message
╷
│ Error: Reference to undeclared resource
│
│   on main.tf line 29, in resource "digitalocean_droplet" "example":
│   29:   image     = digitalocean_custom_image.flatcar.id
│
│ A managed resource "digitalocean_custom_image" "flatcar" has not been declared in the root module.
╵

**Comment by scotchneat** [comment]
Hi @root0day,

The error message indicates that the `flatcar` image resource has not been created.  The only image resource created in the main.tf above is a custom image referenced as `example`:

```
resource "digitalocean_custom_image" "example" {
    name = "image-01"
    url = "https://cloud.debian.org/images/cloud/OpenStack/9.13.26-20210722/debian-9.13.26-20210722-openstack-amd64.qcow2"
    regions = ["sfo3"]
}
```

This can be resolved by changing the resource name/alias to `flatcar` (Note: The name given to the image is still `image-01`. This can can also be changed to `flatcar` if you wish.):

```
resource "digitalocean_custom_image" "flatcar" {
    name   = "image-01"
    url = "https://stable.release.flatcar-linux.net/amd64-usr/2605.7.0/flatcar_production_digitalocean_image.bin.bz2"
    regions = ["nyc3"]
}
```

**Comment by scotchneat** [comment]
I'm closing this issue since I believe it's answered. However, if you continue to have problems and need to pick this discussion back up, feel free to reopen it.
