### ISSUE TITLE
digitalocean_app is missing numerous properties / documentation

### ISSUE THREAD

**Issue by itsjoekent** [digitalocean/terraform-provider-digitalocean#686]
### Is your feature request related to a problem? Please describe.
- [ ] The `id` of the app is [used in tests](https://github.com/digitalocean/terraform-provider-digitalocean/blob/9f791e084b07bbf5aac27b84061b1492132c9d05/digitalocean/datasource_digitalocean_app_test.go#L82), but is not defined in the [resource documentation](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/app). Having this ID is very useful/important when trying to connect the App to a DB Firewall.
- [ ] I am unable to configure alerts policies, (see https://github.com/digitalocean/terraform-provider-digitalocean/issues/683)
- [ ] I am unable to set CORS policies https://docs.digitalocean.com/products/app-platform/how-to/update-cors-policies/
- [ ] The "instance_size" is not well documented anywhere I can find (in either the Terraform provider docs or the DO website)
- [ ] I cannot change the default "Basic Plan" that my app is set to
![Screen Shot 2021-09-09 at 5 37 42 PM](https://user-images.githubusercontent.com/897368/132765978-14b44bf1-f155-4b94-964d-7f9ec08657dc.png)

### Describe the solution you'd like
Ideally all of the available config options work within Terraform, but at a minimum it would be great if the documentation was updated for the missing fields.

**Comment by andrewsomething** [comment]
Thanks for all the feedback. We'll be working to get all of this covered, but I wanted to address these two related pieces:

> The "instance_size" is not well documented anywhere I can find (in either the Terraform provider docs or the DO website)￼
> I cannot change the default "Basic Plan" that my app is set to

The `instance_size_slug` is linked to the plan. To change the plan, you need to change the `instance_size_slug` . The available instances sizes can be [retrieved via the API](https://docs.digitalocean.com/reference/api/api-reference/#operation/list_instance_sizes) or with doctl:

```
$ doctl apps tier instance-size list
Name               Slug               CPUs           Memory        $/month    $/second     Tier            Tier Downgrade/Upgrade Path
Basic XXS          basic-xxs          1 shared       512.00 MiB    5.00       0.0000021    basic           basic-xxs -> professional-xs
Basic XS           basic-xs           1 shared       1.00 GiB      10.00      0.0000041    basic           basic-xs -> professional-xs
Basic S            basic-s            1 shared       2.00 GiB      20.00      0.0000083    basic           basic-s -> professional-s
Basic M            basic-m            2 shared       4.00 GiB      40.00      0.0000165    basic           basic-m -> professional-m
Professional XS    professional-xs    1 shared       1.00 GiB      12.00      0.0000050    professional    basic-xs <- professional-xs
Professional S     professional-s     1 shared       2.00 GiB      25.00      0.0000103    professional    basic-s <- professional-s
Professional M     professional-m     2 shared       4.00 GiB      50.00      0.0000207    professional    basic-s <- professional-m
Professional 1L    professional-1l    1 dedicated    4.00 GiB      75.00      0.0000310    professional    basic-m <- professional-1l
Professional L     professional-l     2 dedicated    8.00 GiB      150.00     0.0000620    professional    basic-s <- professional-l
Professional XL    professional-xl    4 dedicated    16.00 GiB     300.00     0.0001240    professional    basic-s <- professional-xl
```

**Comment by itsjoekent** [comment]
Thank you!
