### ISSUE TITLE
Plugin crashes if first apply invocation fails

### ISSUE THREAD

**Issue by jasonaibrahim** [digitalocean/terraform-provider-digitalocean#689]
# Bug Report

---

## Describe the bug

When using a terraform configuration that includes a `digitalocean_app` declaration, if `terraform apply` fails the first time, subsequent invocations will crash the plugin.

### Affected Resource(s)

- digitailocean_app

### Expected Behavior

The plugin should have completed the requested execution without crashing

### Actual Behavior

The plugin crashed

### Steps to Reproduce

1. create a terraform configuration with invalid `digitalocean_app` parameters. e.g. set `region` to `abc`
2. run `terraform apply` - the execution will fail but __not__ crash
3. change terraform configuration back to something valid, e.g. set `region` to `sfo`
4. run `terraform apply` - the plugin crashes

**Panic Output**

<summary>
<details>
Stack trace from the terraform-provider-digitalocean_v2.11.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdfe531]

goroutine 73 [running]:
github.com/digitalocean/terraform-provider-digitalocean/digitalocean.resourceDigitalOceanAppRead(0x123ae98, 0xc0005b7320, 0xc0005fd200, 0xf60860, 0xc0006aecc0, 0xc0005a7410, 0xc0008d5908, 0x40e0f8)
        github.com/digitalocean/terraform-provider-digitalocean/digitalocean/resource_digitalocean_app.go:111 +0x471
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0005d88c0, 0x123ae28, 0xc0003a6300, 0xc0005fd200, 0xf60860, 0xc0006aecc0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:347 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0005d88c0, 0x123ae28, 0xc0003a6300, 0xc0008ece70, 0xf60860, 0xc0006aecc0, 0xc000019198, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c030, 0x123ae28, 0xc0003a6300, 0xc0003a6340, 0xc0003a6300, 0x40b965, 0x1007960)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0004a0be0, 0x123aed0, 0xc0003a6300, 0xc00009b620, 0xc0004a0be0, 0xc0003a8900, 0xc000101ba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x1049820, 0xc0004a0be0, 0x123aed0, 0xc0003a8900, 0xc00009b5c0, 0x0, 0x123aed0, 0xc0003a8900, 0xc0008b7000, 0x7c7)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000d6000, 0x1244738, 0xc000083500, 0xc000160100, 0xc000096cf0, 0x17d8b90, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0000d6000, 0x1244738, 0xc000083500, 0xc000160100, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000524220, 0xc0000d6000, 0x1244738, 0xc000083500, 0xc000160100)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-digitalocean_v2.11.1 plugin crashed!

</details>
</summary>

**Comment by jasonaibrahim** [comment]
I was able to move past this by running `terraform state pull` and trying again. 

I won't close this just yet since there does appear to be a bug with the plugin, but if anyone else is encountering this issue, try viewing the disaster recovery docs here: https://www.terraform.io/docs/cli/state/recover.html

**Comment by andrewsomething** [comment]
This same panic was reported in https://github.com/digitalocean/terraform-provider-digitalocean/issues/678 and https://github.com/digitalocean/terraform-provider-digitalocean/issues/700 and fixed in https://github.com/digitalocean/terraform-provider-digitalocean/pull/684. Looks like we missed closing this one. Thanks for the report!
