### ISSUE TITLE
Mongo DB User password attribute is empty

### ISSUE THREAD

**Issue by rgbrizzlehizzle** [digitalocean/terraform-provider-digitalocean#706]
# Bug Report

## Describe the bug
Hi... The documentation for the provider states that a password attribute is exported for a `digitalocean_database_user`.  However, this does not occur for the mongo db user.  Or perhaps, it does, but the password is empty.  It is unclear to me at the moment.  

### Affected Resource(s)
- `digitalocean_database_user` (specifically for MongoDB)

### Expected Behavior
A password should be generated for a user declared in terraform code

### Actual Behavior
The password attribute is empty. 

### Steps to Reproduce
Take the following 

```hcl
resource "digitalocean_database_cluster" "example" {
  name = "example"
  engine = "mongodb"
  version = "4"
  size = "db-s-1vcpu-1gb"
  region = "nyc1"
  node_count = "1"
}

resource "digitalocean_database_db" "example" {
  cluster_id = digitalocean_database_cluster.example.id
  name = "example"
}
resource "digitalocean_database_user" "example" {
  cluster_id = digitalocean_database_cluster.example.id
  name = "example"
}
```

On apply, this seems to deploy no problem.  However, on inspection of the terraform state, it is clear that the user password is either not generated at all or not passed along in the response.   See this snippet of state 

```json
{
      "mode": "managed",
      "type": "digitalocean_database_user",
      "name": "example",
      "provider": "provider[\"registry.terraform.io/digitalocean/digitalocean\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "cluster_id": "omitted",
            "id": "omitted",
            "mysql_auth_plugin": null,
            "name": "example",
            "password": "", // <---- 😭 😭 😭 
            "role": "normal"
          },
          "sensitive_attributes": [],
          "private": "bnVsbA==",
          "dependencies": [
            "digitalocean_database_cluster.example"
          ]
        }
      ]
    }
```

This is _very_ blocking, as it basically renders managed mongodb not functional from a fully automated deployment perspective.  Hope you guys can get this resolved ASAP.  Was so excited to start leveraging this.

**Comment by andrewsomething** [comment]
Thanks for the report. This issue was fixed in https://github.com/digitalocean/terraform-provider-digitalocean/pull/697 and will be available in the next release.
