### ISSUE TITLE
Floating IP Assignment Action Status Update

### ISSUE THREAD

**Issue by mpuckett159** [digitalocean/terraform-provider-digitalocean#711]
# Bug Report

## Version Info
❯ terraform -v
Terraform v1.0.6
on windows_amd64
+ provider registry.terraform.io/digitalocean/digitalocean v2.12.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

## Describe the bug
When attempting to assign a `digitalocean_floating_ip_assignment` resource to a `digitalocean_droplet` resource I receive the following error:

`Error: Error waiting for FloatingIP (x.x.x.x) to be Assigned: unexpected state 'done', wanted target 'completed'. last error: %!s(<nil>)
│
│   with digitalocean_floating_ip_assignment.pub_ip,
│   on main.tf line 86, in resource "digitalocean_floating_ip_assignment" "pub_ip":
│   86: resource "digitalocean_floating_ip_assignment" "pub_ip" {`

It would appear that the issue is that DigitalOcean returns the `status` field of for their `floating_ips/$floaing_ip/actions` API as `done` instead of `completed` which is what the provider is expecting. Please see the References section below for more details. The line specified just needs to be updated from `completed` to `done`. I'll probably make a PR to fix it but just creating the Issue so others can see if they search for it.

### Affected Resource(s)
- digitalocean_floating_ip_assignment

### Expected Behavior
The `digitalocean_floating_ip_assignment` should complete with no errors.

### Actual Behavior
I receive an error.

### Steps to Reproduce
1. Create Terraform configuration that uses the `digitalocean_floating_ip_assignment` resource that will be assigned to a `digitalocean_droplet` resource.
2. `terraform apply`

**Terraform Configuration Files**
`# Create droplet with userdata stored in cloud-config.yaml file
resource "digitalocean_droplet" "owncast" {
  name               = "owncast-droplet"
  size               = "c-4"
  image              = element(tolist(data.digitalocean_images.docker.images), 0).id
  region             = "sfo3"
  ipv6               = false
  user_data          = local.user_data_local
  tags               = [digitalocean_tag.owncast_tag.id]
}

# Assign floating IP to new droplet
resource "digitalocean_floating_ip_assignment" "pub_ip" {
  ip_address = "x.x.x.x"
  droplet_id = digitalocean_droplet.owncast.id
}`

**Panic Output**
None

**References**
[DigitalOcean floating_ip action API reference](https://docs.digitalocean.com/reference/api/api-reference/#operation/list_floating_ip_actions)
[Example current API response](https://gist.github.com/mpuckett159/9d6bf4f50edf8f1b0d9f4fd72fde8027)
[Line to update](https://github.com/digitalocean/terraform-provider-digitalocean/blob/cdad3198cbc922c11ed673a49138851ddd1c2103/digitalocean/resource_digitalocean_floating_ip_assignment.go#L55)

**Comment by mpuckett159** [comment]
It would appear that this change has been reverted on the DigitalOcean side already.... I guess someone pushed a change to prod before it was ready.

**Comment by andrewsomething** [comment]
Thanks for reporting this @mpuckett159. It was indeed an error on the DigitalOcean API. The change has been reverted.

**Comment by andrewsomething** [comment]
Thanks for reporting this @mpuckett159. It was indeed an error on the DigitalOcean API. The change has been reverted.

**Comment by mpuckett159** [comment]
Thanks for confirming I was questioning my sanity a little bit lol.
