### ISSUE TITLE
floating_ip_assignment error

### ISSUE THREAD

**Issue by opichon** [digitalocean/terraform-provider-digitalocean#712]
# Bug Report

Floating_ip_assignment falis with this error:

`Error waiting for FloatingIP (143.198.248.229) to be Assigned: unexpected state 'done', wanted target 'completed'. last error: %!s(<nil>)`

```
resource "digitalocean_droplet" "this" {
  image      = var.image
  ipv6       = var.ipv6
  monitoring = var.monitoring
  name       = var.name
  region     = var.region
  size       = var.size
  ssh_keys   = [...]
  tags       = var.tags
  vpc_uuid = var.vpc_id
}

resource "digitalocean_floating_ip_assignment" "floating_ip" {
  count      = var.floating_ip != null ? 1 : 0
  depends_on = [digitalocean_droplet.this]
  droplet_id = digitalocean_droplet.this.id
  ip_address = var.floating_ip

  provisioner "local-exec" {
    when    = destroy
    command = "sed -i -e '/^${self.ip_address} .*/d' ~/.ssh/known_hosts"
  }
}
```
---

### Affected Resource(s)
- digitalocean_floating_ip_assignment
- 
If this issue appears to affect multiple resources, it may be an issue with
Terraform's core, so please mention this. -->

### Expected Behavior
Success instead of failure

### Actual Behavior
Droplet is created and IP address is assigned, but terraform reports a failure.  Outputs are not generated.

### Steps to Reproduce

**Terraform Configuration Files**

**Expected behavior**

**Debug Output**
https://gist.github.com/opichon/8b1d95ede224a33f0e375bb7a986c8f4

**Panic Output**

## Additional context

**Important Factoids**

**References**

**Comment by andrewsomething** [comment]
Thanks for reporting this @opichon. The cause was an unexpected change to the DigitalOcean API which has been reverted. This should be working again.
