### ISSUE TITLE
Wrong basic example for digitalocean_monitor_alert resource

### ISSUE THREAD

**Issue by lostintime** [digitalocean/terraform-provider-digitalocean#714]
# Bug Report

Wrong resource type in basic example in `digitalocean_monitor_alert` resource documentation.

---

## Describe the bug

In the basic example for `digitalocean_monitor_alert` resource `digitalocean_monitoring` is used as resource type, should be `digitalocean_monitor_alert`: 

```
# Create a new Web Droplet in the nyc2 region
resource "digitalocean_droplet" "web" {
  image  = "ubuntu-20-04-x64"
  name   = "web-1"
  region = "nyc2"
  size   = "s-1vcpu-1gb"
}

resource "digitalocean_monitoring" "cpu_alert" { // ----> resource "digitalocean_monitor_alert" "cpu_alert" 
  alerts {
    email = ["benny@digitalocean.com"]
    slack {
      channel   = "Production Alerts"
      url       = "https://hooks.slack.com/services/T1234567/AAAAAAAA/ZZZZZZ"
  }
  window      = "5m"
  type        = "v1/insights/droplet/cpu"
  compare     = "GreaterThan"
  value       = 95
  enabled     = true
  entities    = [digitalocean_droplet.web.id]
  description = "Alert about CPU usage"
}
```

### Affected Resource(s)

- digitalocean_monitor_alert

**Comment by andrewsomething** [comment]
Thanks for flagging this. It has been fixed in https://github.com/digitalocean/terraform-provider-digitalocean/pull/710 The way the Terraform registry works we'll need to cut a new release just to update the docs.
