### ISSUE TITLE
Kubernetes can be added to digitalocean_project_resources, project_resources

### ISSUE THREAD

**Issue by KylePeterDavies** [digitalocean/terraform-provider-digitalocean#749]
Kubernetes can be added to a project resource with terraform

```terraform
module "kubernetes_development_project_resources" {
  source = "../../modules/digitalocean/project_resources"
  project_id = module.kubernetes_development_project.project_id
  project_resources = [
    module.kubernetes_development_cluster.kubernetes_urn
  ]
}
```
The documentation here states otherwise, and it's incorrect

https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/project_resources

https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/project

**Comment by scotchneat** [comment]
@KylePeterDavies thanks for bringing this to our attention. We'll look into updating the documentation.
