### ISSUE TITLE
vultr can't create a instance

### ISSUE THREAD

**Issue by lyc0221** [digitalocean/terraform-provider-digitalocean#758]
# Bug Report

---

## Describe the bug

terraform version: `1.0.11`

`terraform plan` can't get the `data.vultr_plan.this`, it was ok last month.

### Affected Resource(s)

vultr_instance

### Steps to Reproduce

**Terraform Configuration Files**

data.tf
```
data "vultr_os" "this" {
  filter {
    name   = "name"
    values = ["Ubuntu 20.04 x64"]
  }
}

data "vultr_plan" "this" {
  filter {
    name   = "id"
    values = ["vc2-1c-2gb"]
  }
}
```

main.tf
```
module "vultr" {
  source            = "../../modules/vultr-instance"
  namenumber        = var.namenumber

  user              = var.user
  service           = var.service
  environment       = var.environment
  region            = var.region
  os_id             = data.vultr_os.this.id
  plan              = data.vultr_plan.this.id
  firewall_group_id = module.vultr_fw.this_firewall_id
}
```

**Expected behavior**

**Debug Output**

**Panic Output**

```
Error: Error getting plans: json: cannot unmarshal number 7.5 into Go struct field Plan.plans.monthly_cost of type int

   with data.vultr_plan.this,
   on data.tf line 8, in data "vultr_plan" "this":
    8: data "vultr_plan" "this" {
```

## Additional context

**Important Factoids**

**References**

**Comment by andrewsomething** [comment]
Sounds like you are trying to report an issue to Vultr. This is the repository of the DigitalOcean Terraform provider. Looks like this is probably the correct place:

https://github.com/vultr/terraform-provider-vultr
