### ISSUE TITLE
CA Attribute Reference, digitalocean_database_cluster

### ISSUE THREAD

**Issue by tfolbrecht** [digitalocean/terraform-provider-digitalocean#762]
### Is your feature request related to a problem? Please describe.

Currently using a local-exec to grab the CA for a db cluster with [the api](https://api.digitalocean.com/v2/databases/{database_cluster_uuid}/ca)
Would be nice to add ca to the Attributes Reference.

### Describe the solution you'd like
Add ca to the digitalocean_database_cluster Attributes Reference
 
### Describe alternatives you've considered
A little extra clicking in the gui 😉

### Additional context
Just a nice quality of life update. Would make my tf a little nicer looking

**Comment by tfolbrecht** [comment]
If anyone is searching, here's the shell script I'm using

```curl -X GET \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $dotoken" \
  "https://api.digitalocean.com/v2/databases/$DATABASE_ID/ca" | jq  -r -c .ca.certificate | base64 --decode > ca-certificate.crt```

**Comment by andrewsomething** [comment]
Hi @tfolbrecht,

We recently added a data source that can be used to get the certificate, e.g.:

```hcl
data "digitalocean_database_ca" "ca" {
  cluster_id = "aaa-bbb-ccc-ddd"
}

output "ca_output" {
  value = data.digitalocean_database_ca.ca.certificate
}
```

https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/data-sources/database_ca

Feel free to reopen if I've misunderstood the request.

**Comment by tfolbrecht** [comment]
Cool, appreciate it! much cleaner than the shell script. I'll try it out later.
