### ISSUE TITLE
cannot be configured within modules using count, for_each or depends_on

### ISSUE THREAD

**Issue by lyc0221** [digitalocean/terraform-provider-digitalocean#764]
# Bug Report

---

## Describe the bug

terraform version: 1.1.2
digitalocean version: v2.16.0

terraform init
```
╷
│ Error: Module module.droplet contains provider configuration
│
│ Providers cannot be configured within modules using count, for_each or depends_on.
╵

```

https://www.terraform.io/language/meta-arguments/for_each

Version note: for_each was added in Terraform 0.12.6. Module support for for_each was added in Terraform 0.13

### Affected Resource(s)

- digitalocean_droplet

### Steps to Reproduce

**Terraform Configuration Files**

main.tf
```
module "droplet" {
  for_each    = var.namenumber

  source      = "../../modules/do-droplet-with-volume"
  service     = format("%s-%s", var.project, each.key)
  environment = var.environment
  snapshot    = true
  region      = var.region[each.key]
  size        = var.size[each.key]
  volume      = var.volume[each.key]
  tags        = var.tags[each.key]
  namenumber  = each.key
  user        = var.user
  token       = var.token
}
```

**Expected behavior**

**Debug Output**

**Panic Output**

## Additional context

**Important Factoids**

**References**

**Comment by danaelhe** [comment]
Thank you for the write up. We will look into it as soon as we can.

**Comment by lyc0221** [comment]
any update ?

**Comment by andrewsomething** [comment]
Hi @lyc0221,

It's hard to give any definite answer without seeing the actual module in use. Though the error message suggests that you have configured the provider inside of the module. This is incompatible with using `for_each`, `count`, and `depends_on`. From HashiCorp's [docs on module development](https://www.terraform.io/language/modules/develop/providers#legacy-shared-modules-with-provider-configurations):

> Terraform v0.13 introduced the possibility for a module itself to use the `for_each`, `count`, and `depends_on` arguments, but the implementation of those unfortunately conflicted with the support for the legacy pattern.

> To retain the backward compatibility as much as possible, Terraform v0.13 continues to support the legacy pattern for module blocks that do not use these new features, but a module with its own provider configurations is not compatible with `for_each`, `count,` or `depends_on`. Terraform will produce an error if you attempt to combine these features.

> To make a module compatible with the new features, you must remove all of the `provider` blocks from its definition.

We'd suggest that you remove the `provider` config from the module and either allow for [implicit inheritance](https://www.terraform.io/language/modules/develop/providers#implicit-provider-inheritance) or [pass the provider details explicitly](https://www.terraform.io/language/modules/develop/providers#passing-providers-explicitly).

**Comment by mikeberezowski** [comment]
There has been no response from the original requestor in over 30 days. Closing this issue

**Comment by mulder999** [comment]
I strongly believe something should be done to be much more flexible in this regard.

Rationales:

- A module should be able to behave as a black box, encapsulating the provider details/complexity if it decide to do so
- A module should be testable on its own, the actual limit forces us to add/remove provider sections in the module
- A module might be part of several project where it is being used with/without a for_each/count. Module implementation should not changed based on how it is used

Suggestion:
- Introduce `scope-type` attribute in the `provider` block to define its actual scope, some possible modes could be:
   - `legacy`: (default when undefined) actual behavior ending with an error when using `for_each`, `count`, `depends_on` on a caller.
   - `local`: which would limit the provider scope definition to the actual module instance only (hence providing full module encapsulation). Passing the provider explicitly would not be allowed in this case (raise an error). Implicit provider from caller would be ignored.
   - `inherit`: which would automatically inherit provider scope from parent if the same provider is defined at a more global scope (implicit or explict). In opposition to `legacy` it will not raise an error if it is defined in 2 places or more but use the most global options. It behave as a `local` provider if there is nothing to inherit from.
