### ISSUE TITLE
create digitalocean_loadbalancer data source from load balancer id

### ISSUE THREAD

**Issue by andyli** [digitalocean/terraform-provider-digitalocean#772]
Right now the [`digitalocean_loadbalancer` data source](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/data-sources/loadbalancer) use `name` to query load-balancers. I would like to use id to query instead.

The reason I want to do this is that I'm setting up [Accessing pods over a managed load-balancer from inside the cluster](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/docs/controllers/services/examples/README.md#accessing-pods-over-a-managed-load-balancer-from-inside-the-cluster), in which I need to create a DNS record for the load balancer ip. The ingress-nginx k8s service records the load balancer id in the `kubernetes.digitalocean.com/load-balancer-id` annotation, but there is no record of the load balancer name.

**Comment by opeco17** [comment]
I've created the PR (https://github.com/digitalocean/terraform-provider-digitalocean/pull/773) to create loadbalancer datasource by its ID.

By this update, we will be able to create loadbalancer datasource by its ID in addition to name like below.

```
data "digitalocean_loadbalancer" "example" {
  id = "loadbalancer_id"
}
```
