### ISSUE TITLE
`droplet_agent` is not honored for `digitalocean_droplet` resource

### ISSUE THREAD

**Issue by brainplot** [digitalocean/terraform-provider-digitalocean#779]
# Bug Report

---

## Describe the bug
The Droplet agent seems to be installed regardless of whether or not the [`droplet_agent`](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/droplet#droplet_agent) argument is set to `true` or `false`.

### Affected Resource(s)
- digitalocean_droplet

### Expected Behavior
Setting `droplet_agent` to `false` should not install the droplet agent at all on the droplet. I expect to SSH into a fresh VM and get a `Unit droplet-agents.service could not be found` error when I run `systemctl status droplet-agent`.

The docs for `droplet_agent` say:

> - `droplet_agent` (Optional) - A boolean indicating whether to install the DigitalOcean agent used for providing access to the Droplet web console in the control panel. By default, the agent is installed on new Droplets but installation errors (i.e. OS not supported) are ignored. To prevent it from being installed, set to `false`. To make installation errors fatal, explicitly set it to `true`.

### Actual Behavior
The Droplet Agent is installed even if the `droplet_agent` argument is set to `false`.

### Steps to Reproduce
I've compiled a minimal reproducible example for this. Here's a Terraform configuration file that deploys a Droplet with `droplet_agent` set to `false` and enables SSH password access for `root`.

```terraform
terraform {
  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "~> 2.0"
    }
  }
}

variable "root_pwd" {
  type      = string
  sensitive = true
}

resource "digitalocean_droplet" "bug" {
  image             = "debian-11-x64"
  name              = "test-bug"
  region            = "fra1"
  size              = "s-1vcpu-1gb"
  graceful_shutdown = true
  droplet_agent     = false
  user_data         = <<-EOF
    #!/bin/sh

    printf 'root:${var.root_pwd}' | chpasswd
    sed -i -E '/PermitRootLogin[[:space:]]/c\PermitRootLogin yes' /etc/ssh/sshd_config
    systemctl reload ssh
  EOF
}

output "droplet_ipv4_address" {
  value = digitalocean_droplet.bug.ipv4_address
}
```

Then run the following commands.

```sh
terraform apply -auto-approve -var root_pwd='Pa$$w0rd' # or change to another one
```
```sh
ssh root@$(terraform output -raw droplet_ipv4_address)
```

```sh
systemctl status droplet-agent
```

The `droplet-agent` service appears to be up and running, even though `droplet_agent` was set to `false`.

## Terraform Version
```
Terraform v1.1.3
on darwin_arm64
+ provider registry.terraform.io/digitalocean/digitalocean v2.17.0
```

**Comment by Kidsan** [comment]
This looks like its due to not being able to set a default for the boolean. The boolean can have 3 states, `nil`, `true`, and `false` which each trigger different behaviour. The resource `resource_digitalocean_droplet.go` calls GetOk for the `droplet_agent` field which checks if it exists and that it isn't the zero value (false in this case). There is a deprecated function on `ResourceData` called `GetOkExists` which looks like it was designed to handle these triple value booleans but had unexpected behaviours.
