### ISSUE TITLE
digitalocean_ssh_keys missing configuration reference

### ISSUE THREAD

**Issue by tomjohnburton** [digitalocean/terraform-provider-digitalocean#792]
The documentation [here](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/data-sources/ssh_keys) fails to mention how you can utilise the `filter` section. It is missing some references to `values`.

## Suggested changes
Add the following to the documentation 

## Example Usage
```
data "digitalocean_ssh_keys" "keys" {
  filter {
    key       = "name"
    values  = ["key1", "key2"]
  }
}
```

## Argument Reference
`filter` supports the following arguments:

* `key` - (Required) Filter the SSH Keys by this key. This may be one of name, public_key, or fingerprint.
* `values` - (Required) List of values of the supplied `key` to filter the SSH Keys by.

**Comment by danaelhe** [comment]
Hi there,

Thank you so much for this write up. We will review it and apply changes if necessary as soon as we can.
