### ISSUE TITLE
`digitalocean_app` times out waiting for deployment when deployment has completed successfully

### ISSUE THREAD

**Issue by robbles** [digitalocean/terraform-provider-digitalocean#807]
# Bug Report

---

## Describe the bug
When making small changes to a `digitalocean_app`, I have seen the provider often get stuck on the `Still modifying...` step up until the create timeout for the resource is hit and I get the following error:
```
Error: timeout waiting for app (...redacted) deployment
```
However, when checking with both the web UI and `doctl`, I can see that the deploy completed successfully.

It looks to me like what might be happening is a race condition inside the code that checks for app deployment status, here:
https://github.com/digitalocean/terraform-provider-digitalocean/blob/v2.18.0/digitalocean/resource_digitalocean_app.go#L182-L190
If the deploy completes very rapidly in between checks for the deployment ID to show up on the app, I think that code will get stuck forever.
I tested by watching the TRACE logs of an apply, and it does look like the `in_progress_deployment` key doesn't show up on the timing out deploys.

### Affected Resource(s)

- digitalocean_app

### Expected Behavior

The deploy should have completed and `terraform apply` exited successfully.

### Actual Behavior

The apply command times out and shows an error.

### Steps to Reproduce

Given that this appears to be a timing bug, my particular config might not reproduce the issue reliably. I was able to trigger pretty often by making changes to the `alert` blocks on a previously deployed app only, and saw it happen only on an app deployed to the TOR region - perhaps because it's closer to me geographically?

**Expected behavior**

**Debug Output**

**Panic Output**

## Additional context

**Important Factoids**

**References**

**Comment by andrewsomething** [comment]
Fixed via https://github.com/digitalocean/terraform-provider-digitalocean/pull/831/commits/d95782344d77a609acf036501e9b54bf5b10d1cf in  https://github.com/digitalocean/terraform-provider-digitalocean/pull/831
