### ISSUE TITLE
labels provided to digitalocean_kubernetes_node_pool do not appear in kubernetes node metadata

### ISSUE THREAD

**Issue by mjpitz** [digitalocean/terraform-provider-digitalocean#810]
# Bug Report

## Describe the bug

Custom `labels` provided to a `digitalocean_kubernetes_node_pool` do not appear in the metadata of the node returned by the Kubernetes API. 

### Affected Resource(s)

- digitalocean_kubernetes_node_pool
- digitalocean_kubernetes_cluster.node_pool (maybe?)

### Expected Behavior

`labels` provided to a `digitalocean_kubernetes_node_pool` should appear in the metadata of the nodes belonging to that pool. Modifications to this should also cause an update.

### Actual Behavior

`labels` are not added to the metadata of the nodes belonging to that pool. Modifying the map does not cause an update.

### Steps to Reproduce

This appears like it may be documented, but unimplemented?

**Terraform Configuration Files**

Most of my Terraform is [here](https://github.com/mjpitz/mjpitz/tree/main/infra/do/mya), but I have a handful of additions that I have yet to commit below.

```terraform
# clusters.tf
locals {
  clusters = {for cluster in digitalocean_kubernetes_cluster.clusters : cluster.name => cluster.id}
}

resource "digitalocean_kubernetes_node_pool" "cluster_pools" {
  count = length(var.node_pools)

  cluster_id = local.clusters[var.node_pools[count.index].cluster]
  name       = var.node_pools[count.index].name
  size       = var.node_pools[count.index].node_size
  auto_scale = false
  node_count = var.node_pools[count.index].node_count
  tags       = var.node_pools[count.index].node_tags
  labels     = var.node_pools[count.index].node_labels
}
```

```terraform
# terraform.tfvars

node_pools = [
  {
    cluster : "mya-nyc",
    name : "mya-nyc-email",
    node_size : "s-4vcpu-8gb",
    node_count : 1,
    node_tags: [],
    node_labels: {
      "node.pitz.tech/role" : "email",
    },
    tags: [],
  },
]
```

**Expected behavior**

I would expect the labels to be added as documented and modifications to trigger updates.

**Debug Output**

Not Applicable.

**Panic Output**

Not Applicable.

## Additional context

- Attempted with several versions of the plugin (including latest).
- I tried scaling the cluster to see if it was a race condition with the API server that happened at the same time (no luck).

**Important Factoids**

Not Applicable.

**References**

Not Applicable.

**Comment by andrewsomething** [comment]
Hi @mjpitz,

I was not able to reproduce your issue with a simple config like:

```hcl
resource "digitalocean_kubernetes_cluster" "foo" {
  name   = "foo"
  region = "nyc1"
  version = "1.22.8-do.0"

  node_pool {
    name       = "worker-pool"
    size       = "s-2vcpu-2gb"
    node_count = 1
    labels = {"foo": "bar"}
  }
}
```

Changes to the labels were detected and applied. I was able to see the labels in the output of `kubectl describe nodes`. 

Though I was able to reproduce the problem after cloning your repo. After a bit of investigation, it looks like the issue is with the type for the variable in `vars.tf`. After making the change below, I was able to apply labels as expected.

```diff
$ git diff vars.tf
diff --git a/infra/do/mya/vars.tf b/infra/do/mya/vars.tf
index 79114d8..8888fbe 100644
--- a/infra/do/mya/vars.tf
+++ b/infra/do/mya/vars.tf
@@ -19,7 +19,7 @@ variable "clusters" {
     node_size : string,
     node_count : number,
     node_tags : list(string),
-    node_labels : object({}),
+    node_labels : map(string),
     tags : list(string),
   }))
 }
```

**Comment by mjpitz** [comment]
Interesting.... I'll give that a try. Thank you~!
