### ISSUE TITLE
Documentation inconsistent

### ISSUE THREAD

**Issue by KylePeterDavies** [digitalocean/terraform-provider-digitalocean#815]
If you look at `docs/resources/kubernetes_cluster.md` 

`node_pool.tags = A list of tag names to be applied to the Kubernetes cluster.`

versus  `docs/data-resources/kubernetes_cluster.md` 

`node_pool.tags =  list of tag names applied to the node pool.`

I believe that that `docs/resources/kubernetes_cluster.md` should be updated to show that the tags under `node_pool` are for the nodes and not the cluster as there is already a tags input for the cluster.

**Comment by danaelhe** [comment]
Hi there,

Thank you so much for this write up! I agree, it does appear to be a typo. We will post a PR fix for it soon. Thanks for bringing it to our attention!

**Comment by andrewsomething** [comment]
Closed via https://github.com/digitalocean/terraform-provider-digitalocean/pull/816
