### ISSUE TITLE
Additional records added to terraform for DNS

### ISSUE THREAD

**Issue by userbradley** [digitalocean/terraform-provider-digitalocean#819]
### Is your feature request related to a problem? Please describe.
No, not yet!

### Describe the solution you'd like
Currently when using domains via terraform, I am only able to create A records, no `txt` or anything else
 
### Describe alternatives you've considered
Using another DNS provicer

### Additional context
I would prefer to have 2 resources, one creating the Zone, and another creating records in that zone

new resource: `digitalocean_domain`
```
resource "digitalocean_domain" "example" {
  name = "do.breadinfra.net"
 }
```
This will have the outputs of:

* ID
* Creation time

Resource changes: `digitalocean_domain` 

```
resource "digitalocean_domain" "webserver" {
  name = "webserver"
  type = "a/mx/aaaa/txt/etc"
  zone_id = digitalocean_domain.example.id
  ttl = "100" //seconds
}
```

Either I've missed something but I don't seem to be able to create records other than `A` via terraform

**Comment by andrewsomething** [comment]
Hi @userbradley! Have you seen the [`digitalocean_record` resource](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/record)? If I'm reading your request right, it should do what you are looking for.  E.g.

```hcl
resource "digitalocean_domain" "default" {
  name = "example.com"
}

resource "digitalocean_record" "www" {
  domain = digitalocean_domain.default.id
  type   = "A"
  name   = "www"
  value  = "192.168.0.11"
}
```

**Comment by userbradley** [comment]
@andrewsomething - you know what, that's exactly what I was after...

Not sure how I missed that one. Thanks!

<3
