### ISSUE TITLE
Digital Ocean Container Registry - Region argument not allowed

### ISSUE THREAD

**Issue by Quixotical** [digitalocean/terraform-provider-digitalocean#829]
# Bug Report

---

## Describe the bug
When I select the region to build my DO container registry in, i receive an error stating that `region` is not an expected argument
and according to the documentation:

```[region](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/container_registry#region) - (Optional) The slug identifier of for region where registry data will be stored. When not provided, a region will be selected automatically.```

The expectation is that I can choose the region where I will be creating my registry.

### Affected Resource(s)
digitalocean_container_registry

### Expected Behavior
I can choose the region to create my resource in

### Actual Behavior
Receive the following error (repeating for simplicity sake)

```
Error: Unsupported argument

  on kubernetes/container_registry.tf line 4, in resource "digitalocean_container_registry" "my_registry":
   4:   region                 = "nyc3"

An argument named "region" is not expected here.
```

### Steps to Reproduce
1. `terraform validate`

**Terraform Configuration Files**
```
resource "digitalocean_container_registry" "my_registry" {
  name                           = "my-registry"
  subscription_tier_slug = "starter"
  region                          = "nyc3"
}
```

**Expected behavior**
I am on the latest version
```
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/digitalocean/digitalocean v2.15.0
+ provider registry.terraform.io/hashicorp/helm v2.5.1
+ provider registry.terraform.io/hashicorp/null v3.1.1
```

**Debug Output**
I pasted the error above

**Panic Output**
n/a

## Additional context

**Important Factoids**

**References**

**Comment by andrewsomething** [comment]
> + provider registry.terraform.io/digitalocean/digitalocean v2.15.0

Hi @Quixotical Looks like you need to update your version of the DigitalOcean provider. This is fairly new functionality that was added in v2.19.0.

https://github.com/digitalocean/terraform-provider-digitalocean/releases/tag/v2.19.0
