### ISSUE TITLE
slug for digitalocean_image rockylinux-8-x64 has changed?

### ISSUE THREAD

**Issue by ad8lmondy** [digitalocean/terraform-provider-digitalocean#834]
# Bug Report
---

## Describe the bug

It appears that the image ID for the `digitalocean_image` with slug `rockylinux-8-x64` has changed, which prompts Terraform to replace all the droplets we have using it.

### Affected Resource(s)
- digitalocean_droplet
- digitalocean_image

### Expected Behavior

Nothing should happen, our TF code is up to date with our infra, and this has been working OK for months now.

### Actual Behavior
As of today, when we run `terraform plan` on our code, we get messages similar to this for each of our nodes using the Rocky8 image:

```
-/+ resource "digitalocean_droplet" "software_license_ddm_stage_node" {
      ~ created_at           = "2022-05-16T06:31:30Z" -> (known after apply)
      ~ disk                 = 60 -> (known after apply)
      ~ id                   = "xxxxxxxxxxxxx" -> (known after apply)
      ~ image                = "96967120" -> "108964453" # forces replacement
      ~ ipv4_address         = "xxx.xxx.xxx.xxx" -> (known after apply)
      ~ ipv4_address_private = "xxx.xxx.xxx.xxx" -> (known after apply)
      + ipv6_address         = (known after apply)
      ~ locked               = false -> (known after apply)
      ~ memory               = 2048 -> (known after apply)
        name                 = "hostname.meow.com"
      ~ price_hourly         = 0.02232 -> (known after apply)
      ~ price_monthly        = 15 -> (known after apply)
      ~ private_networking   = true -> (known after apply)
      ~ status               = "active" -> (known after apply)
        tags                 = [
            "stage",
        ]
      ~ urn                  = "do:droplet:xxxxxxxxx" -> (known after apply)
      ~ vcpus                = 2 -> (known after apply)
      ~ volume_ids           = [] -> (known after apply)
        # (8 unchanged attributes hidden)
    }
```
(some details removed).

Note that the change of image ID is forcing the replacement.

Our images are defined as:

```
data "digitalocean_image" "rocky_8" {
  slug = "rockylinux-8-x64"
}
```

and the droplets themselves:

```
resource "digitalocean_droplet" "software_license_ddm_stage_node" {
  image    = data.digitalocean_image.rocky_8.id
  name     = "hostname.meow.com"
  ...
```

In a different Terraform project, I outputted the `digitalocean_images` data source, searching for all Rocky images, and got this:

```
  + rocky = {
      + filter = [
          + {
              + all      = false
              + key      = "slug"
              + match_by = "re"
              + values   = [
                  + "rockylinux.*",
                ]
            },
        ]
      + id     = "images/9698072944148077665"
      + images = [
          + {
              + created        = "2022-05-24T16:05:21Z"
              + description    = "RockyLinux 8.4 x64"
              + distribution   = "Rocky Linux"
              + error_message  = ""
              + id             = 108962679
              + image          = "108962679"
              + min_disk_size  = 10
              + name           = "RockyLinux 8.4 x64"
              + private        = false
              + regions        = [
                  + "ams2",
                  + "ams3",
                  + "blr1",
                  + "fra1",
                  + "lon1",
                  + "nyc1",
                  + "nyc2",
                  + "nyc3",
                  + "sfo1",
                  + "sfo2",
                  + "sfo3",
                  + "sgp1",
                  + "tor1",
                ]
              + size_gigabytes = 0.57
              + slug           = "rockylinux-8-4-x64"
              + status         = "available"
              + tags           = []
              + type           = "snapshot"
            },
          + {
              + created        = "2022-05-24T17:36:31Z"
              + description    = "RockyLinux 8.5 x64"
              + distribution   = "Rocky Linux"
              + error_message  = ""
              + id             = 108964453
              + image          = "108964453"
              + min_disk_size  = 10
              + name           = "RockyLinux 8.5 x64"
              + private        = false
              + regions        = [
                  + "ams2",
                  + "ams3",
                  + "blr1",
                  + "fra1",
                  + "lon1",
                  + "nyc1",
                  + "nyc2",
                  + "nyc3",
                  + "sfo1",
                  + "sfo2",
                  + "sfo3",
                  + "sgp1",
                  + "tor1",
                ]
              + size_gigabytes = 0.58
              + slug           = "rockylinux-8-x64"
              + status         = "available"
              + tags           = []
              + type           = "snapshot"
            },
        ]
      + sort   = null
    }
```

Note that both the IDs listed don't match the original image IDs that our existing nodes use (which is: `96967120`).

Doing a search of that ID directly gives:

```
 + rocky = {
      + filter = [
          + {
              + all      = false
              + key      = "id"
              + match_by = "exact"
              + values   = [
                  + "96967120",
                ]
            },
        ]
      + id     = "images/9698072944148077665"
      + images = []
      + sort   = null
    }
```
aka: no image found.

My guess is that the image ID associated with the slug `rockylinux-8-x64` has changed.

### Steps to Reproduce

Have a droplet configured with:

```
data "digitalocean_image" "rocky_8" {
  slug = "rockylinux-8-x64"
}

resource "digitalocean_droplet" "software_license_ddm_stage_node" {
  image    = data.digitalocean_image.rocky_8.id
  name     = "hostname.meow.com"
  ...
```

before this issue started, and then run `terraform plan`.

**Terraform Configuration Files**

See above

**Terraform version**

Terraform v1.2.1
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.19.2
+ provider registry.terraform.io/digitalocean/digitalocean v2.11.1
+ provider registry.terraform.io/grafana/grafana v1.14.0
+ provider registry.terraform.io/hashicorp/dns v3.2.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.2
+ provider registry.terraform.io/jfrog/artifactory v6.6.0
+ provider registry.terraform.io/mongodb/mongodbatlas v0.8.2
+ provider registry.terraform.io/statuscakedev/statuscake v1.0.1
+ provider registry.terraform.io/vultr/vultr v2.4.0

**Comment by andrewsomething** [comment]
The purpose of slugs is to point to the most recent image for the distribution or 1-Click application. The ID of the image that slugs point to will change each time a new, updated image in the series is released. By using the data source, you are creating the Droplet using the image ID and not the slug. This will cause the diff you are seeing if a new version of the image is released. Unless you want to rebuild the Droplet each time, instead of using the data source to resolved the image's ID, just use the slug (`rockylinux-8-x64`) itself for the Droplet's image argument.

For this existing Droplet, the easiest way to recover is to replace `data.digitalocean_image.rocky_8.id` with the ID, `96967120`

**Comment by ad8lmondy** [comment]
Thanks for the advice, switching the `image = ` statements to point at the string `96967120` has prevented TF trying to replace the droplets.

More broadly, would it be fair to say that using the `.slug` attribute of the data source (as opposed to the `.id`) would be the way to do this? Or would you recommend not bothering with the extra complication?

**Comment by andrewsomething** [comment]
Generally, I'd recommend skipping the data source in most cases and just using the slug directly if known. Using the `.slug` attribute may have additional complications id the image is retired completely.

**Comment by ad8lmondy** [comment]
Great, thanks for your help!
