### ISSUE TITLE
digitalocean_app does not expose 'urn' attribute

### ISSUE THREAD

**Issue by connorkuehl** [digitalocean/terraform-provider-digitalocean#853]
# Bug Report

---

## Describe the bug
The `digitalocean_app` resource and data source don't seem to expose `urn` attributes like other resources/data sources. This prevents me from using the `digitalocean_project_resources` resource in my Terraform module to add my `digitalocean_app` to a specified project, like so:

```terraform
resource "digitalocean_project_resources" "assigntoproject" {
  project = data.digitalocean_project.myproject.id
  resources = [
    digitalocean_app.myapp.urn,             # this will fail
    digitalocean_droplet.mydroplet.urn,
  ]
}
```

To work around this, I added the app to my project manually using the cloud console web UI.

### Affected Resource(s)

- digitalocean_app

### Expected Behavior

The digitalocean_app resource/data source exports a `urn` attribute so that it can be grouped into a project using Terraform so that users don't have to do this manually with the cloud console web UI.

### Actual Behavior

When attempting to access the `urn` attribute (I know, I know, it's not documented so there's no reason to expect it to exist, this is just for the sake of example)

```console
$ terraform plan
│ Error: Unsupported attribute
│ 
│   on main.tf line 200, in resource "digitalocean_project_resources" "assigntoproject":
│  200:     digitalocean_app.myapp.urn,
│ 
│ This object has no argument, nested block, or exported attribute named "urn".
```

---

### Steps to Reproduce

**Terraform Configuration Files**

**Expected behavior**

**Debug Output**

**Panic Output**

## Additional context

**Important Factoids**

**References**

**Comment by andrewsomething** [comment]
:+1:  Good call out. We'll get this added. It depends on this godo change landing: https://github.com/digitalocean/godo/pull/544

**Comment by connorkuehl** [comment]
Thank you! :slightly_smiling_face:
