### ISSUE TITLE
Not able to install digitalocean provider in terraform

### ISSUE THREAD

**Issue by dhrvjsh** [digitalocean/terraform-provider-digitalocean#875]
# Bug Report

When I'm trying to run "terraform init", it is giving me the error "Failed to install provider"

╷
│ Error: Failed to install provider
│
│ Error while installing digitalocean/digitalocean v2.22.2: could not query provider registry for
│ registry.terraform.io/digitalocean/digitalocean: failed to retrieve authentication checksums for provider:
│ the request failed after 2 attempts, please try again later: Get
│ "https://github.com/digitalocean/terraform-provider-digitalocean/releases/download/v2.22.2/terraform-provider-digitalocean_2.22.2_SHA256SUMS":
│ net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
---

If this issue appears to affect multiple resources, it may be an issue with
Terraform's core, so please mention this. -->

### Steps to Reproduce

1. `terraform init`

**Terraform Configuration Files**
terraform {
  required_providers {
    digitalocean = {
      source = "digitalocean/digitalocean"
      version = "2.22.2"
    }
  }
}

variable "do_token" {}
variable "pvt_key" {}

provider "digitalocean" {
	token = var.do_token
}

data "digitalocean_ssh_key" "Ubuntu" {
	name = "Ubuntu"
}

**Terraform version**
Terraform version: 1.2.8

**Comment by dhrvjsh** [comment]
Hi @andrewsomething 

When i was trying this from WSL 2 in Windows 11 it is not working, but when i tried this from digitalocean droplet it was working fine, not sure where is the issue

**Comment by dhrvjsh** [comment]
Hi @andrewsomething

When i was trying this from WSL 2 in Windows 11 it is not working, but when i tried this from digitalocean droplet it was working fine, not sure where is the issue

**Comment by dhrvjsh** [comment]
Hi @andrewsomething

When i was trying this from WSL 2 in Windows 11 it is not working, but when i tried this from digitalocean droplet it was working fine, not sure where is the issue

**Comment by andrewsomething** [comment]
Looks like there is a similar issue around WSL 2, DNS, and Terraform reported at https://github.com/microsoft/WSL/issues/8022  

Can you try the suggested work-a-rounds?

**Comment by dhrvjsh** [comment]
The workaround works and that solves the problem which I'm facing with terraform init

**Comment by andrewsomething** [comment]
Glad to hear it. Thanks for following up!
