### ISSUE TITLE
cannot create redis cluster user using terraform

### ISSUE THREAD

**Issue by atmosx** [digitalocean/terraform-provider-digitalocean#876]
# Bug Report

The [database_user](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/database_user) resource cannot create Redis users. Here's the code sample:

```
resource "digitalocean_database_user" "new_relic_user_dev" {
  cluster_id = digitalocean_database_cluster.redis_router_development.id
  name       = "newrelic"
}
```

And the error when running `apply`:

```
digitalocean_database_user.new_relic_user_dev: Creating...

│ Error: Error creating Database User: POST https://api.digitalocean.com/v2/databases/xxx-9c44-4078-xxx/users: 500 (request "a51168e1-a618-45a5-af8c-xxx") Server Error

│   with digitalocean_database_user.new_relic_user_dev,
│   on router-redis.tf line 29, in resource "digitalocean_database_user" "new_relic_user_dev":
│   29: resource "digitalocean_database_user" "new_relic_user_dev" {
```

### Affected Resource(s)
- digitalocean_database_user
- digitalocean_database_cluster

### Expected Behavior
Create `newrelic` user.

### Actual Behavior
API reports 500 error.

### Steps to Reproduce
See provided code.

**Terraform version**
Terraform v1.1.7
+ provider registry.terraform.io/digitalocean/digitalocean v2.14.0
+ provider registry.terraform.io/dopplerhq/doppler v1.1.2
+ provider registry.terraform.io/hashicorp/random v3.4.2

ps. If this behaviour is expected, then it should be mentioned explicitly in [digitalocean_database_user](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/database_user) page.

**Comment by atmosx** [comment]
Apparently, the API doesn't support Redis user creation either 🤔 - is this by design?

**Comment by andrewsomething** [comment]
That is correct. DigitalOcean's managed Redis does not currently support any user management via the API or control panel. That said, a 500 Server Error is not a very helpful response. I'll raise this with the team internally. Thanks for flagging this!
