### ISSUE TITLE
Change `id` value of `digitalocean_database_replica` to match replica UUID

### ISSUE THREAD

**Issue by timkrins** [digitalocean/terraform-provider-digitalocean#878]
### Is your feature request related to a problem? Please describe.

The `id` that is returned by the current `digitalocean_database_replica` resource is generated (in `makeReplicaId`) rather than fetched from the DigitalOcean API.
The new `id` field was added to the API yesterday, under
`{"replicas":[{"id" ...` at `https://api.digitalocean.com/v2/databases/{cluster_id}/replicas`
It has not yet landed in the public API documentation, but it is there.

### Describe the solution you'd like

The `digitalocean_database_replica` `id` field should track the DigitalOcean replica UUID so that replicas can be used with the `digitalocean_database_firewall` provider.
 
### Describe alternatives you've considered

Not sure of any other alternative.

### Additional context

https://github.com/digitalocean/terraform-provider-digitalocean/issues/224
https://github.com/digitalocean/terraform-provider-digitalocean/issues/639
https://github.com/digitalocean/terraform-provider-digitalocean/issues/799

**Comment by cphalpin** [comment]
I'm currently having to hardcode the id of my replica since there doesn't seem to be any way to get it from Terraform at all (I tried fetching it from the `digitalocean_database_replica` data source as a workout around). `doctl` returns the UUID in the `id` field as expected.

**Comment by danaelhe** [comment]
Hi there, 

Thank you for bringing this to our attention. This has been addressed in #921 and will be available in the next release (which we plan to do in the next few days).

Thank you so much for your feedback! Please don't hesitate to reach out again. 

Dana

**Comment by timkrins** [comment]
Hello,
Thanks for completing this!

Can I ask how importing an existing `digitalocean_database_replica` resource works?

I can't seem to get the UUID from imported resources.
I'm still investigating but will update when I have done a bit more research.

**Comment by timkrins** [comment]
I think with the above changes the replica UUID is only ever assigned when the replica is created via terraform, rather than imported.
I managed to perform an import, then export my (remote) terraform state, update the UUID that I got from the DO UI manually in the JSON, then push my state back up.
Maybe there is a way to look up the UUID when performing the `terraform import` command?

**Comment by andrewsomething** [comment]
Good catch @timkrins I have a PR up that should fix the problem for imports https://github.com/digitalocean/terraform-provider-digitalocean/pull/964
