### ISSUE TITLE
`digitalocean_certificate.id` does not match `doctl compute certificate list`

### ISSUE THREAD

**Issue by unredundant** [digitalocean/terraform-provider-digitalocean#881]
Hey 👋  this is either a bug, or at minimum quite unintuitive.  

When you run `doctl compute certificate list`, it calls `ID` what the `digitalocean_certificate` resource refers to as `uuid`.  And when you look at what `digitalocean_certificate.id` is, it is equivalent to what `doctl compute certificate list` refers to as `name`.  

IMO, `digitalocean_certificate.uuid` should be deprecated, and instead the uuid should just be the value for `digitalocean_certificate.id`.

**Comment by andrewsomething** [comment]
Hi @unredundant,

Unfortunately, the UUID of a certificate is not an appropriate ID for a Terraform resource. Terraform requires that the ID be stable while Let's Encrypt certificates change their ID when they are renewed. Using the UUID would lead to drift, causing the Terraform wanting to recreate the certificate each time it is renewed (see: https://github.com/digitalocean/terraform-provider-digitalocean/issues/318). As the names for certificates have a uniqueness requirement, they can serve this purpose. The names persist across certificate renewals.
