### ISSUE TITLE
Terraform provider v2.23.0 was released but not published

### ISSUE THREAD

**Issue by dghubble** [digitalocean/terraform-provider-digitalocean#888]
# Bug Report

Terraform provider v2.23.0 was released but never actually published to the Terraform Registry. The latest as of this writing is v2.22.3

https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs

You may need to login to the Terraform Registry and sync the provider with this project to pickup the latest GitHub release.

---

### Steps to Reproduce

**Terraform Configuration Files**

**Terraform version**

**Debug Output**

**Panic Output**

## Additional context

**Important Factoids**

**References**

**Comment by dghubble** [comment]
cc @andrewsomething who performed the release

**Comment by andrewsomething** [comment]
Thanks for flagging this. Looks like we somehow ended up with a "release" that only includes the source, not the binaries and signatures. Those ended up in a "pre-release," both pointing at the same commit and tag.

![image](https://user-images.githubusercontent.com/46943/194914401-e054f9b0-e400-4140-848a-a9f302766d00.png)

Think I should be able to clear it up by un-publishing the source only release.
