### ISSUE TITLE
digitalocean_database_cluster: redis version ignored

### ISSUE THREAD

**Issue by leitmedium** [digitalocean/terraform-provider-digitalocean#891]
# Bug Report

---

## Describe the bug
When deploying a redis database cluster the version setting gets ignored.

### Affected Resource(s)
- digitalocean_database_cluster

### Expected Behavior
When a dedicated version, e.g. "6" is being set, deploy the correct version.

### Actual Behavior
Instead of version 6 the version 7 has been deployed. Multiple runs of terraform did not change that.

### Steps to Reproduce

**Terraform Configuration Files**
```
resource "digitalocean_database_cluster" "redis-staging" {
  name                 = "redis-staging"
  engine               = "redis"
  version              = "6"
  size                 = "db-s-1vcpu-1gb"
  node_count           = "1"
  region               = "fra1"
  private_network_uuid = digitalocean_vpc.vpc-kubernetes-staging-fra1.id
  tags                 = [ "staging" ]
}
```

**Terraform version**
```
Terraform v1.2.5
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.26.0
+ provider registry.terraform.io/digitalocean/digitalocean v2.23.0
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/google v4.41.0
+ provider registry.terraform.io/hashicorp/google-beta v4.41.0
+ provider registry.terraform.io/hashicorp/helm v2.7.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.14.0

Your version of Terraform is out of date! The latest version
is 1.3.3. You can update by downloading from https://www.terraform.io/downloads.html
```

**References**
The version of redis had been a topic here in the past:  https://github.com/digitalocean/terraform-provider-digitalocean/issues/343

**Comment by andrewsomething** [comment]
Hi @leitmedium,

This is the expected behavior. DigitalOcean no longer supports creating Redis v6 clusters and will be auto updating existing v6 clusters to v7. 

https://docs.digitalocean.com/release-notes/redis/#2022-09-07
