### ISSUE TITLE
Unable to import digitalocean_kubernetes_cluster

### ISSUE THREAD

**Issue by mkroman** [digitalocean/terraform-provider-digitalocean#892]
# Bug Report

---

## Describe the bug

When trying to import an existing Kubernetes Cluster, I get the following error:

```
digitalocean_kubernetes_cluster.development: Importing from ID "6e2e943a-00d3-4fc9-8cf2-5f7c421b04fd"...
╷
│ Error: an object with 21 attributes is required (14 given)
```

### Affected Resource(s)

- digitalocean_kubernetes_cluster

### Expected Behavior

The cluster should've been imported without issues.

### Actual Behavior

The mentioned error happens.

### Steps to Reproduce

I'm not sure how reproducible it is, as this is an older cluster.

1. Create a cluster in the web control panel
2. `terraform import digitalocean_kubernetes_cluster.development <id>`

**Terraform Configuration Files**

```hcl
resource "digitalocean_kubernetes_cluster" "development" {
  name         = "dev-cluster"
  region       = var.region
  version      = "1.22.13-do.0"
  vpc_uuid     = digitalocean_vpc.development.id
  tags         = concat(var.default_tags, [])
  auto_upgrade = true
  surge_upgrade = true
  ha           = true

  maintenance_policy {
    start_time = "04:00"
    day        = "sunday"
  }

  node_pool {
    name = "g-2vcpu-8gb"
    size = "g-2vcpu-8gb"
    node_count = 2
  }
}

```

**Terraform version**

**Debug Output**

https://gist.github.com/mkroman/f197e45414250db2935fdbf834c55e53

**Important Factoids**

The cluster is running DOKS v1.22.13-do.0 and has 2 node pools.

**Comment by andrewsomething** [comment]
Hi @mkroman,

Thank you for raising this issue. I've been able to reproduce it when importing a cluster with multiple node pools. Importing a cluster with a single node pool still works as expected. The issue seems to be caused by some incompatibility in our approach of importing multiple node pools with Terraform v1.3.x.

While we work to resolve the issue, there is a workaround.  With Terraform v1.2.9, the import works as expected. After running the initial import with v1.2.9, the resources can be managed with v1.3.x like normal.

Previous versions of Terraform can be downloaded from https://developer.hashicorp.com/terraform/downloads

**Comment by mijndert** [comment]
I can confirm this works on version 1.2.9.

**Comment by holms** [comment]
```
Terraform v1.3.5
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.29.0
+ provider registry.terraform.io/digitalocean/digitalocean v2.25.2
```

And I've got gateway timeout error:

```
 Error: Error retrieving database cluster: GET https://api.digitalocean.com/v2/databases/48f9d49f-f4b8-49b4-aac1-772caf381da7: 504 <!DOCTYPE html>
│ <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
│ <!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
│ <!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
│ <!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
│ <head>
│ 
│ 
│ <title>api.digitalocean.com | 504: Gateway time-out</title>
│ <meta charset="UTF-8" />

```

Any recommendations?

**Comment by killshotrevival** [comment]
The issue is still there with version `v1.4.0`, but works as expected with `1.2.9`
