### ISSUE TITLE
Create space resource via terraform

### ISSUE THREAD

**Issue by alexandrubau** [digitalocean/terraform-provider-digitalocean#900]
I would like to be able to create a new DigitalOcean Space from terraform config file, similarly to how I am able to create a new Container Registry resource.

**Comment by alexandrubau** [comment]
Nevermind, I've figured it out. I thought I am able to create multiple Spaces but in fact each Space is actually a Bucket.

**Comment by andrewsomething** [comment]
Hey @alexandrubau,

That's right. The `digitalocean_spaces_bucket` resource. It should allow you to create a new DigitalOcean Space from Terraform:

https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/spaces_bucket

Let us know if there's anything else that would help you get up and running.
