### ISSUE TITLE
digitalocean_database_replica: size parameter forces replacement

### ISSUE THREAD

**Issue by mijndert** [digitalocean/terraform-provider-digitalocean#902]
# Bug Report

---

## Describe the bug
When I try to change the `size` parameter on a digitalocean_database_replica resource, Terraform forces replacement on that resource. This is also defined in the provider:

```
"size": {
  Type:     schema.TypeString,
  Optional: true,
  ForceNew: true,
},
```

But I can do the change in the Digitalocean web UI without replacing the entire database replica, which to me would mean the API is ready to do so.

### Affected Resource(s)
- digitalocean_database_replica

### Expected Behavior
Not replace the digitalocean_database_replica resource when the `size` parameter is changed.

### Actual Behavior
Terraform forces a replacement of the digitalocean_database_replica resource when the `size` parameter is changed.

### Steps to Reproduce
- terraform apply

**Terraform Configuration Files**
```
resource "digitalocean_database_cluster" "postgresql" {
  engine               = "pg"
  name                 = var.db_cluster_name
  version              = var.db_cluster_version
  node_count           = var.db_node_count
  region               = var.region
  size                 = var.db_cluster_size
  private_network_uuid = data.digitalocean_vpc.this.id
}

resource "digitalocean_database_replica" "postgresql" {
  cluster_id = digitalocean_database_cluster.postgresql.id
  name       = var.db_cluster_replica_name
  region     = var.region
  size       = var.db_cluster_replica_size
}
```
```
module "databases" {
  source = "../../../modules/databases"

  # PostgreSQL
  db_cluster_name      = "db-postgresql-ams3-toot-community"
  db_cluster_version   = "14"
  db_node_count        = "1"
  db_cluster_size      = "db-s-2vcpu-4gb"

  # Postgresql replica
  db_cluster_replica_name = "db-ro-postgresql-ams3-toot-community"
  db_cluster_replica_size = "db-s-4vcpu-8gb"

[...]
}
```

**Terraform version**
```
Terraform v1.3.4
on darwin_amd64
+ provider registry.terraform.io/digitalocean/digitalocean v2.24.0
```

## Additional context
None

**Important Factoids**
None

**References**
None

**Comment by mijndert** [comment]
@andrewsomething any update? Thanks.

**Comment by jameyg** [comment]
@andrewsomething Yes this isn't an enhancement, this is a bug. I'm seeing exactly the same thing.

It seems impossible to get my local state in sync with the DigitalOcean replica's state. Setting/adding/removing the size parameter, whatever I do it triggers a replacement so the state never becomes settled.

**Comment by andrewsomething** [comment]
@jameyg, it was labeled as an enhancement as when the issue was first opened, the DigitalOcean API did not support resizing read-only replicas at all. As this is now possible, I've opened a PR (#977) to add support here as well.
