### ISSUE TITLE
Support Uptime Checks and Alerts

### ISSUE THREAD

**Issue by goodhoko** [digitalocean/terraform-provider-digitalocean#908]
### Is your feature request related to a problem? Please describe.
I'd like to manage my uptime checks and corresponding alerts with this provider.

### Describe the solution you'd like
Add support for the [uptime check](https://docs.digitalocean.com/reference/api/api-reference/#operation/uptime_checks_list) and [alert](https://docs.digitalocean.com/reference/api/api-reference/#operation/uptime_check_alerts_list) resources.
 
### Describe alternatives you've considered
There really is no alternative to this apart from not using this provider at all.

**Comment by danaelhe** [comment]
Hi there, 

Thanks for this suggestion. We will look into supporting `uptime` and `alerts` in the provider and get to implementation when we can- hopefully soon.

**Comment by goodhoko** [comment]
May I give it a shot a submit a PR for this? .)

**Comment by danaelhe** [comment]
You're more than welcome to take a stab at creating a PR for it! We love reviewing PR's :)

**Comment by danaelhe** [comment]
We've added support for Uptime Checks and Alerts. It will be available in the next release (which we plan to do in the next week or so). Thank you for reaching out!

**Comment by goodhoko** [comment]
Perfect! Thanks a lot!
