### ISSUE TITLE
CloudQuery Source Plugin?

### ISSUE THREAD

**Issue by yevgenypats** [digitalocean/terraform-provider-digitalocean#917]
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are asked for a [DigitalOcean source plugin](https://www.cloudquery.io/docs/plugins/sources/digitalocean/overview), and we shipped a first version.

As we have limited capacity to maintain all plugins we are usually looking for the official vendor to help maintain it (Similar to terraform).

I was curious if this would be an interesting collaboration, where we can help with the initial version (already implemented) and you will help maintain it?

This will give your users the ability to sync [DigitalOcean](https://www.cloudquery.io/docs/plugins/sources/digitalocean/overview) APIs to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

**Comment by mikeberezowski** [comment]
Hello Yevgeny,
 Thank you for your interest in DigitalOcean and for bringing this to our attention. Our team is responsible for developer tools including third party integrations and plugins. Unfortunately we're currently in a similar situation where we don't have the capacity to take ownership of new plugins right now.

I will add this plugin to our list of potential projects to pick up in the future. When we have the capacity to take ownership we'll reach out to you.

Thank you,
Mike Berezowski
