### ISSUE TITLE
adding `ha = true` to existing do_kubernetes_cluster (1.23.14) fails

### ISSUE THREAD

**Issue by gladiatr72** [digitalocean/terraform-provider-digitalocean#926]
# Bug Report

---

## Describe the bug

according to DO, adding HA backplane functionality is supported post kube 1.21. It works from the web console; however, the plan after adding `ha = true` to an existing cluster indicates a destroy/create cycle would be necessary.  It appears the effort to support `ha` as a valid _on-create_ parameter might pre-date DO's support for enabling HA post-creation.

### Affected Resource(s)
  * digitalocean_kubernetes_cluster

### Expected Behavior

applying a plan with a newly truthful _ha_ parameter would provide a non-destructive update

**Terraform Configuration Files**

```

  resource digitalocean_kubernetes_cluster cluster {
    name    = "do-2"
    region  = var.do_region
    version = "1.23.14-do.0"

    ha = true /* post creation setting */

    node_pool {
      name       = "default-node-pool"
      size       = "s-2vcpu-4gb"
      node_count = 4
    }
  }

```

**Terraform version**

Terraform v0.15.5 on linux_amd64
+ provider registry.terraform.io/digitalocean/digitalocean v2.26.0

**Comment by maiku1008** [comment]
Any news on this? It would actually be very helpful.
