### ISSUE TITLE
New`digitalocean_certificate ` created after each `terraform apply`

### ISSUE THREAD

**Issue by leonvisscher** [digitalocean/terraform-provider-digitalocean#928]
# Bug Report

I am using the `digitalocean_certificate` resource for my k8s cluster managed with terraform:
```
resource "digitalocean_certificate" "cert" {
  name    = "my-name"
  type    = "lets_encrypt"
  domains = ["*.example.com"]
}
```
However, every time I run `terraform apply` it recreates a certificate instead of just using the one it first created.

---

### Affected Resource(s)
- digitalocean_certificate

### Expected Behavior
Create the certificate once, and then re-use it after running `terraform apply`

**Comment by andrewsomething** [comment]
Hi @leonvisscher, 

Thanks for raising this issue.  It looks like when you create a wildcard (e.g. `*.example.com`) cert the DigitalOcean certificates API adds the base domain (e.g. `example.com`) to the certificate as well. So the prompt to recreate is cause by Terraform attempting to remove that.

To work around this issue, you can include the base domain as well:

```hcl
resource "digitalocean_certificate" "cert" {
  name    = "my-name"
  type    = "lets_encrypt"
  domains = [
    "example.com",
    "*.example.com"
  ]
}
```

This is not very intuitive. If this is the intended behavior for the API, we could potentially suppress the diff for this case.
