### ISSUE TITLE
Add trusted sources argument to digitalocean_database_cluster resource

### ISSUE THREAD

**Issue by leonvisscher** [digitalocean/terraform-provider-digitalocean#946]
### Is your feature request related to a problem? Please describe.
I am using terraform to fully manage my Digital Ocean infrastructure. The only thing that I am missing is that I cannot define the trusted sources for a digitalocean_database_cluster resource through terraform. I think the only way to do this right now is through the UI:

![image](https://user-images.githubusercontent.com/17271164/218410265-a350c481-8ce3-43dc-996d-ca564786a90a.png)

### Describe the solution you'd like
It would be great if `trusted_sources` gets added as a [digitalocean_database_cluster argument.](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/database_cluster#argument-reference)
 
### Describe alternatives you've considered
Add it through UI.

**Comment by andrewsomething** [comment]
Trusted sources for a database cluster can be managed using the `digitalocean_database_firewall` resource. e.g.

```hcl
resource "digitalocean_database_firewall" "example-fw" {
  cluster_id = digitalocean_database_cluster.postgres-example.id

  rule {
    type  = "ip_addr"
    value = "192.168.1.1"
  }

  rule {
    type  = "droplet"
    value = digitalocean_droplet.web.id
  }
}
```

https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/database_firewall
