### ISSUE TITLE
Forced replacement of database resource due to change of version in API response

### ISSUE THREAD

**Issue by c-w** [digitalocean/terraform-provider-digitalocean#948]
# Bug Report

---

## Describe the bug

See below for a minimal example of a terraform script which I use to manage a Postgres database. Up until yesterday, this script worked fine: applying created the database and re-applying it would leave the database alone.

Starting today, re-applying the script forced a replacement of the resource as the API now returns "14.5" for the version number which Terraform interprets as a diff and destroying/re-creating the database (!).

Note that I can't even pin "14.5" as the exact version to protect against this as this leads to an "invalid cluster engine version" error.

### Affected Resource(s)

- digitalocean_database_cluster

### Expected Behavior

I expect that running `terraform apply` without changes to the configuration doesn't modify the database.

### Actual Behavior

Actually running `terraform apply` destroys and re-creates the database.

### Steps to Reproduce

1. `terraform apply`

**Terraform Configuration Files**

```hcl
variable "name" {
  type = string
}

locals {
  postgres_version = "14"
  region = "nyc3"
}

resource "digitalocean_database_cluster" "postgres" {
  name       = var.name
  engine     = "pg"
  version    = local.postgres_version
  size       = "db-s-1vcpu-2gb"
  region     = local.region
  node_count = 1

  private_network_uuid = digitalocean_vpc.postgres.id
}

resource "digitalocean_vpc" "postgres" {
  name   = var.name
  region = local.region
}

terraform {
  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "~> 2.25.2"
    }
  }
}
```

**Terraform version**

1.3.8

**Debug Output**

Relevant part from stdout:

```
  # digitalocean_database_cluster.postgres must be replaced
-/+ resource "digitalocean_database_cluster" "postgres" {
      ~ database             = "defaultdb" -> (known after apply)
      ~ host                 = "REDACTED-do-user-9785225-0.b.db.ondigitalocean.com" -> (known after apply)
      ~ id                   = "e7fdb5d1-76f6-408e-985d-b41f62bc191b" -> (known after apply)
        name                 = "REDACTED"
      ~ password             = (sensitive value)
      ~ port                 = 25060 -> (known after apply)
      ~ private_host         = "private-REDACTED-do-user-9785225-0.b.db.ondigitalocean.com" -> (known after apply)
      ~ private_uri          = (sensitive value)
      - tags                 = [] -> null
      ~ uri                  = (sensitive value)
      ~ urn                  = "do:dbaas:e7fdb5d1-76f6-408e-985d-b41f62bc191b" -> (known after apply)
      ~ user                 = "doadmin" -> (known after apply)
      ~ version              = "14.5" -> "14" # forces replacement
        # (5 unchanged attributes hidden)
    }
```

## Additional context

DigitalOcean Provider version: 2.25.2

**Comment by lybrus** [comment]
😱

```hcl
lifecycle {
  prevent_destroy = true # 🙏
}
```

**Comment by c-w** [comment]
The fix I went with:

```hcl
lifecycle {
  ignore_changes = [
    version,
  ]
}
```

Anyways this should be resolved on the API side as it's very unexpected behavior in my opinion.

**Comment by dtrd-tadej** [comment]
We are experiencing the same issue with redis.

## Terraform Configuration Files

```terraform
resource "digitalocean_database_cluster" "redis" {
  name                     = "some-name"
  engine                   = "redis"
  version                  = 7
  size                        = "db-1"
  region                    = "fra1"
  node_count           = 1
}
```

## Debug Output

```terraform
resource "digitalocean_database_cluster" "redis" {
  ...
  ~ version              = "7.0.5" -> "7"
  ...
}
```

## Additional context
DigitalOcean Provider version: 2.25.2
Terraform version: 1.2

**Comment by andrewsomething** [comment]
Thank you for raising this issue. It has been flagged internally with the DigitalOcean Database team who are reverting a change on the API side.

**Comment by andrewsomething** [comment]
The API change has been reverted, and I can not longer reproduce the issue. Thanks again for flagging this and sorry for the inconvenience.
