### ISSUE TITLE
Add possibility to use backup_restore for a new database cluster

### ISSUE THREAD

**Issue by bery** [digitalocean/terraform-provider-digitalocean#968]
### Is your feature request related to a problem? Please describe.
I would like to be able to restore a managed database backup to a new cluster. It's very frustrating to have to create a backup first and then restore it. 

### Describe the solution you'd like
Add the possibility to take advantage of DO API https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_create_cluster and backup_restore option
 
### Describe alternatives you've considered
Switching to AWS

### Additional context
None is needed if its feasible

**Comment by danaelhe** [comment]
Hi @bery !

Thank you for the write up! It's funny you bring this up because I actually just added this functionality in another DO tool, [doctl](https://github.com/digitalocean/doctl/pull/1346), so it probably won't be too much of an effort to add it terraform too. I've created a ticket for this and have moved it to the top of the backlog, hopefully we can get to it soon.

Thanks,
Dana

**Comment by bery** [comment]
That's what I call perfect timing! Thank you very much @danaelhe, if you need any help with testing, let me know!

**Comment by andrewsomething** [comment]
Closed via https://github.com/digitalocean/terraform-provider-digitalocean/pull/970

**Comment by AAverin** [comment]
The documentation and examples at https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/database_cluster just don't make sense to me.
The field is called `database_name` and example implies that a database is used for the backup, while description states `Create a new database cluster based on a backup of an existing cluster`.
So is it a cluster or a database? 
Example also shows how to restore backup from another, already existing cluster and its database.
What if neither the cluster and database don't exist yet and are just being created?

**Comment by AAverin** [comment]
@andrewsomething @danaelhe could you please clarify?

**Comment by danaelhe** [comment]
Hi there, 

Thank you for the write up- I've answered your questions in sections:

> Are there examples on how does it work exactly, maybe some article with an explanation?
Which db cluster are you trying to create? [Here's](https://docs.digitalocean.com/products/databases/postgresql/how-to/restore-from-backups/) an article for back ups for Postgres. And [here's](https://docs.digitalocean.com/products/databases/mysql/how-to/restore-from-backups/) an article on back ups for MySQL.


> Would DO automatically do backups of my managed database? 
DigitalOcean managed PostgreSQL and MySQL database clusters take automated daily backups. This is in the API documentation [here](https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_create_cluster), but looks like we should also include it in the terraform provider documentation to mitigate confusion. I can create a PR for that documentation add in a bit. 

> Also, wouldn't this fail if backup cluster doesn't exist yet? I am trying to build a cluster and configure it to use its own backups using backup_restore.
> Error creating database cluster: POST https://api.digitalocean.com/v2/databases: 404 (request "2f49d2c9-...") cluster not found
> Example also shows how to restore backup from another, already existing cluster and its database.
> What if neither the cluster and database don't exist yet and are just being created?

In the example, we wait for the creation of the original database cluster to complete before we create the back up database cluster via the `depends_on`:
```
resource "digitalocean_database_cluster" "doby" {
  name       = "dobydb"
  engine     = "pg"
  version    = "11"
  size       = "db-s-1vcpu-2gb"
  region     = "nyc1"
  node_count = 1
  tags       = ["production"]
}

resource "digitalocean_database_cluster" "doby_backup" {
  name       = "dobydupe"
  engine     = "pg"
  version    = "11"
  size       = "db-s-1vcpu-2gb"
  region     = "nyc1"
  node_count = 1
  tags       = ["production"]

  backup_restore {
    database_name = "dobydb"
  }

  depends_on = [
    digitalocean_database_cluster.doby
  ]
}
```

Are you still running into this 404 with the `depends_on`? 


> The field is called database_name and example implies that a database is used for the backup, while description states Create a new database cluster based on a backup of an existing cluster.
> So is it a cluster or a database?
`database_name` takes in the cluster name, not the specific database within a cluster. I can see how that's confusing, `database_cluster_name` would've probably been more clear. We wanted to be consistent with the naming done in the API [here](https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_create_cluster) but we made sure to be explicit in the documentation:
>  [database_name](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/database_cluster#database_name) - (Required) The name of an existing database cluster from which the backup will be restored.

Please let me know if I've understood/answered all your questions!

Thanks,
Dana
