### ISSUE TITLE
Provider produced inconsistent final plan when running apply for a record with type AAAA pointing to a droplet

### ISSUE THREAD

**Issue by Zarickan** [digitalocean/terraform-provider-digitalocean#981]
# Bug Report

---

## Describe the bug
Initially created a droplet with `ipv6=false` noticed the mistake when terraform apply failed creating a AAAA record pointing to the ipv6 address of the droplet. Changed `ipv6=true` and ran apply again which gave me the following error:
```
Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for digitalocean_record.name_of_record to include new values learned so far
│ during apply, provider "registry.terraform.io/digitalocean/digitalocean" produced an invalid new value for
│ .value: was cty.StringVal(""), but now cty.StringVal("2a03:b0c0:2:d0::13cc:d001").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Error assigning resources to default project: Error assigning resources: POST https://api.digitalocean.com/v2/projects/project_guid/resources: 500 (request "0c14e154-2f54-4c5c-ad63-1e49afdde7f2") Server Error
```

### Affected Resource(s)
- digitalocean_record

### Expected Behavior
Record should be created/updated pointing to the ipv6 address of the droplet

### Actual Behavior
Terraform apply failed and the record was not updated

### Steps to Reproduce
0. Define a domain
1. Define a droplet with `ipv6=false`
2. Define a record under the domain with `type="AAAA"` and `value = digitalocean_droplet.droplet_name.ipv6_address`
3. Run `terraform apply` should fail with error since droplet ipv6 will be empty
4. Change droplet to `ipv6=true`
5. Run `terraform apply` again 

**Terraform version**
```
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/digitalocean/digitalocean v2.27.1

Your version of Terraform is out of date! The latest version
is 1.4.5. You can update by downloading from https://www.terraform.io/downloads.htm
```

**Comment by andrewsomething** [comment]
Thanks for flagging this issue @Zarickan! I've opened a PR that should prevent it in the future.
