### ISSUE TITLE
Spaces bucket creation fails with 404

### ISSUE THREAD

**Issue by SkeLLLa** [digitalocean/terraform-provider-digitalocean#996]
# Bug Report

---

## Describe the bug

If spaces bucket creation takes more than 1 minute, it 100% will fail with 404 error. However bucket is created.
```
│ Error: NoSuchBucket: 
│       status code: 404, request id: , host id: 
```

### Affected Resource(s)
- digitalocean_spaces_bucket

### Expected Behavior
Bucket is created. And no 404 error appear.

### Actual Behavior
Bucket created in DO, but it remains not created in terraform state.

### Steps to Reproduce

Copy example from DO provider docs for creating spaces bucket.
Run terraform apply and make sure that bucket creation takes more than 1min. If needed create more than one.

The only way to get proper state is to run `terraform untaint`

**Comment by danaelhe** [comment]
Hi there,

Thanks for the write up! I'm trying to reproduce the error on my end and cannot get the bucket creation to last more than 1 minute. I've tried creating more than one bucket and it still completes in less than 13 seconds. How many buckets are you creating that's making it take longer than 1 minute? Are you adding any other configuration to make the creation last longer?

**Comment by muratoreT** [comment]
Same problem here, only creating 1 bucket. My resource:

```hcl
resource "digitalocean_spaces_bucket" "test_space" {
  lifecycle {
    prevent_destroy = true
  }

  name   = "test"
  region = "fra1"
  acl    = "private"
}
```

Space bucket is being created successfully in DO in about 20 Seconds, but I'm getting the same error as OP.

**Comment by danaelhe** [comment]
> Same problem here, only creating 1 bucket. My resource:
> 
> ```terraform
> resource "digitalocean_spaces_bucket" "test_space" {
>   lifecycle {
>     prevent_destroy = true
>   }
> 
>   name   = "test"
>   region = "fra1"
>   acl    = "private"
> }
> ```
> 
> Space bucket is being created successfully in DO, but I'm getting the same error as OP.

Interesting...and this is when the bucket creation takes longer than a minute as well?

**Comment by muratoreT** [comment]
@danaelhe I've tested it again. When I started the Terraform run, I saw the Bucket at the DO Dashboard after about 20 seconds. After 1 minute, the run failed with the following error:

```
Error: NoSuchBucket: status code: 404, request id: , host id:
with module.ok_bon.digitalocean_spaces_bucket.test_space
on modules/test/space.tf line 11, in resource "digitalocean_spaces_bucket" "test_space"
```

My Terraform resource:

```hcl
resource "digitalocean_spaces_bucket" "test_space" {
  lifecycle {
    prevent_destroy = true
  }

  name   = "test-ok"
  region = "fra1"
  acl    = "private"
}
```

**Comment by SkeLLLa** [comment]
@danaelhe I think the problem is that DO can't give 100% guarantee that bucket creation request will finish in less than 60s. Also as far as we can see there are no guarantees that if requests returned non 2XX code, then bucket creation is failed.

Therefore for terraform provider it's required to have either larger timeout or to have additional check with retries, since DO API is no reliable. Otherwise each run of terraform will require manual intervention to fix incorrect state which is terrible UX.

**Comment by danaelhe** [comment]
Thank you so much for the continued dialogue as we try to troubleshoot this. 
Opened a PR [here](https://github.com/digitalocean/terraform-provider-digitalocean/pull/999) 🤞 

The only child function that `resourceDigitalOceanBucketCreate` uses a 1 minute timeout is the retryOnAwsCode so updating that to 5 minutes to hopefully mitigate the errors on successful bucket creations.

Anyone who's been experiencing this issue willing to test this out?
